// ── Shared colour palette + formatters (single source of truth) ──────────────
export {
  C,
  escapeHtml,
  fmtINR,
  fmtINRFull,
  fmtINRShort,
  shortTitle
} from '@/features/finance/common/components/ReportsShared';

export const REPORTS_METADATA_ALL = {
  REVENUE_DASHBOARD: {
    code: 'REVENUE_DASHBOARD',
    title: 'Revenue Analytics Dashboard',
    desc: 'Consolidated revenue metrics, segment splits, customer rankings and trends',
    kind: 'dashboard',
    icon: 'lavender',
    total: 23456,
    count: 123,
    chip: 'analytics'
  },
  REVENUE_ALL: {
    code: 'REVENUE_ALL',
    title: 'All Revenue Reports',
    desc: 'Catalog of statutory and analytical reports including BR11 & BR27 registers',
    kind: 'all_reports',
    icon: 'info',
    total: 3455,
    gst: 4,
    count: 23,
    chip: 'catalog'
  }
};

export const REPORTS_METADATA = {
  REVENUE_DASHBOARD: {
    code: 'REVENUE_DASHBOARD',
    title: 'Revenue Analytics Dashboard',
    desc: 'Consolidated revenue metrics, segment splits, customer rankings and trends',
    kind: 'dashboard',
    icon: 'lavender',
    total: 23456,
    count: 123,
    chip: 'analytics'
  },
  REVENUE_ALL: {
    code: 'REVENUE_ALL',
    title: 'All Revenue Reports',
    desc: 'Catalog of statutory and analytical reports including BR11 & BR27 registers',
    kind: 'all_reports',
    icon: 'info',
    total: 3455,
    gst: 4,
    count: 23,
    chip: 'catalog'
  },
  REVENUE_BR11: {
    code: 'REVENUE_BR11',
    title: 'Invoice-wise Revenue',
    desc: 'Master invoice register — Enterprise, Retail & Special Events with GST decomposition',
    kind: 'br11',
    icon: 'mint',
    total: 23456,
    count: 123,
    chip: 'register'
  },
  REVENUE_BR27: {
    code: 'REVENUE_BR27',
    title: 'Credit Notes — Customer',
    desc: 'Customer refunds and adjustments against issued invoices',
    kind: 'br27',
    icon: 'coral',
    total: 23456,
    count: 123,
    chip: 'refunds'
  },
  REVENUE_BY_SEGMENT: {
    code: 'REVENUE_BY_SEGMENT',
    title: 'By Customer Segment',
    desc: 'Revenue split across Government, Private and Home Subscriber segments',
    kind: 'segment',
    icon: 'teal',
    total: 23456,
    count: 123,
    chip: 'segments'
  },
  REVENUE_BY_CUSTOMER: {
    code: 'REVENUE_BY_CUSTOMER',
    title: 'Top Customers',
    desc: 'Ranking of unique customer accounts by gross invoiced value',
    kind: 'customer',
    icon: 'amber',
    total: 23456,
    count: 123,
    chip: 'customers'
  }
};

export const CODE_TO_PATH = {
  REVENUE_DASHBOARD: '',
  REVENUE_ALL: 'all',
  REVENUE_BR11: 'invoice-wise-revenue',
  REVENUE_BR27: 'credit-notes-customer',
  REVENUE_BY_SEGMENT: 'by-segment',
  REVENUE_BY_CUSTOMER: 'by-customer'
};

export const PATH_TO_CODE = {
  ...Object.fromEntries(Object.entries(CODE_TO_PATH).map(([code, path]) => [path, code])),
  br11: 'REVENUE_BR11',
  br27: 'REVENUE_BR27'
};

export const BR11_SCHEMA = [
  { k: 'invNo', label: 'Invoice No', fmt: 'mono' },
  { k: 'invDate', label: 'Date' },
  { k: 'docType', label: 'Doc', fmt: 'doc' },
  { k: 'revType', label: 'Rev Type', fmt: 'rev' },
  { k: 'custName', label: 'Customer', fmt: 'custcell' },
  { k: 'custType', label: 'Segment', fmt: 'cust' },
  { k: 'gstCat', label: 'GST', fmt: 'gst' },
  { k: 'incomeType', label: 'Income' },
  { k: 'taxable', label: 'Taxable', num: true, fmt: 'inr' },
  { k: 'totGst', label: 'Total GST', num: true, fmt: 'inr' },
  { k: 'invVal', label: 'Inv Value', num: true, fmt: 'inr', total: true }
];

export const BR27_SCHEMA = [
  { k: 'cnNo', label: 'Credit Note No', fmt: 'mono' },
  { k: 'cnDate', label: 'CN Date' },
  { k: 'custName', label: 'Customer', fmt: 'custcell27' },
  { k: 'subType', label: 'Subscriber Type', fmt: 'subtype' },
  { k: 'svcInv', label: 'Service Invoice', fmt: 'mono' },
  { k: 'svcStart', label: 'Svc Start' },
  { k: 'svcEnd', label: 'Svc End' },
  { k: 'numLoc', label: 'Locs', num: true },
  { k: 'amount', label: 'Amount', num: true, fmt: 'inr' },
  { k: 'gst', label: 'GST', num: true, fmt: 'inr' },
  { k: 'cnValue', label: 'CN Value', num: true, fmt: 'inr', total: true }
];

export const BR11_DATA = [
  {
    sl: 1,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFONCE11/24/0001',
    invDate: '02-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'Future Connect BroadBand Pvt. Ltd',
    gstin: '32AAECF5277D1ZV',
    state: 'Kerala',
    custType: 'Private',
    incomeType: 'OTC',
    svcStart: '',
    svcEnd: '',
    taxable: 470000.0,
    cgst: 42300.0,
    sgst: 42300.0,
    igst: 0.0,
    totGst: 84600.0,
    invVal: 554600.0,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 2,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFONCE11/24/0002',
    invDate: '07-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'Directorate of NCC (K&L)',
    gstin: '',
    state: 'Kerala',
    custType: 'Government',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 31497.0,
    cgst: 2834.73,
    sgst: 2834.73,
    igst: 0.0,
    totGst: 5669.46,
    invVal: 37166.46,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 3,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'ISD',
    invNo: 'KFONCE11/24/0003',
    invDate: '12-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'KADCO',
    gstin: '32AACCK2253Q1ZF',
    state: 'Kerala',
    custType: 'Government',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 17499.0,
    cgst: 1574.91,
    sgst: 1574.91,
    igst: 0.0,
    totGst: 3149.82,
    invVal: 20648.82,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 4,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFONCE11/24/0004',
    invDate: '12-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'KSIDC Thiruvananthapuram',
    gstin: '32AAACK9434D1ZV',
    state: 'Kerala',
    custType: 'Government',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 126027.4,
    cgst: 11342.47,
    sgst: 11342.47,
    igst: 0.0,
    totGst: 22684.93,
    invVal: 148712.33,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 5,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFONCE11/24/0005',
    invDate: '13-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'Directorate of Technical Education',
    gstin: '',
    state: 'Kerala',
    custType: 'Government',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 98195.0,
    cgst: 8837.55,
    sgst: 8837.55,
    igst: 0.0,
    totGst: 17675.1,
    invVal: 115870.1,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 6,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFONCE11/24/0006',
    invDate: '13-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'National Health Mission- Arogya Keralam',
    gstin: '',
    state: 'Kerala',
    custType: 'Government',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 144941.89,
    cgst: 13044.77,
    sgst: 13044.77,
    igst: 0.0,
    totGst: 26089.54,
    invVal: 171031.43,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 7,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFONCE11/24/0007',
    invDate: '13-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'Mar Gregorios College of Law',
    gstin: '',
    state: 'Kerala',
    custType: 'Private',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 2016.19,
    cgst: 181.46,
    sgst: 181.46,
    igst: 0.0,
    totGst: 362.91,
    invVal: 2379.1,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 8,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFONCE11/24/0008',
    invDate: '13-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'Powergrid Teleservices Limited',
    gstin: '32AAMCP4886G1Z2',
    state: 'Kerala',
    custType: 'Private',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 136703.18,
    cgst: 12303.29,
    sgst: 12303.29,
    igst: 0.0,
    totGst: 24606.57,
    invVal: 161309.75,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 9,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Composition',
    invNo: 'KFONCE11/24/0009',
    invDate: '13-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'DC School of Management and Technology, Vagamon',
    gstin: '32AABFD5289P2Z0',
    state: 'Kerala',
    custType: 'Private',
    incomeType: 'Static IP',
    svcStart: '',
    svcEnd: '',
    taxable: 8988.89,
    cgst: 809.0,
    sgst: 809.0,
    igst: 0.0,
    totGst: 1618.0,
    invVal: 10606.89,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 10,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFONCE11/24/0010',
    invDate: '16-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'State Agricultural Management And Extension Training Institute (SAMETI)',
    gstin: '',
    state: 'Kerala',
    custType: 'Private',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 24383.36,
    cgst: 2194.5,
    sgst: 2194.5,
    igst: 0.0,
    totGst: 4389.0,
    invVal: 28772.36,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 11,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFONCE11/24/0011',
    invDate: '18-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'Kollam Co operative Spinning Mills Ltd',
    gstin: '32AACAT7732K1ZC',
    state: 'Kerala',
    custType: 'Government',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 13438.0,
    cgst: 1209.42,
    sgst: 1209.42,
    igst: 0.0,
    totGst: 2418.84,
    invVal: 15856.84,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 12,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFONCE11/24/0012',
    invDate: '19-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'NIMS Medicity',
    gstin: '32AAATN1161B1ZD',
    state: 'Kerala',
    custType: 'Private',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 94520.55,
    cgst: 8506.85,
    sgst: 8506.85,
    igst: 0.0,
    totGst: 17013.7,
    invVal: 111534.25,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 13,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFONCE11/24/0013',
    invDate: '19-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'KIMS HEALTH MEDICAL CENTRE',
    gstin: '32AABCT2300C1ZC',
    state: 'Kerala',
    custType: 'Private',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 135616.44,
    cgst: 12205.48,
    sgst: 12205.48,
    igst: 0.0,
    totGst: 24410.96,
    invVal: 160027.4,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 14,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFONCE11/24/0014',
    invDate: '19-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'Malabar Cancer Centre Kannur',
    gstin: '32AAATM4095K1ZG',
    state: 'Kerala',
    custType: 'Government',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 55452.05,
    cgst: 4990.68,
    sgst: 4990.68,
    igst: 0.0,
    totGst: 9981.37,
    invVal: 65433.42,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 15,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFONCE11/24/0015',
    invDate: '19-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'Abad Green Forest',
    gstin: '32AACCA2659L4ZM',
    state: 'Kerala',
    custType: 'Private',
    incomeType: 'Static IP',
    svcStart: '',
    svcEnd: '',
    taxable: 11027.28,
    cgst: 992.45,
    sgst: 992.45,
    igst: 0.0,
    totGst: 1984.91,
    invVal: 13012.19,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 16,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFONCE11/24/0016',
    invDate: '19-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'Directorate for General Education',
    gstin: '',
    state: 'Kerala',
    custType: 'Government',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 71910.0,
    cgst: 6471.9,
    sgst: 6471.9,
    igst: 0.0,
    totGst: 12943.8,
    invVal: 84853.8,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 17,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFONCE11/24/0017',
    invDate: '19-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'Directorate of Economics & Statistics',
    gstin: '',
    state: 'Kerala',
    custType: 'Government',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 138986.0,
    cgst: 12508.74,
    sgst: 12508.74,
    igst: 0.0,
    totGst: 25017.48,
    invVal: 164003.48,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 18,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFONCE11/24/0018',
    invDate: '22-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'Periyar Tiger Reserve East Division Thekkady',
    gstin: '',
    state: 'Kerala',
    custType: 'Government',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 375000.0,
    cgst: 33750.0,
    sgst: 33750.0,
    igst: 0.0,
    totGst: 67500.0,
    invVal: 442500.0,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 19,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFONCE11/24/0019',
    invDate: '27-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'Mountain Pass Residency',
    gstin: '32ALJPV1222B1ZN',
    state: 'Kerala',
    custType: 'Private',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 12671.12,
    cgst: 1140.4,
    sgst: 1140.4,
    igst: 0.0,
    totGst: 2280.8,
    invVal: 14951.93,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 20,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFONCE11/24/0020',
    invDate: '28-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'Kerala Financial Corporation (KFC)',
    gstin: '32AABCK1316M1ZU',
    state: 'Kerala',
    custType: 'Government',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 63013.7,
    cgst: 5671.23,
    sgst: 5671.23,
    igst: 0.0,
    totGst: 11342.47,
    invVal: 74356.16,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 21,
    revType: 'Enterprise',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFONCE11/24/0021',
    invDate: '30-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: "Small Farmers' Agribusiness Consortium Kerala (SFAC)",
    gstin: '',
    state: 'Kerala',
    custType: 'Private',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 9602.64,
    cgst: 864.24,
    sgst: 864.24,
    igst: 0.0,
    totGst: 1728.48,
    invVal: 11331.12,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 22,
    revType: 'Special Events',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFONSE11/24/0001',
    invDate: '30-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: 'Kerala Development and Innovation Strategic Council (KDISC)',
    gstin: '',
    state: 'Kerala',
    custType: 'Government',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 70991.0,
    cgst: 6389.19,
    sgst: 6389.19,
    igst: 0.0,
    totGst: 12778.38,
    invVal: 83769.38,
    renewMode: '',
    partnerId: '',
    partnerName: ''
  },
  {
    sl: 23,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/000638',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAGFF1936J1ZK',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 449.0,
    cgst: 40.41,
    sgst: 40.41,
    igst: 0.0,
    totGst: 80.82,
    invVal: 529.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 24,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/000011',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AMJPA4734A1ZT',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 599.0,
    cgst: 53.91,
    sgst: 53.91,
    igst: 0.0,
    totGst: 107.82,
    invVal: 706.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 25,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/000713',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAFAN4170N1ZF',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 449.0,
    cgst: 40.41,
    sgst: 40.41,
    igst: 0.0,
    totGst: 80.82,
    invVal: 529.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 26,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/001458',
    invDate: '02-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32EDPPG7256G1ZD',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 299.0,
    cgst: 26.91,
    sgst: 26.91,
    igst: 0.0,
    totGst: 53.82,
    invVal: 352.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 27,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/001497',
    invDate: '02-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32GHQPK5562J1ZU',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 28,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/002935',
    invDate: '04-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AARCM9133E1ZE',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 999.0,
    cgst: 89.91,
    sgst: 89.91,
    igst: 0.0,
    totGst: 179.82,
    invVal: 1178.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 29,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/002954',
    invDate: '04-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32ACBFA3562E1ZZ',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 499.0,
    cgst: 44.91,
    sgst: 44.91,
    igst: 0.0,
    totGst: 89.82,
    invVal: 588.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 30,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/004163',
    invDate: '05-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32BRNPK0158C1Z6',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 299.0,
    cgst: 26.91,
    sgst: 26.91,
    igst: 0.0,
    totGst: 53.82,
    invVal: 352.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 31,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/004548',
    invDate: '05-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32ABZFM5740P1ZE',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 999.0,
    cgst: 89.91,
    sgst: 89.91,
    igst: 0.0,
    totGst: 179.82,
    invVal: 1178.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 32,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/004861',
    invDate: '05-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AALCP1846M1Z4',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 399.0,
    cgst: 35.91,
    sgst: 35.91,
    igst: 0.0,
    totGst: 71.82,
    invVal: 470.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 33,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/005792',
    invDate: '06-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AADCM0074C1Z6',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 799.0,
    cgst: 71.91,
    sgst: 71.91,
    igst: 0.0,
    totGst: 143.82,
    invVal: 942.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 34,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/005473',
    invDate: '06-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32BADPV1019A1ZE',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 299.0,
    cgst: 26.91,
    sgst: 26.91,
    igst: 0.0,
    totGst: 53.82,
    invVal: 352.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 35,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/005282',
    invDate: '06-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AACCE8200D1ZD',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 599.0,
    cgst: 53.91,
    sgst: 53.91,
    igst: 0.0,
    totGst: 107.82,
    invVal: 706.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 36,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/005280',
    invDate: '06-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAMFC2475K1ZB',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 599.0,
    cgst: 53.91,
    sgst: 53.91,
    igst: 0.0,
    totGst: 107.82,
    invVal: 706.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 37,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/004978',
    invDate: '06-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32ABPFS7161N1ZJ',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 599.0,
    cgst: 53.91,
    sgst: 53.91,
    igst: 0.0,
    totGst: 107.82,
    invVal: 706.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 38,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/009542',
    invDate: '14-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32DIZPS9217M2Z6',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 1249.0,
    cgst: 112.41,
    sgst: 112.41,
    igst: 0.0,
    totGst: 224.82,
    invVal: 1473.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 39,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/009569',
    invDate: '14-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AHLPT6183H1ZY',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 2994.0,
    cgst: 269.46,
    sgst: 269.46,
    igst: 0.0,
    totGst: 538.92,
    invVal: 3532.92,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 40,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/010218',
    invDate: '15-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32IYVPS0687E1ZR',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 499.0,
    cgst: 44.91,
    sgst: 44.91,
    igst: 0.0,
    totGst: 89.82,
    invVal: 588.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 41,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/010232',
    invDate: '15-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AABFE3237A1ZB',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 799.0,
    cgst: 71.91,
    sgst: 71.91,
    igst: 0.0,
    totGst: 143.82,
    invVal: 942.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 42,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/010293',
    invDate: '15-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAZCS1371E1Z8',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 599.0,
    cgst: 53.91,
    sgst: 53.91,
    igst: 0.0,
    totGst: 107.82,
    invVal: 706.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 43,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/010493',
    invDate: '15-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAQFD1589H1Z8',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 799.0,
    cgst: 71.91,
    sgst: 71.91,
    igst: 0.0,
    totGst: 143.82,
    invVal: 942.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 44,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/011282',
    invDate: '16-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAVFN4004G1ZF',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 499.0,
    cgst: 44.91,
    sgst: 44.91,
    igst: 0.0,
    totGst: 89.82,
    invVal: 588.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 45,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/011609',
    invDate: '16-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32BEBPB1311R1ZY',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 299.0,
    cgst: 26.91,
    sgst: 26.91,
    igst: 0.0,
    totGst: 53.82,
    invVal: 352.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 46,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/012145',
    invDate: '17-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32ABDCS2623Q1Z6',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 499.0,
    cgst: 44.91,
    sgst: 44.91,
    igst: 0.0,
    totGst: 89.82,
    invVal: 588.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 47,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/013207',
    invDate: '18-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAIFE4837D1ZQ',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 499.0,
    cgst: 44.91,
    sgst: 44.91,
    igst: 0.0,
    totGst: 89.82,
    invVal: 588.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 48,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/014498',
    invDate: '19-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32DYZPM3191N1ZI',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 499.0,
    cgst: 44.91,
    sgst: 44.91,
    igst: 0.0,
    totGst: 89.82,
    invVal: 588.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 49,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/014097',
    invDate: '19-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAKCT3720D1ZR',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 5988.0,
    cgst: 538.92,
    sgst: 538.92,
    igst: 0.0,
    totGst: 1077.84,
    invVal: 7065.84,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 50,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/014467',
    invDate: '19-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAMFG0510B1ZA',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 449.0,
    cgst: 40.41,
    sgst: 40.41,
    igst: 0.0,
    totGst: 80.82,
    invVal: 529.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 51,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/015229',
    invDate: '20-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAQFD1589H1Z8',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 799.0,
    cgst: 71.91,
    sgst: 71.91,
    igst: 0.0,
    totGst: 143.82,
    invVal: 942.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 52,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/015391',
    invDate: '20-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32BAQPS1724Q1Z3',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 2394.0,
    cgst: 215.46,
    sgst: 215.46,
    igst: 0.0,
    totGst: 430.92,
    invVal: 2824.92,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 53,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/015484',
    invDate: '20-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAUCS7444M1ZM',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 1249.0,
    cgst: 112.41,
    sgst: 112.41,
    igst: 0.0,
    totGst: 224.82,
    invVal: 1473.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 54,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/015754',
    invDate: '21-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32BLWPV8355D1ZH',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 599.0,
    cgst: 53.91,
    sgst: 53.91,
    igst: 0.0,
    totGst: 107.82,
    invVal: 706.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 55,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/016225',
    invDate: '21-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAPFN3430Q1ZW',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 1794.0,
    cgst: 161.46,
    sgst: 161.46,
    igst: 0.0,
    totGst: 322.92,
    invVal: 2116.92,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 56,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/016503',
    invDate: '22-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AMAPC0258J1ZM',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 999.0,
    cgst: 89.91,
    sgst: 89.91,
    igst: 0.0,
    totGst: 179.82,
    invVal: 1178.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 57,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/018234',
    invDate: '24-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAGFF3556L1ZC',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 58,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/019832',
    invDate: '26-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAECB1042N1ZZ',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 399.0,
    cgst: 35.91,
    sgst: 35.91,
    igst: 0.0,
    totGst: 71.82,
    invVal: 470.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 59,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/020765',
    invDate: '26-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAQFD5184J1Z4',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 897.0,
    cgst: 80.73,
    sgst: 80.73,
    igst: 0.0,
    totGst: 161.46,
    invVal: 1058.46,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 60,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/020743',
    invDate: '26-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAQFT4941F1Z2',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 1249.0,
    cgst: 112.41,
    sgst: 112.41,
    igst: 0.0,
    totGst: 224.82,
    invVal: 1473.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 61,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/020678',
    invDate: '26-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAKAP5413H1ZP',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 599.0,
    cgst: 53.91,
    sgst: 53.91,
    igst: 0.0,
    totGst: 107.82,
    invVal: 706.82,
    renewMode: 'IKM',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 62,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/019873',
    invDate: '26-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32ABFCS8873G1Z1',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 399.0,
    cgst: 35.91,
    sgst: 35.91,
    igst: 0.0,
    totGst: 71.82,
    invVal: 470.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 63,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/023023',
    invDate: '29-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAJPE5051C1ZE',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 599.0,
    cgst: 53.91,
    sgst: 53.91,
    igst: 0.0,
    totGst: 107.82,
    invVal: 706.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 64,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/023540',
    invDate: '29-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAQFT4941F1Z2',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 1249.0,
    cgst: 112.41,
    sgst: 112.41,
    igst: 0.0,
    totGst: 224.82,
    invVal: 1473.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 65,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/023467',
    invDate: '29-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32ABCFR2191L1Z5',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 499.0,
    cgst: 44.91,
    sgst: 44.91,
    igst: 0.0,
    totGst: 89.82,
    invVal: 588.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 66,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/023421',
    invDate: '29-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAECR7294L1ZX',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 67,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/023324',
    invDate: '29-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAYCA8253A1ZO',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 2394.0,
    cgst: 215.46,
    sgst: 215.46,
    igst: 0.0,
    totGst: 430.92,
    invVal: 2824.92,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 68,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/023243',
    invDate: '29-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32CEFPV1521J1ZL',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 299.0,
    cgst: 26.91,
    sgst: 26.91,
    igst: 0.0,
    totGst: 53.82,
    invVal: 352.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 69,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/023107',
    invDate: '29-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32ABCFA8441J1ZL',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 2094.0,
    cgst: 188.46,
    sgst: 188.46,
    igst: 0.0,
    totGst: 376.92,
    invVal: 2470.92,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 70,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/023106',
    invDate: '29-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AADCH1395K1ZK',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 999.0,
    cgst: 89.91,
    sgst: 89.91,
    igst: 0.0,
    totGst: 179.82,
    invVal: 1178.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 71,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/023024',
    invDate: '29-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAKCM0094M1ZA',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 799.0,
    cgst: 71.91,
    sgst: 71.91,
    igst: 0.0,
    totGst: 143.82,
    invVal: 942.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 72,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/023973',
    invDate: '30-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AAJCS2258L1Z5',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 2997.0,
    cgst: 269.73,
    sgst: 269.73,
    igst: 0.0,
    totGst: 539.46,
    invVal: 3536.46,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 73,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/024051',
    invDate: '30-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32ARJPK0383Q1ZF',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 599.0,
    cgst: 53.91,
    sgst: 53.91,
    igst: 0.0,
    totGst: 107.82,
    invVal: 706.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 74,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'SEZ',
    invNo: 'KFON11/24/024293',
    invDate: '30-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32APTPB6969B1ZT',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 2094.0,
    cgst: 188.46,
    sgst: 188.46,
    igst: 0.0,
    totGst: 376.92,
    invVal: 2470.92,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 75,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/024407',
    invDate: '30-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AADCL2832M1ZK',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 999.0,
    cgst: 89.91,
    sgst: 89.91,
    igst: 0.0,
    totGst: 179.82,
    invVal: 1178.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 76,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/024508',
    invDate: '30-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32AACFK6606L1ZE',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 799.0,
    cgst: 71.91,
    sgst: 71.91,
    igst: 0.0,
    totGst: 143.82,
    invVal: 942.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 77,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2B',
    taxPayer: 'Regular',
    invNo: 'KFON11/24/024536',
    invDate: '30-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '32ABFCS8873G1Z1',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 78,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000001',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 79,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000004',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 80,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000005',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'LNP',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 81,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000006',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 82,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000008',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 83,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000010',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 84,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000013',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 85,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000014',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 86,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000016',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 87,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000017',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 88,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000019',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 89,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000020',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 90,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000021',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 91,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000022',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 92,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000023',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 93,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000024',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 94,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000025',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 95,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000028',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 96,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000029',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 97,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000030',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 98,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000031',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 99,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000032',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 100,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000033',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 101,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000034',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 102,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000036',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 103,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000038',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 104,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000040',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 105,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000042',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 106,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000043',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 107,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000044',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 108,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000045',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 109,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000046',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 110,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000048',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 111,
    revType: 'Retail',
    docType: 'INV',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000050',
    invDate: '01-11-2024',
    cnNo: '',
    cnDate: '',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: 349.0,
    cgst: 31.41,
    sgst: 31.41,
    igst: 0.0,
    totGst: 62.82,
    invVal: 411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 112,
    revType: 'Retail',
    docType: 'CN',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000046',
    invDate: '01-11-2024',
    cnNo: 'KFONCN11/24/000050',
    cnDate: '01-11-2024',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: -349.0,
    cgst: -31.41,
    sgst: -31.41,
    igst: 0.0,
    totGst: -62.82,
    invVal: -411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 113,
    revType: 'Retail',
    docType: 'CN',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000048',
    invDate: '01-11-2024',
    cnNo: 'KFONCN11/24/000051',
    cnDate: '01-11-2024',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: -349.0,
    cgst: -31.41,
    sgst: -31.41,
    igst: 0.0,
    totGst: -62.82,
    invVal: -411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  },
  {
    sl: 114,
    revType: 'Retail',
    docType: 'CN',
    gstCat: 'B2C',
    taxPayer: 'Unregistered',
    invNo: 'KFON11/24/000050',
    invDate: '01-11-2024',
    cnNo: 'KFONCN11/24/000052',
    cnDate: '01-11-2024',
    custId: '',
    custName: '',
    gstin: '',
    state: 'Kerala',
    custType: 'Home Subscriber',
    incomeType: 'BANDWIDTH',
    svcStart: '',
    svcEnd: '',
    taxable: -349.0,
    cgst: -31.41,
    sgst: -31.41,
    igst: 0.0,
    totGst: -62.82,
    invVal: -411.82,
    renewMode: 'HDFC',
    partnerId: 12345,
    partnerName: 'ABC Limited'
  }
];

export const BR27_DATA = [
  {
    subType: 'Corporate - Government',
    custName: 'KERALA STATE HOUSING BOARD',
    svcInv: 'KFONCE06/25/0030',
    svcStart: '23-06-2025',
    svcEnd: '22-06-2026',
    numLoc: 1,
    amount: 3685.96,
    gst: 663.47,
    cnValue: 4349.43,
    cnDate: '15-05-2026',
    cnNo: 'KFON/CN/26/00145'
  },
  {
    subType: 'Corporate - Government',
    custName: 'KERALA STATE HOUSING BOARD',
    svcInv: 'KFONCE11/25/0070',
    svcStart: '25-11-2025',
    svcEnd: '24-11-2026',
    numLoc: 3,
    amount: 25142.42,
    gst: 4525.64,
    cnValue: 29668.06,
    cnDate: '15-05-2026',
    cnNo: 'KFON/CN/26/00144'
  },
  {
    subType: 'Corporate - Government',
    custName: 'KERALA STATE HOUSING BOARD',
    svcInv: 'KFONCE02/26/0018',
    svcStart: '04-02-2026',
    svcEnd: '03-02-2027',
    numLoc: 6,
    amount: 105799.89,
    gst: 19043.98,
    cnValue: 124843.87,
    cnDate: '15-05-2026',
    cnNo: 'KFON/CN/26/00143'
  },
  {
    subType: 'Corporate - Government',
    custName: 'KERALA STATE HOUSING BOARD',
    svcInv: 'KFONCE04/26/0078',
    svcStart: '08-04-2026',
    svcEnd: '07-04-2027',
    numLoc: 1,
    amount: 10938.0,
    gst: 1968.84,
    cnValue: 12906.84,
    cnDate: '15-05-2026',
    cnNo: 'KFON/CN/26/00142'
  },
  {
    subType: 'Corporate - Government',
    custName: 'KERALA STATE HOUSING BOARD',
    svcInv: 'KFONCE04/25/0062',
    svcStart: '08-04-2025',
    svcEnd: '07-04-2026',
    numLoc: 1,
    amount: 1408.45,
    gst: 253.52,
    cnValue: 1661.97,
    cnDate: '15-05-2026',
    cnNo: 'KFON/CN/26/00141'
  },
  {
    subType: 'Corporate - Government',
    custName: 'KERALA STATE HOUSING BOARD',
    svcInv: 'KFONCE01/26/0029',
    svcStart: '03-01-2026',
    svcEnd: '02-01-2027',
    numLoc: 2,
    amount: 110437.66,
    gst: 19878.78,
    cnValue: 130316.44,
    cnDate: '15-05-2026',
    cnNo: 'KFON/CN/26/00140'
  },
  {
    subType: 'Corporate - Private',
    custName: 'DC School of Management & Technology',
    svcInv: 'KFONCE04/26/0003',
    svcStart: '01-04-2026',
    svcEnd: '31-03-2027',
    numLoc: 1,
    amount: 69999.0,
    gst: 12599.82,
    cnValue: 82598.82,
    cnDate: '15-05-2026',
    cnNo: 'KFON/CN/26/00139'
  },
  {
    subType: 'Corporate - Government',
    custName: 'Deputy Director of Fisheries',
    svcInv: 'KFONCE12/25/0051',
    svcStart: '18-12-2025',
    svcEnd: '15-06-2026',
    numLoc: 1,
    amount: 20784.94,
    gst: 3741.29,
    cnValue: 24526.23,
    cnDate: '15-05-2026',
    cnNo: 'KFON/CN/26/00138'
  },
  {
    subType: 'Corporate-DarkFiber',
    custName: 'KERALA VISION BROAD BAND LIMITED',
    svcInv: 'KFONDF04/26/0001',
    svcStart: '01-04-2026',
    svcEnd: '30-06-2026',
    numLoc: 1,
    amount: 117949.93,
    gst: 21230.99,
    cnValue: 139180.92,
    cnDate: '13-05-2026',
    cnNo: 'KFON/CN/26/00137'
  }
];

export function compute() {
  const t = {};

  const invs = BR11_DATA.filter((r) => r.docType === 'INV');
  const cns = BR11_DATA.filter((r) => r.docType === 'CN');

  t.totalInv = {
    count: invs.length,
    taxable: invs.reduce((s, r) => s + r.taxable, 0),
    total: invs.reduce((s, r) => s + r.totGst, 0),
    gst: invs.reduce((s, r) => s + r.totGst, 0),
    val: invs.reduce((s, r) => s + r.invVal, 0)
  };
  t.cnInline = {
    count: cns.length,
    taxable: cns.reduce((s, r) => s + r.taxable, 0),
    total: invs.reduce((s, r) => s + r.totGst, 0),
    gst: cns.reduce((s, r) => s + r.totGst, 0),
    val: cns.reduce((s, r) => s + r.invVal, 0)
  };

  t.br27 = {
    count: BR27_DATA.length,
    amount: BR27_DATA.reduce((s, r) => s + r.amount, 0),
    total: invs.reduce((s, r) => s + r.totGst, 0),
    gst: BR27_DATA.reduce((s, r) => s + r.gst, 0),
    val: BR27_DATA.reduce((s, r) => s + r.cnValue, 0)
  };

  t.gross = t.totalInv.val;
  t.cnTotal = Math.abs(t.cnInline.val) + t.br27.val;
  t.net = t.gross - t.cnTotal;

  t.byRevType = {};
  invs.forEach((r) => {
    const k = r.revType || 'Other';
    if (!t.byRevType[k]) t.byRevType[k] = { count: 0, taxable: 0, gst: 0, val: 0 };
    t.byRevType[k].count++;
    t.byRevType[k].taxable += r.taxable;
    t.byRevType[k].gst += r.totGst;
    t.byRevType[k].val += r.invVal;
  });

  t.byCustType = {};
  invs.forEach((r) => {
    const k = r.custType || 'Other';
    if (!t.byCustType[k]) t.byCustType[k] = { count: 0, taxable: 0, gst: 0, val: 0 };
    t.byCustType[k].count++;
    t.byCustType[k].taxable += r.taxable;
    t.byCustType[k].gst += r.totGst;
    t.byCustType[k].val += r.invVal;
  });

  t.byGstCat = {};
  invs.forEach((r) => {
    const k = r.gstCat || 'Other';
    if (!t.byGstCat[k]) t.byGstCat[k] = { count: 0, val: 0 };
    t.byGstCat[k].count++;
    t.byGstCat[k].val += r.invVal;
  });

  t.byTaxPayer = {};
  invs.forEach((r) => {
    const k = r.taxPayer || 'Other';
    if (!t.byTaxPayer[k]) t.byTaxPayer[k] = { count: 0, val: 0 };
    t.byTaxPayer[k].count++;
    t.byTaxPayer[k].val += r.invVal;
  });

  const custMap = {};
  invs.forEach((r) => {
    const name = r.custName || (r.gstin ? `GSTIN ${r.gstin}` : 'Retail Subscriber');
    if (!custMap[name]) custMap[name] = { name, custType: r.custType, count: 0, val: 0, taxable: 0 };
    custMap[name].count++;
    custMap[name].val += r.invVal;
    custMap[name].taxable += r.taxable;
  });
  t.topCustomers = Object.values(custMap).sort((a, b) => b.val - a.val);

  const monthMap = {};
  invs.forEach((r) => {
    if (!r.invDate) return;
    const parts = r.invDate.split('-');
    if (parts.length < 3) return;
    const key = parts[1] + '/' + parts[2].slice(-2);
    if (!monthMap[key]) monthMap[key] = { key, count: 0, val: 0 };
    monthMap[key].count++;
    monthMap[key].val += r.invVal;
  });
  t.monthly = Object.values(monthMap).sort((a, b) => {
    const [am, ay] = a.key.split('/');
    const [bm, by] = b.key.split('/');
    return (ay + am).localeCompare(by + bm);
  });

  t.erosionPct = t.gross > 0 ? (t.cnTotal / t.gross) * 100 : 0;

  return t;
}

export const T = compute();

// C, fmtINR, fmtINRFull, fmtINRShort, escapeHtml, shortTitle are re-exported from the top of this file.

export const DETAIL_FIELDS = {
  REVENUE_BR11: [
    ['Invoice No', 'invNo'],
    ['Invoice Date', 'invDate'],
    ['Document Type', 'docType'],
    ['Revenue Type', 'revType'],
    ['Customer Name', 'custName'],
    ['Customer ID', 'custId'],
    ['Customer Segment', 'custType'],
    ['GSTIN', 'gstin'],
    ['GST Category', 'gstCat'],
    ['Tax Payer Type', 'taxPayer'],
    ['State', 'state'],
    ['Income Type', 'incomeType'],
    ['Renewal Mode', 'renewMode'],
    ['Partner Name', 'partnerName'],
    ['Credit Note No', 'cnNo'],
    ['Credit Note Date', 'cnDate']
  ],
  REVENUE_BR27: [
    ['Credit Note No', 'cnNo'],
    ['Credit Note Date', 'cnDate'],
    ['Customer', 'custName'],
    ['Subscriber Type', 'subType'],
    ['Service Invoice', 'svcInv'],
    ['Service Start', 'svcStart'],
    ['Service End', 'svcEnd'],
    ['No. of Locations', 'numLoc']
  ]
};

export const BREAKDOWN_FIELDS = {
  REVENUE_BR11: [
    ['Taxable Amount', 'taxable'],
    ['CGST', 'cgst'],
    ['SGST', 'sgst'],
    ['IGST', 'igst'],
    ['Total GST', 'totGst'],
    ['Invoice Value', 'invVal', true]
  ],
  REVENUE_BR27: [
    ['Amount (excl. GST)', 'amount'],
    ['GST Reversed', 'gst'],
    ['Credit Note Value', 'cnValue', true]
  ]
};

/**
 * Convenience maps used by RevenueReports.jsx to look up data / schema by report code.
 */
export const DATA = {
  REVENUE_BR11: BR11_DATA,
  REVENUE_BR27: BR27_DATA
};

export const SCHEMAS = {
  REVENUE_BR11: BR11_SCHEMA,
  REVENUE_BR27: BR27_SCHEMA
};
