// fetchEnquiryList
import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

export const API_ACTION_TYPES = {
  FETCH_ENQUIRY_LIST: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_LIST`,
  SUBMIT_BASIC_DETAILS: `${STATE_REDUCER_KEY}/SUBMIT_BASIC_DETAILS`,
  UPDATE_BASIC_DETAILS: `${STATE_REDUCER_KEY}/UPDATE_BASIC_DETAILS`,
  UPDATE_SUBSCRIPTION_DETAILS: `${STATE_REDUCER_KEY}/UPDATE_SUBSCRIPTION_DETAILS`,
  UPDATE_DEVICE_DETAILS: `${STATE_REDUCER_KEY}/UPDATE_DEVICE_DETAILS`,
  UPDATE_GST_INFORMATION: `${STATE_REDUCER_KEY}/UPDATE_GST_INFORMATION`,
  UPDATE_ADDRESS_DETAILS: `${STATE_REDUCER_KEY}/UPDATE_ADDRESS_DETAILS`,
  UPDATE_SUPPORTING_DOCUMENTS: `${STATE_REDUCER_KEY}/UPDATE_SUPPORTING_DOCUMENTS`,
  FETCH_DEVICE_PROVIDER: `${STATE_REDUCER_KEY}/FETCH_DEVICE_PROVIDER`,
  FETCH_ONT_DEVICES: `${STATE_REDUCER_KEY}/FETCH_ONT_DEVICES`,
  FETCH_DEVICE_TYPE: `${STATE_REDUCER_KEY}/FETCH_DEVICE_TYPE`,
  FETCH_OLT_TYPE: `${STATE_REDUCER_KEY}/FETCH_OLT_TYPE`,
  FETCH_OLT_DEVICE_LIST: `${STATE_REDUCER_KEY}/FETCH_OLT_DEVICE_LIST`,
  FETCH_AVAILABLE_PON_PORTS: `${STATE_REDUCER_KEY}/FETCH_AVAILABLE_PON_PORTS`,
  FETCH_PLAN_TYPE: `${STATE_REDUCER_KEY}/FETCH_PLAN_TYPE`,
  FETCH_PACKAGE_TYPE: `${STATE_REDUCER_KEY}/FETCH_PACKAGE_TYPE`,
  FETCH_PACKAGE_LIST: `${STATE_REDUCER_KEY}/FETCH_PACKAGE_LIST`,
  FETCH_DISTRIBUTOR_LIST: `${STATE_REDUCER_KEY}/FETCH_DISTRIBUTOR_LIST`,
  FETCH_PARTNER_LIST: `${STATE_REDUCER_KEY}/FETCH_PARTNER_LIST`,
  FETCH_DEVICE_DETAILS_BY_ID: `${STATE_REDUCER_KEY}/FETCH_DEVICE_DETAILS_BY_ID`,
  FETCH_ENQUIRY_DASHBOARD: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_DASHBOARD`,
  FETCH_ENQUIRY_CARD_DATA: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_CARD_DATA`,
  FETCH_ENQUIRY_SUMMARY: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_SUMMARY`,
  CREATE_CUSTOMER_ENQUIRY: `${STATE_REDUCER_KEY}/CREATE_CUSTOMER_ENQUIRY`,
  DOWNLOAD_ENQUIRY_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_ENQUIRY_CSV`,
  ASSIGN_ENQUIRY_TO_FE: `${STATE_REDUCER_KEY}/ASSIGN_ENQUIRY_TO_FE`,
  ASSIGN_ENQUIRY_TO_LNP: `${STATE_REDUCER_KEY}/ASSIGN_ENQUIRY_TO_LNP`,
  SAVE_MEETING: `${STATE_REDUCER_KEY}/SAVE_MEETING`,
  FETCH_MEETING_LIST: `${STATE_REDUCER_KEY}/FETCH_MEETING_LIST`,
  FETCH_SUBSCRIBER_LIST: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_LIST`,
  SUBMIT_DISPOSITION: `${STATE_REDUCER_KEY}/SUBMIT_DISPOSITION`,
  FETCH_FE_LIST: `${STATE_REDUCER_KEY}/FETCH_FE_LIST`,
  FETCH_LNP_LIST: `${STATE_REDUCER_KEY}/FETCH_LNP_LIST`,
  FETCH_DISPOSITION_HISTORY_LIST: `${STATE_REDUCER_KEY}/FETCH_DISPOSITION_HISTORY_LIST`,
  FETCH_DISPOSITION_LIST: `${STATE_REDUCER_KEY}/FETCH_DISPOSITION_LIST`,
  FETCH_REASON_LIST: `${STATE_REDUCER_KEY}/FETCH_REASON_LIST`,
  FETCH_ENQUIRY_STATUSES: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_STATUSES`,
  FETCH_EWS_ENQUIRY_LIST: `${STATE_REDUCER_KEY}/FETCH_EWS_ENQUIRY_LIST`,
  FETCH_SUBSCRIBER_BY_ENQUIRY_ID: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_BY_ENQUIRY_ID`,
  FETCH_RESIDENCE_PROOF_TYPES: `${STATE_REDUCER_KEY}/FETCH_RESIDENCE_PROOF_TYPES`,
  FETCH_IDENTITY_PROOF_TYPES: `${STATE_REDUCER_KEY}/FETCH_IDENTITY_PROOF_TYPES`,
  FINALIZE_CAF: `${STATE_REDUCER_KEY}/FINALIZE_CAF`,
  UPLOAD_SINGLE_DOCUMENT: `${STATE_REDUCER_KEY}/UPLOAD_SINGLE_DOCUMENT`,
  FETCH_ONT_NEXT_POSITION: `${STATE_REDUCER_KEY}/FETCH_ONT_NEXT_POSITION`,
  UPDATE_EKYC_DETAILS: `${STATE_REDUCER_KEY}/UPDATE_EKYC_DETAILS`,
  SUBMIT_EKYC_DETAILS: `${STATE_REDUCER_KEY}/SUBMIT_EKYC_DETAILS`,
  VERIFY_SUBSCRIBER: `${STATE_REDUCER_KEY}/VERIFY_SUBSCRIBER`,
  ONBOARD_SUBSCRIBER: `${STATE_REDUCER_KEY}/ONBOARD_SUBSCRIBER`,
  CHECK_FEASIBILITY: `${STATE_REDUCER_KEY}/CHECK_FEASIBILITY`,
  FETCH_SUBSCRIBERS_PAGE: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBERS_PAGE`,
  FETCH_SUBSCRIBER_FORWARD_USERS: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_FORWARD_USERS`,
  ASSIGN_SUBSCRIBER_ENQUIRY: `${STATE_REDUCER_KEY}/ASSIGN_SUBSCRIBER_ENQUIRY`,
  FETCH_EWS_PACKAGES: `${STATE_REDUCER_KEY}/FETCH_EWS_PACKAGES`,
  GET_ONT_ACKNOWLEDGEMENT: `${STATE_REDUCER_KEY}/GET_ONT_ACKNOWLEDGEMENT`,
  VERIFY_ONT_ACKNOWLEDGEMENT: `${STATE_REDUCER_KEY}/VERIFY_ONT_ACKNOWLEDGEMENT`,
  FETCH_SUBSCRIBER_DETAIL: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_DETAIL`,
  FETCH_SUBSCRIBER_DATA_USAGE: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_DATA_USAGE`,
  FETCH_RADIUS_DETAILS: `${STATE_REDUCER_KEY}/FETCH_RADIUS_DETAILS`,
  UPDATE_SUBSCRIBER_DETAIL: `${STATE_REDUCER_KEY}/UPDATE_SUBSCRIBER_DETAIL`,
  SEND_MOBILE_CHANGE_OTP: `${STATE_REDUCER_KEY}/SEND_MOBILE_CHANGE_OTP`,
  VERIFY_MOBILE_CHANGE_OTP: `${STATE_REDUCER_KEY}/VERIFY_MOBILE_CHANGE_OTP`,
  RESET_SUBSCRIBER_PASSWORD: `${STATE_REDUCER_KEY}/RESET_SUBSCRIBER_PASSWORD`,
  CHANGE_USERNAME: `${STATE_REDUCER_KEY}/CHANGE_USERNAME`,
  DOWNLOAD_SUBSCRIBERS_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_SUBSCRIBERS_CSV`
};
export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchEnquiryList = createAction(API_ACTION_TYPES.FETCH_ENQUIRY_LIST);
export const submitBasicDetails = createAction(API_ACTION_TYPES.SUBMIT_BASIC_DETAILS);
export const updateBasicDetails = createAction(API_ACTION_TYPES.UPDATE_BASIC_DETAILS);
export const updateSubscriptionDetails = createAction(API_ACTION_TYPES.UPDATE_SUBSCRIPTION_DETAILS);
export const updateDeviceDetails = createAction(API_ACTION_TYPES.UPDATE_DEVICE_DETAILS);
export const updateGstInformation = createAction(API_ACTION_TYPES.UPDATE_GST_INFORMATION);
export const updateAddressDetails = createAction(API_ACTION_TYPES.UPDATE_ADDRESS_DETAILS);
export const updateSupportingDocuments = createAction(API_ACTION_TYPES.UPDATE_SUPPORTING_DOCUMENTS);
export const fetchDeviceProvider = createAction(API_ACTION_TYPES.FETCH_DEVICE_PROVIDER);
export const fetchOntDevices = createAction(API_ACTION_TYPES.FETCH_ONT_DEVICES);
export const fetchDeviceType = createAction(API_ACTION_TYPES.FETCH_DEVICE_TYPE);
export const fetchOltType = createAction(API_ACTION_TYPES.FETCH_OLT_TYPE);
export const fetchOltDeviceList = createAction(API_ACTION_TYPES.FETCH_OLT_DEVICE_LIST);
export const fetchAvailablePonPorts = createAction(API_ACTION_TYPES.FETCH_AVAILABLE_PON_PORTS);
export const fetchPlanType = createAction(API_ACTION_TYPES.FETCH_PLAN_TYPE);
export const fetchPackageType = createAction(API_ACTION_TYPES.FETCH_PACKAGE_TYPE);
export const fetchPackageList = createAction(API_ACTION_TYPES.FETCH_PACKAGE_LIST);
export const fetchDistributorList = createAction(API_ACTION_TYPES.FETCH_DISTRIBUTOR_LIST);
export const fetchPartnerList = createAction(API_ACTION_TYPES.FETCH_PARTNER_LIST);
export const fetchDeviceDetailsById = createAction(API_ACTION_TYPES.FETCH_DEVICE_DETAILS_BY_ID);
export const fetchEnquiryDashboard = createAction(API_ACTION_TYPES.FETCH_ENQUIRY_DASHBOARD);
export const fetchEnquiryCardData = createAction(API_ACTION_TYPES.FETCH_ENQUIRY_CARD_DATA);
export const fetchEnquirySummary = createAction(API_ACTION_TYPES.FETCH_ENQUIRY_SUMMARY);
export const createCustomerEnquiry = createAction(API_ACTION_TYPES.CREATE_CUSTOMER_ENQUIRY);
export const downloadEnquiryCSV = createAction(API_ACTION_TYPES.DOWNLOAD_ENQUIRY_CSV);
export const assignEnquiryToFE = createAction(API_ACTION_TYPES.ASSIGN_ENQUIRY_TO_FE);
export const assignEnquiryToLNP = createAction(API_ACTION_TYPES.ASSIGN_ENQUIRY_TO_LNP);
export const saveMeeting = createAction(API_ACTION_TYPES.SAVE_MEETING);
export const fetchMeetingList = createAction(API_ACTION_TYPES.FETCH_MEETING_LIST);
export const fetchSubscriberList = createAction(API_ACTION_TYPES.FETCH_SUBSCRIBER_LIST);
export const submitDisposition = createAction(API_ACTION_TYPES.SUBMIT_DISPOSITION);
export const fetchFEList = createAction(API_ACTION_TYPES.FETCH_FE_LIST);
export const fetchLNPList = createAction(API_ACTION_TYPES.FETCH_LNP_LIST);
export const fetchDispositionHistoryList = createAction(API_ACTION_TYPES.FETCH_DISPOSITION_HISTORY_LIST);
export const fetchDispositionList = createAction(API_ACTION_TYPES.FETCH_DISPOSITION_LIST);
export const fetchReasonList = createAction(API_ACTION_TYPES.FETCH_REASON_LIST);
export const fetchEnquiryStatuses = createAction(API_ACTION_TYPES.FETCH_ENQUIRY_STATUSES);
export const fetchEwsEnquiryList = createAction(API_ACTION_TYPES.FETCH_EWS_ENQUIRY_LIST);
export const fetchSubscriberByEnquiryId = createAction(API_ACTION_TYPES.FETCH_SUBSCRIBER_BY_ENQUIRY_ID);
export const fetchResidenceProofTypes = createAction(API_ACTION_TYPES.FETCH_RESIDENCE_PROOF_TYPES);
export const fetchIdentityProofTypes = createAction(API_ACTION_TYPES.FETCH_IDENTITY_PROOF_TYPES);
export const finalizeCaf = createAction(API_ACTION_TYPES.FINALIZE_CAF);
export const uploadSingleDocument = createAction(API_ACTION_TYPES.UPLOAD_SINGLE_DOCUMENT);
export const fetchOntNextPosition = createAction(API_ACTION_TYPES.FETCH_ONT_NEXT_POSITION);
export const updateEkycDetails = createAction(API_ACTION_TYPES.UPDATE_EKYC_DETAILS);
export const submitEkycDetails = createAction(API_ACTION_TYPES.SUBMIT_EKYC_DETAILS);
export const verifySubscriber = createAction(API_ACTION_TYPES.VERIFY_SUBSCRIBER);
export const onboardSubscriber = createAction(API_ACTION_TYPES.ONBOARD_SUBSCRIBER);
export const checkFeasibility = createAction(API_ACTION_TYPES.CHECK_FEASIBILITY);
export const fetchSubscribersPage = createAction(API_ACTION_TYPES.FETCH_SUBSCRIBERS_PAGE);
export const fetchSubscriberForwardUsers = createAction(API_ACTION_TYPES.FETCH_SUBSCRIBER_FORWARD_USERS);
export const assignSubscriberEnquiry = createAction(API_ACTION_TYPES.ASSIGN_SUBSCRIBER_ENQUIRY);
export const fetchEwsPackages = createAction(API_ACTION_TYPES.FETCH_EWS_PACKAGES);
export const getOntAcknowledgement = createAction(API_ACTION_TYPES.GET_ONT_ACKNOWLEDGEMENT);
export const verifyOntAcknowledgement = createAction(API_ACTION_TYPES.VERIFY_ONT_ACKNOWLEDGEMENT);
export const fetchSubscriberDetail = createAction(API_ACTION_TYPES.FETCH_SUBSCRIBER_DETAIL);
export const fetchSubscriberDataUsage = createAction(API_ACTION_TYPES.FETCH_SUBSCRIBER_DATA_USAGE);
export const fetchRadiusDetails = createAction(API_ACTION_TYPES.FETCH_RADIUS_DETAILS);
export const updateSubscriberDetail = createAction(API_ACTION_TYPES.UPDATE_SUBSCRIBER_DETAIL);
export const sendMobileChangeOtp = createAction(API_ACTION_TYPES.SEND_MOBILE_CHANGE_OTP);
export const verifyMobileChangeOtp = createAction(API_ACTION_TYPES.VERIFY_MOBILE_CHANGE_OTP);
export const resetSubscriberPassword = createAction(API_ACTION_TYPES.RESET_SUBSCRIBER_PASSWORD);
export const changeUsername = createAction(API_ACTION_TYPES.CHANGE_USERNAME);
export const downloadSubscribersCsv = createAction(API_ACTION_TYPES.DOWNLOAD_SUBSCRIBERS_CSV);
