import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

const API_ACTION_TYPES = {
  FETCH_TICKET_TABLE_DATA: `${STATE_REDUCER_KEY}/FETCH_TICKET_TABLE_DATA`,
  FETCH_CORPORATE_ENQUIRY_LIST: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_ENQUIRY_LIST`,
  FETCH_CORPORATE_ENQUIRY_EXPANDED_LIST: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_ENQUIRY_EXPANDED_LIST`,
  CREATE_CORPORATE_ENQUIRY: `${STATE_REDUCER_KEY}/CREATE_CORPORATE_ENQUIRY`,
  CREATE_CORPORATE_CUSTOMER: `${STATE_REDUCER_KEY}/CREATE_CORPORATE_CUSTOMER`,
  FETCH_CORPORATE_CUSTOMER_LIST: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_CUSTOMER_LIST`,
  FETCH_CORP_ENQUIRY_LOCATION_LIST: `${STATE_REDUCER_KEY}/FETCH_CORP_ENQUIRY_LOCATION_LIST`,
  FETCH_INDUSTRY_LIST: `${STATE_REDUCER_KEY}/FETCH_INDUSTRY_LIST`,
  FETCH_SERVICES_LIST: `${STATE_REDUCER_KEY}/FETCH_SERVICES_LIST`,
  FETCH_CONNECTION_TYPE_LIST: `${STATE_REDUCER_KEY}/FETCH_CONNECTION_TYPE_LIST`,
  DOWNLOAD_ENQUIRY_LIST_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_ENQUIRY_LIST_CSV`,
  DOWNLOAD_CORPORATE_PURCHASE_ORDER_LIST_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_CORPORATE_PURCHASE_ORDER_LIST_CSV`,
  DOWNLOAD_LOCATION_LIST_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_LOCATION_LIST_CSV`,
  DOWNLOAD_LOCATION_REPORT_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_LOCATION_REPORT_CSV`,
  LOCATION_FORWARD_TO_FE: `${STATE_REDUCER_KEY}/LOCATION_FORWARD_TO_FE`,
  LOCATION_FORWARD_TO_LNP: `${STATE_REDUCER_KEY}/LOCATION_FORWARD_TO_LNP`,
  FETCH_LOCATION_DETAILS: `${STATE_REDUCER_KEY}/FETCH_LOCATION_DETAILS`,
  SUBMIT_LOCATION_DATA: `${STATE_REDUCER_KEY}/SUBMIT_LOCATION_DATA`,
  FETCH_CUSTOMER_DETAILS: `${STATE_REDUCER_KEY}/FETCH_CUSTOMER_DETAILS`,
  FETCH_ENQUIRY_LIST: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_LIST`,
  FETCH_ENQUIRY_LIST_DROPDOWN: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_LIST_DROPDOWN`,
  FETCH_COMPANY_TYPE_LIST: `${STATE_REDUCER_KEY}/FETCH_COMPANY_TYPE_LIST`,
  DOWNLOAD_LOCATION_SAMPLE_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_LOCATION_SAMPLE_CSV`,
  FETCH_CORPORATE_PACKAGE_LIST: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_PACKAGE_LIST`,
  DOWNLOAD_PACKAGE_LIST_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_PACKAGE_LIST_CSV`,
  CREATE_CORPORATE_PACKAGE: `${STATE_REDUCER_KEY}/CREATE_CORPORATE_PACKAGE`,
  FETCH_CORPORATE_PROPOSAL_LIST: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_PROPOSAL_LIST`,
  DOWNLOAD_PROPOSAL_LIST_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_PROPOSAL_LIST_CSV`,
  CREATE_CORPORATE_PROPOSAL: `${STATE_REDUCER_KEY}/CREATE_CORPORATE_PROPOSAL`,
  FETCH_SERVICE_TYPES: `${STATE_REDUCER_KEY}/FETCH_SERVICE_TYPES`,
  FETCH_SUB_SERVICE_TYPES: `${STATE_REDUCER_KEY}/FETCH_SUB_SERVICE_TYPES`,
  FETCH_PLAN_TYPES: `${STATE_REDUCER_KEY}/FETCH_PLAN_TYPES`,
  FETCH_PROPOSAL_REVISIONS: `${STATE_REDUCER_KEY}/FETCH_PROPOSAL_REVISIONS`,
  FETCH_PROPOSAL_DETAILS: `${STATE_REDUCER_KEY}/FETCH_PROPOSAL_DETAILS`,
  UPDATE_CORPORATE_PROPOSAL: `${STATE_REDUCER_KEY}/UPDATE_CORPORATE_PROPOSAL`,
  CREATE_PURCHASE_ORDER: `${STATE_REDUCER_KEY}/CREATE_PURCHASE_ORDER`,
  FETCH_PO_DETAILS: `${STATE_REDUCER_KEY}/FETCH_PO_DETAILS`,
  UPDATE_PURCHASE_ORDER: `${STATE_REDUCER_KEY}/UPDATE_PURCHASE_ORDER`,
  GENERATE_PO_PDF: `${STATE_REDUCER_KEY}/GENERATE_PO_PDF`,
  DELETE_PO_DOCUMENT: `${STATE_REDUCER_KEY}/DELETE_PO_DOCUMENT`,
  FETCH_CIRCUIT_PROVISIONING: `${STATE_REDUCER_KEY}/FETCH_CIRCUIT_PROVISIONING`,
  CREATE_CIRCUIT_PROVISIONING: `${STATE_REDUCER_KEY}/CREATE_CIRCUIT_PROVISIONING`,
  UPDATE_CIRCUIT_PROVISIONING: `${STATE_REDUCER_KEY}/UPDATE_CIRCUIT_PROVISIONING`,
  FETCH_CIRCUIT_MULTICAST_TYPES: `${STATE_REDUCER_KEY}/FETCH_CIRCUIT_MULTICAST_TYPES`,
  FETCH_CIRCUIT_SERVICE_PROVIDERS: `${STATE_REDUCER_KEY}/FETCH_CIRCUIT_SERVICE_PROVIDERS`,
  FETCH_SERVICE_PROVISIONING: `${STATE_REDUCER_KEY}/FETCH_SERVICE_PROVISIONING`,
  CREATE_SERVICE_PROVISIONING: `${STATE_REDUCER_KEY}/CREATE_SERVICE_PROVISIONING`,
  UPDATE_SERVICE_PROVISIONING: `${STATE_REDUCER_KEY}/UPDATE_SERVICE_PROVISIONING`,
  FETCH_ENQUIRY_DETAILS: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_DETAILS`,
  FETCH_CORPORATE_PURCHASE_ORDER_LIST: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_PURCHASE_ORDER_LIST`,
  FETCH_MEETING_HISTORY: `${STATE_REDUCER_KEY}/FETCH_MEETING_HISTORY`,
  FETCH_FORWARD_ROLES: `${STATE_REDUCER_KEY}/FETCH_FORWARD_ROLES`,
  FETCH_ROLE_USERS: `${STATE_REDUCER_KEY}/FETCH_ROLE_USERS`,
  FETCH_ENQUIRY_NOTES: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_NOTES`,
  ASSIGN_ENQUIRY: `${STATE_REDUCER_KEY}/ASSIGN_ENQUIRY`,
  ASSIGN_ENQUIRY_MULTIPLE: `${STATE_REDUCER_KEY}/ASSIGN_ENQUIRY_MULTIPLE`,
  FORWARD_ENQUIRY: `${STATE_REDUCER_KEY}/FORWARD_ENQUIRY`,
  SAVE_MEETING: `${STATE_REDUCER_KEY}/SAVE_MEETING`,
  FETCH_DISPOSITION_LIST: `${STATE_REDUCER_KEY}/FETCH_DISPOSITION_LIST`,
  FETCH_REASON_LIST: `${STATE_REDUCER_KEY}/FETCH_REASON_LIST`,
  SAVE_DISPOSITION: `${STATE_REDUCER_KEY}/SAVE_DISPOSITION`,
  UPDATE_DISPOSITION: `${STATE_REDUCER_KEY}/UPDATE_DISPOSITION`,
  FETCH_LOCATION_DISPOSITION: `${STATE_REDUCER_KEY}/FETCH_LOCATION_DISPOSITION`,
  SAVE_NOTE: `${STATE_REDUCER_KEY}/SAVE_NOTE`,
  FETCH_FEASIBILITY_LNP_LIST: `${STATE_REDUCER_KEY}/FETCH_FEASIBILITY_LNP_LIST`,
  FETCH_FEASIBILITY_CONNECTED_BY_LIST: `${STATE_REDUCER_KEY}/FETCH_FEASIBILITY_CONNECTED_BY_LIST`,
  FETCH_NEAREST_POP: `${STATE_REDUCER_KEY}/FETCH_NEAREST_POP`,
  SAVE_FEASIBILITY: `${STATE_REDUCER_KEY}/SAVE_FEASIBILITY`,
  SAVE_NEAREST_LOCATION: `${STATE_REDUCER_KEY}/SAVE_NEAREST_LOCATION`,
  UPDATE_NEAREST_LOCATION: `${STATE_REDUCER_KEY}/UPDATE_NEAREST_LOCATION`,
  FETCH_NEAREST_LOCATION: `${STATE_REDUCER_KEY}/FETCH_NEAREST_LOCATION`,
  UPDATE_CORPORATE_ENQUIRY: `${STATE_REDUCER_KEY}/UPDATE_CORPORATE_ENQUIRY`,
  VERIFY_CUSTOMER: `${STATE_REDUCER_KEY}/VERIFY_CUSTOMER`,
  SAVE_CUSTOMER_BASIC_DETAILS: `${STATE_REDUCER_KEY}/SAVE_CUSTOMER_BASIC_DETAILS`,
  UPDATE_CUSTOMER_BASIC_DETAILS: `${STATE_REDUCER_KEY}/UPDATE_CUSTOMER_BASIC_DETAILS`,
  UPDATE_CUSTOMER_PAN_DETAILS: `${STATE_REDUCER_KEY}/UPDATE_CUSTOMER_PAN_DETAILS`,
  FETCH_KYC_DETAILS: `${STATE_REDUCER_KEY}/FETCH_KYC_DETAILS`,
  UPDATE_CUSTOMER_GST_DETAILS: `${STATE_REDUCER_KEY}/UPDATE_CUSTOMER_GST_DETAILS`,
  SEARCH_CORPORATE_GST_DETAILS: `${STATE_REDUCER_KEY}/SEARCH_CORPORATE_GST_DETAILS`,
  DELINK_CORPORATE_CUSTOMER: `${STATE_REDUCER_KEY}/DELINK_CORPORATE_CUSTOMER`,
  LINK_CORPORATE_CUSTOMER: `${STATE_REDUCER_KEY}/LINK_CORPORATE_CUSTOMER`,
  SUBMIT_ENQUIRY_LOCATION: `${STATE_REDUCER_KEY}/SUBMIT_ENQUIRY_LOCATION`,
  FETCH_ENQUIRY_LOCATIONS: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_LOCATIONS`,
  FETCH_PACKAGE_TYPES_LIST: `${STATE_REDUCER_KEY}/FETCH_PACKAGE_TYPES_LIST`,
  FETCH_PACKAGES_LIST: `${STATE_REDUCER_KEY}/FETCH_PACKAGES_LIST`,
  FETCH_ADDITIONAL_SERVICES_LIST: `${STATE_REDUCER_KEY}/FETCH_ADDITIONAL_SERVICES_LIST`,
  UPDATE_ENQUIRY_LOCATION: `${STATE_REDUCER_KEY}/UPDATE_ENQUIRY_LOCATION`,
  FETCH_ENQUIRY_LOCATION_DETAILS: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_LOCATION_DETAILS`,
  FETCH_KYC_DOCUMENT: `${STATE_REDUCER_KEY}/FETCH_KYC_DOCUMENT`,
  FETCH_ENQUIRY_DISPOSITION_LIST: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_DISPOSITION_LIST`,
  FETCH_RETURN_TO_INFO: `${STATE_REDUCER_KEY}/FETCH_RETURN_TO_INFO`,
  RETURN_TO_ENQUIRY: `${STATE_REDUCER_KEY}/RETURN_TO_ENQUIRY`,
  FETCH_LOCATIONS_BY_SEAT: `${STATE_REDUCER_KEY}/FETCH_LOCATIONS_BY_SEAT`,
  SAVE_ENQUIRY_PROPOSAL: `${STATE_REDUCER_KEY}/SAVE_ENQUIRY_PROPOSAL`,
  CREATE_LOCATION_PROPOSAL: `${STATE_REDUCER_KEY}/CREATE_LOCATION_PROPOSAL`,
  UPDATE_LOCATION_PROPOSAL: `${STATE_REDUCER_KEY}/UPDATE_LOCATION_PROPOSAL`,
  BULK_UPDATE_PROPOSALS: `${STATE_REDUCER_KEY}/BULK_UPDATE_PROPOSALS`,
  FETCH_ENQUIRY_PROPOSALS: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_PROPOSALS`,
  FETCH_ENQUIRY_LOCATIONS_SUMMARY: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_LOCATIONS_SUMMARY`,
  FETCH_CORPORATE_ENQUIRY_SUMMARY: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_ENQUIRY_SUMMARY`,
  FETCH_CORPORATE_ENQUIRY_OUTBOX: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_ENQUIRY_OUTBOX`,
  SEND_CORPORATE_PROPOSAL: `${STATE_REDUCER_KEY}/SEND_CORPORATE_PROPOSAL`,
  CREATE_CORPORATE_PROPOSAL_SEND: `${STATE_REDUCER_KEY}/CREATE_CORPORATE_PROPOSAL_SEND`,
  FETCH_CORPORATE_PROPOSAL_SEND: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_PROPOSAL_SEND`,
  FETCH_PROPOSAL_SEND_PREVIEW: `${STATE_REDUCER_KEY}/FETCH_PROPOSAL_SEND_PREVIEW`,
  DELETE_KYC_DOCUMENT: `${STATE_REDUCER_KEY}/DELETE_KYC_DOCUMENT`,
  UPLOAD_KYC_DOCUMENT: `${STATE_REDUCER_KEY}/UPLOAD_KYC_DOCUMENT`,
  UPDATE_PROPOSAL_STATUS: `${STATE_REDUCER_KEY}/UPDATE_PROPOSAL_STATUS`,
  FETCH_PROPOSAL_DISPATCH: `${STATE_REDUCER_KEY}/FETCH_PROPOSAL_DISPATCH`,
  SEND_EMAIL_PROPOSAL_DISPATCH: `${STATE_REDUCER_KEY}/SEND_EMAIL_PROPOSAL_DISPATCH`,
  SEND_DIRECT_PROPOSAL_DISPATCH: `${STATE_REDUCER_KEY}/SEND_DIRECT_PROPOSAL_DISPATCH`,
  CORPORATE_LOCATION_UPLOAD: `${STATE_REDUCER_KEY}/CORPORATE_LOCATION_UPLOAD`,
  DOWNLOAD_LOCATION_CSV_TEMPLATE: `${STATE_REDUCER_KEY}/DOWNLOAD_LOCATION_CSV_TEMPLATE`,
  APPROVE_SERVICE_PROVISIONING: `${STATE_REDUCER_KEY}/APPROVE_SERVICE_PROVISIONING`,
  GENERATE_SERVICE_COMMISSIONING_INVOICE: `${STATE_REDUCER_KEY}/GENERATE_SERVICE_COMMISSIONING_INVOICE`,
  FETCH_SERVICE_COMMISSIONING_INVOICE: `${STATE_REDUCER_KEY}/FETCH_SERVICE_COMMISSIONING_INVOICE`,
  FETCH_ENQUIRY_SUMMARY_WITH_PROPOSALS: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_SUMMARY_WITH_PROPOSALS`,
  FETCH_PROPOSALS_BY_ENQUIRY: `${STATE_REDUCER_KEY}/FETCH_PROPOSALS_BY_ENQUIRY`,
  FETCH_ENQUIRY_SUMMARY_WITH_PO: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_SUMMARY_WITH_PO`,
  FETCH_PO_BY_ENQUIRY: `${STATE_REDUCER_KEY}/FETCH_PO_BY_ENQUIRY`,
  FETCH_ENQUIRY_SUMMARY_WITH_CIRCUIT_PROVISIONING: `${STATE_REDUCER_KEY}/FETCH_ENQUIRY_SUMMARY_WITH_CIRCUIT_PROVISIONING`,
  FETCH_SERVICE_COMMISSIONING_BY_ENQUIRY: `${STATE_REDUCER_KEY}/FETCH_SERVICE_COMMISSIONING_BY_ENQUIRY`,
  FETCH_NEXT_STEP_USERS: `${STATE_REDUCER_KEY}/FETCH_NEXT_STEP_USERS`,
  CLEAR_NEXT_STEP_USERS: `${STATE_REDUCER_KEY}/CLEAR_NEXT_STEP_USERS`,
  FORWARD_NEXT_STEP: `${STATE_REDUCER_KEY}/FORWARD_NEXT_STEP`
};

export const ACTION_TYPES = {
  ...API_ACTION_TYPES
};

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchTicketTableData = createAction(ACTION_TYPES.FETCH_TICKET_TABLE_DATA);
export const fetchCorporateEnquiryList = createAction(ACTION_TYPES.FETCH_CORPORATE_ENQUIRY_LIST);
export const fetchCorporateEnquiryExpandedList = createAction(ACTION_TYPES.FETCH_CORPORATE_ENQUIRY_EXPANDED_LIST);
export const fetchCorporateEnquirySummaryList = createAction(ACTION_TYPES.FETCH_CORPORATE_ENQUIRY_SUMMARY);
export const fetchCorporateEnquiryOutbox = createAction(ACTION_TYPES.FETCH_CORPORATE_ENQUIRY_OUTBOX);
export const createCorporateEnquiry = createAction(ACTION_TYPES.CREATE_CORPORATE_ENQUIRY);
export const createCorporateCustomer = createAction(ACTION_TYPES.CREATE_CORPORATE_CUSTOMER);
export const fetchCorporateCustomerList = createAction(ACTION_TYPES.FETCH_CORPORATE_CUSTOMER_LIST);
export const fetchCorpEnquiryLocationList = createAction(ACTION_TYPES.FETCH_CORP_ENQUIRY_LOCATION_LIST);
export const fetchIndustryList = createAction(ACTION_TYPES.FETCH_INDUSTRY_LIST);
export const fetchServicesList = createAction(ACTION_TYPES.FETCH_SERVICES_LIST);
export const fetchConnectionTypeList = createAction(ACTION_TYPES.FETCH_CONNECTION_TYPE_LIST);
export const downloadEnquiryListCsv = createAction(API_ACTION_TYPES.DOWNLOAD_ENQUIRY_LIST_CSV);
export const downloadLocationListCsv = createAction(API_ACTION_TYPES.DOWNLOAD_LOCATION_LIST_CSV);
export const downloadLocationReportCsv = createAction(API_ACTION_TYPES.DOWNLOAD_LOCATION_REPORT_CSV);
export const downloadLocationSampleCsv = createAction(API_ACTION_TYPES.DOWNLOAD_LOCATION_SAMPLE_CSV);
export const locationForwardToFE = createAction(API_ACTION_TYPES.LOCATION_FORWARD_TO_FE);
export const locationForwardToLNP = createAction(API_ACTION_TYPES.LOCATION_FORWARD_TO_LNP);
export const fetchLocationDetails = createAction(API_ACTION_TYPES.FETCH_LOCATION_DETAILS);
export const submitLocationData = createAction(API_ACTION_TYPES.SUBMIT_LOCATION_DATA);
export const fetchCustomerDetails = createAction(API_ACTION_TYPES.FETCH_CUSTOMER_DETAILS);
export const fetchEnquiryList = createAction(ACTION_TYPES.FETCH_ENQUIRY_LIST);
export const fetchEnquiryListDropdown = createAction(ACTION_TYPES.FETCH_ENQUIRY_LIST_DROPDOWN);
export const fetchCompanyTypeList = createAction(ACTION_TYPES.FETCH_COMPANY_TYPE_LIST);
export const fetchCorporatePackageList = createAction(ACTION_TYPES.FETCH_CORPORATE_PACKAGE_LIST);
export const downloadPackageListCsv = createAction(API_ACTION_TYPES.DOWNLOAD_PACKAGE_LIST_CSV);
export const createCorporatePackage = createAction(API_ACTION_TYPES.CREATE_CORPORATE_PACKAGE);
export const fetchServiceTypes = createAction(ACTION_TYPES.FETCH_SERVICE_TYPES);
export const fetchSubServiceTypes = createAction(ACTION_TYPES.FETCH_SUB_SERVICE_TYPES);
export const fetchPlanTypes = createAction(ACTION_TYPES.FETCH_PLAN_TYPES);
export const fetchCorporateProposalList = createAction(ACTION_TYPES.FETCH_CORPORATE_PROPOSAL_LIST);
export const downloadProposalListCsv = createAction(API_ACTION_TYPES.DOWNLOAD_PROPOSAL_LIST_CSV);
export const createCorporateProposal = createAction(API_ACTION_TYPES.CREATE_CORPORATE_PROPOSAL);
export const fetchProposalRevisions = createAction(ACTION_TYPES.FETCH_PROPOSAL_REVISIONS);
export const fetchProposalDetails = createAction(ACTION_TYPES.FETCH_PROPOSAL_DETAILS);
export const updateCorporateProposal = createAction(ACTION_TYPES.UPDATE_CORPORATE_PROPOSAL);
export const createPurchaseOrder = createAction(ACTION_TYPES.CREATE_PURCHASE_ORDER);
export const fetchPurchaseOrderDetails = createAction(ACTION_TYPES.FETCH_PO_DETAILS);
export const updatePurchaseOrder = createAction(ACTION_TYPES.UPDATE_PURCHASE_ORDER);
export const generatePoPdf = createAction(ACTION_TYPES.GENERATE_PO_PDF);
export const deletePurchaseOrderDocument = createAction(ACTION_TYPES.DELETE_PO_DOCUMENT);
export const fetchCircuitProvisioning = createAction(ACTION_TYPES.FETCH_CIRCUIT_PROVISIONING);
export const createCircuitProvisioning = createAction(ACTION_TYPES.CREATE_CIRCUIT_PROVISIONING);
export const updateCircuitProvisioning = createAction(ACTION_TYPES.UPDATE_CIRCUIT_PROVISIONING);
export const fetchCircuitMulticastTypes = createAction(ACTION_TYPES.FETCH_CIRCUIT_MULTICAST_TYPES);
export const fetchCircuitServiceProviders = createAction(ACTION_TYPES.FETCH_CIRCUIT_SERVICE_PROVIDERS);
export const fetchServiceProvisioning = createAction(ACTION_TYPES.FETCH_SERVICE_PROVISIONING);
export const createServiceProvisioning = createAction(ACTION_TYPES.CREATE_SERVICE_PROVISIONING);
export const updateServiceProvisioning = createAction(ACTION_TYPES.UPDATE_SERVICE_PROVISIONING);
export const fetchEnquiryDetails = createAction(ACTION_TYPES.FETCH_ENQUIRY_DETAILS);
export const fetchCorporatePurchaseOrderList = createAction(ACTION_TYPES.FETCH_CORPORATE_PURCHASE_ORDER_LIST);
export const downloadCorporatePurchaseOrderListCsv = createAction(
  API_ACTION_TYPES.DOWNLOAD_CORPORATE_PURCHASE_ORDER_LIST_CSV
);
export const fetchMeetingHistory = createAction(ACTION_TYPES.FETCH_MEETING_HISTORY);
export const fetchForwardRoles = createAction(ACTION_TYPES.FETCH_FORWARD_ROLES);
export const fetchRoleUsers = createAction(ACTION_TYPES.FETCH_ROLE_USERS);
export const fetchEnquiryNotes = createAction(ACTION_TYPES.FETCH_ENQUIRY_NOTES);
export const assignEnquiry = createAction(ACTION_TYPES.ASSIGN_ENQUIRY);
export const assignEnquiryMultiple = createAction(ACTION_TYPES.ASSIGN_ENQUIRY_MULTIPLE);
export const forwardEnquiry = createAction(ACTION_TYPES.FORWARD_ENQUIRY);
export const saveMeeting = createAction(ACTION_TYPES.SAVE_MEETING);
export const fetchDispositionList = createAction(ACTION_TYPES.FETCH_DISPOSITION_LIST);
export const fetchReasonList = createAction(ACTION_TYPES.FETCH_REASON_LIST);
export const saveDisposition = createAction(ACTION_TYPES.SAVE_DISPOSITION);
export const updateDisposition = createAction(ACTION_TYPES.UPDATE_DISPOSITION);
export const fetchLocationDisposition = createAction(ACTION_TYPES.FETCH_LOCATION_DISPOSITION);
export const saveNote = createAction(ACTION_TYPES.SAVE_NOTE);
export const fetchFeasibilityLnpList = createAction(ACTION_TYPES.FETCH_FEASIBILITY_LNP_LIST);
export const fetchFeasibilityConnectedByList = createAction(ACTION_TYPES.FETCH_FEASIBILITY_CONNECTED_BY_LIST);
export const fetchNearestPop = createAction(ACTION_TYPES.FETCH_NEAREST_POP);
export const saveFeasibility = createAction(ACTION_TYPES.SAVE_FEASIBILITY);
export const saveNearestLocation = createAction(ACTION_TYPES.SAVE_NEAREST_LOCATION);
export const updateNearestLocation = createAction(ACTION_TYPES.UPDATE_NEAREST_LOCATION);
export const fetchNearestLocation = createAction(ACTION_TYPES.FETCH_NEAREST_LOCATION);
export const updateCorporateEnquiry = createAction(ACTION_TYPES.UPDATE_CORPORATE_ENQUIRY);
export const verifyCustomer = createAction(ACTION_TYPES.VERIFY_CUSTOMER);
export const saveCustomerBasicDetails = createAction(ACTION_TYPES.SAVE_CUSTOMER_BASIC_DETAILS);
export const updateCustomerBasicDetails = createAction(ACTION_TYPES.UPDATE_CUSTOMER_BASIC_DETAILS);
export const updateCustomerPANDetails = createAction(ACTION_TYPES.UPDATE_CUSTOMER_PAN_DETAILS);
export const fetchKycDetails = createAction(ACTION_TYPES.FETCH_KYC_DETAILS);
export const updateCustomerGSTDetails = createAction(ACTION_TYPES.UPDATE_CUSTOMER_GST_DETAILS);
export const searchCorporateGstDetails = createAction(ACTION_TYPES.SEARCH_CORPORATE_GST_DETAILS);
export const delinkCorporateCustomer = createAction(ACTION_TYPES.DELINK_CORPORATE_CUSTOMER);
export const linkCorporateCustomer = createAction(ACTION_TYPES.LINK_CORPORATE_CUSTOMER);
export const submitEnquiryLocation = createAction(ACTION_TYPES.SUBMIT_ENQUIRY_LOCATION);
export const fetchEnquiryLocations = createAction(ACTION_TYPES.FETCH_ENQUIRY_LOCATIONS);
export const fetchPackageTypesList = createAction(ACTION_TYPES.FETCH_PACKAGE_TYPES_LIST);
export const fetchPackagesList = createAction(ACTION_TYPES.FETCH_PACKAGES_LIST);
export const fetchAdditionalServicesList = createAction(ACTION_TYPES.FETCH_ADDITIONAL_SERVICES_LIST);
export const updateEnquiryLocation = createAction(ACTION_TYPES.UPDATE_ENQUIRY_LOCATION);
export const fetchEnquiryLocationDetails = createAction(ACTION_TYPES.FETCH_ENQUIRY_LOCATION_DETAILS);
export const fetchKycDocument = createAction(ACTION_TYPES.FETCH_KYC_DOCUMENT);
export const deleteKycDocument = createAction(ACTION_TYPES.DELETE_KYC_DOCUMENT);
export const uploadKycDocument = createAction(ACTION_TYPES.UPLOAD_KYC_DOCUMENT);
export const fetchEnquiryDispositionList = createAction(ACTION_TYPES.FETCH_ENQUIRY_DISPOSITION_LIST);
export const fetchReturnToInfo = createAction(ACTION_TYPES.FETCH_RETURN_TO_INFO);
export const returnToEnquiry = createAction(ACTION_TYPES.RETURN_TO_ENQUIRY);
export const fetchLocationsBySeat = createAction(ACTION_TYPES.FETCH_LOCATIONS_BY_SEAT);
export const saveEnquiryProposal = createAction(ACTION_TYPES.SAVE_ENQUIRY_PROPOSAL);
export const createLocationProposal = createAction(ACTION_TYPES.CREATE_LOCATION_PROPOSAL);
export const updateLocationProposal = createAction(ACTION_TYPES.UPDATE_LOCATION_PROPOSAL);
export const bulkUpdateProposals = createAction(ACTION_TYPES.BULK_UPDATE_PROPOSALS);
export const fetchEnquiryProposals = createAction(ACTION_TYPES.FETCH_ENQUIRY_PROPOSALS);
export const fetchEnquiryLocationsSummary = createAction(ACTION_TYPES.FETCH_ENQUIRY_LOCATIONS_SUMMARY);
export const sendCorporateProposal = createAction(ACTION_TYPES.SEND_CORPORATE_PROPOSAL);
export const createCorporateProposalSend = createAction(ACTION_TYPES.CREATE_CORPORATE_PROPOSAL_SEND);
export const fetchCorporateProposalSend = createAction(ACTION_TYPES.FETCH_CORPORATE_PROPOSAL_SEND);
export const fetchProposalSendPreview = createAction(ACTION_TYPES.FETCH_PROPOSAL_SEND_PREVIEW);
export const updateProposalStatus = createAction(ACTION_TYPES.UPDATE_PROPOSAL_STATUS);
export const fetchProposalDispatch = createAction(ACTION_TYPES.FETCH_PROPOSAL_DISPATCH);
export const sendEmailProposalDispatch = createAction(ACTION_TYPES.SEND_EMAIL_PROPOSAL_DISPATCH);
export const sendDirectProposalDispatch = createAction(ACTION_TYPES.SEND_DIRECT_PROPOSAL_DISPATCH);
export const corporateLocationUpload = createAction(ACTION_TYPES.CORPORATE_LOCATION_UPLOAD);
export const downloadLocationCsvTemplate = createAction(ACTION_TYPES.DOWNLOAD_LOCATION_CSV_TEMPLATE);
export const approveServiceProvisioning = createAction(ACTION_TYPES.APPROVE_SERVICE_PROVISIONING);
export const generateServiceCommissioningInvoice = createAction(ACTION_TYPES.GENERATE_SERVICE_COMMISSIONING_INVOICE);
export const fetchServiceCommissioningInvoice = createAction(ACTION_TYPES.FETCH_SERVICE_COMMISSIONING_INVOICE);
export const fetchEnquirySummaryWithProposals = createAction(ACTION_TYPES.FETCH_ENQUIRY_SUMMARY_WITH_PROPOSALS);
export const fetchProposalsByEnquiry = createAction(ACTION_TYPES.FETCH_PROPOSALS_BY_ENQUIRY);
export const fetchEnquirySummaryWithPo = createAction(ACTION_TYPES.FETCH_ENQUIRY_SUMMARY_WITH_PO);
export const fetchPoByEnquiry = createAction(ACTION_TYPES.FETCH_PO_BY_ENQUIRY);
export const fetchEnquirySummaryWithCircuitProvisioning = createAction(ACTION_TYPES.FETCH_ENQUIRY_SUMMARY_WITH_CIRCUIT_PROVISIONING);
export const fetchServiceCommissioningByEnquiry = createAction(ACTION_TYPES.FETCH_SERVICE_COMMISSIONING_BY_ENQUIRY);
export const fetchNextStepUsers = createAction(ACTION_TYPES.FETCH_NEXT_STEP_USERS);
export const clearNextStepUsers = createAction(ACTION_TYPES.CLEAR_NEXT_STEP_USERS);
export const forwardNextStep = createAction(ACTION_TYPES.FORWARD_NEXT_STEP);
