import { createAction } from "@reduxjs/toolkit";

import { generateActionTypeVariants } from '@/utils/actionUtils'

import { STATE_REDUCER_KEY } from './constants'

const API_ACTION_TYPES = {
    FETCH_APPROVAL_TABLE_DATA: `${STATE_REDUCER_KEY}/FETCH_APPROVAL_TABLE_DATA`,
    FETCH_SUMMARY_TABLE_DATA: `${STATE_REDUCER_KEY}/FETCH_SUMMARY_TABLE_DATA`,
    FETCH_PARTNER_FINANCE_TABLE_DATA: `${STATE_REDUCER_KEY}/FETCH_PARTNER_FINANCE_TABLE_DATA`,
    FETCH_INVOICE_TABLE_DATA: `${STATE_REDUCER_KEY}/FETCH_INVOICE_TABLE_DATA`,
    FETCH_FINANCE_TRANSACTION_TABLE_DATA: `${STATE_REDUCER_KEY}/FETCH_FINANCE_TRANSACTION_TABLE_DATA`,
    FETCH_GST_WALLET_TABLE_DATA: `${STATE_REDUCER_KEY}/FETCH_GST_WALLET_TABLE_DATA`,
    FETCH_LNP_REVENUE_TABLE_DATA: `${STATE_REDUCER_KEY}/FETCH_LNP_REVENUE_TABLE_DATA`,
    FETCH_GST_DETAILS_DATA: `${STATE_REDUCER_KEY}/FETCH_GST_DETAILS_DATA`
}

export const ACTION_TYPES = {
    ...API_ACTION_TYPES
}

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchApprovalTableData = createAction(API_ACTION_TYPES.FETCH_APPROVAL_TABLE_DATA)
export const fetchSummaryTableData = createAction(API_ACTION_TYPES.FETCH_SUMMARY_TABLE_DATA)
export const fetchPartnerFinanceTableData = createAction(API_ACTION_TYPES.FETCH_PARTNER_FINANCE_TABLE_DATA)
export const fetchInvoiceTableData = createAction(API_ACTION_TYPES.FETCH_INVOICE_TABLE_DATA)
export const fetchFinanceTransactionTableData = createAction(API_ACTION_TYPES.FETCH_FINANCE_TRANSACTION_TABLE_DATA)
export const fetchGstWalletTableData = createAction(API_ACTION_TYPES.FETCH_GST_WALLET_TABLE_DATA)
export const fetchLnpRevenuTableData = createAction(API_ACTION_TYPES.FETCH_LNP_REVENUE_TABLE_DATA)
export const fetchGstDetails = createAction(API_ACTION_TYPES.FETCH_GST_DETAILS_DATA)