export const MENU_KEYS = {
  PARTNERS_ENQUIRY_LIST: 'partners_enquiry_list',
  PARTNERS_LIST: 'partners_list',
  TICKET_LIST: 'ticket_list',
  ADD_STOCK: 'add_stock',
  STOCK_MANAGEMENT: 'stock_management',
  STOCK_LIST: 'stock_list',
  DEVICE_TYPE: 'device_type',
  DEVICE_MAKE: 'device_make',
  DEVICE_CATEGORY: 'device_category',
  DEVICE_MODEL: 'device_model',
  DEVICE_VENDOR: 'device_vendor',
  CORPORATE_ENQUIRY_LIST: 'corporate_enquiry_list',
  CORPORATE_ENQUIRY_LOCATION_LIST: 'corporate_enquiry_location_list',
  CORPORATE_CIRCUIT_PROVISIONING: 'corporate_circuit_provisioning',
  CORPORATE_SERVICE_PROVISIONING: 'corporate_service_provisioning',
  PACKAGE_LIST: 'package_list',
  MANAGE_PACKAGES: 'manage_packages',
  ADD_PACKAGE: 'add_package',
  RETAIL: 'retail_package',
  CORPORATE: 'corporate_package',
  SUBSCRIBER_ENQUIRY_LIST: 'subscriber_enquiry_list',
  OEM_REQUEST: 'oem_request',
  EWS_WORK_ORDER: 'ews_work_order',
  SERVICES: 'package_services',
  MAIN_SERVICES: 'package_main_services',
  SUB_SERVICES: 'package_sub_services',
  COMBINATION: 'package_combination',
  LNP_WALLET_REPORT: 'lnp_wallet_report',
  SUBSCRIBER_WALLET_REPORT: 'subscriber_wallet_report',
  AGNP_WALLET_REPORT: 'agnp_wallet_report',
  GSTR_2A_REFUND_REPORT: 'gstr_2A_refund_report',
  GSTR_1_REPORT: 'gstr_1_report',
  B2B_INVOICES_REPORT: 'b2b_invoices_report',
  SUBSCRIBER_ONLINE_RECHARGE_REPORTS: 'subscriber_online_recharge_reports',
  PARTNER_WALLET_RECHARGE_REPORTS: 'partner_wallet_recharge_reports',
  RECHARGE_INSIGHTS_REPORTS: 'recharge_insights_reports',
  PARTNERS_DASHBOARD: 'partners_dashboard',
  SUBSCRIBERS_DASHBOARD: 'subscribers_dashboard',
  CRM_DASHBOARD: 'crm_dashboard',
  CRM_ALL_TICKETS: 'crm_all_tickets',
  CRM_LONG_PENDING: 'crm_long_pending',
  CRM_PERFORMANCE_PENDING: 'crm_performance_pending',
  CRM_DIVISIONS: 'crm_divisions',
  CORP_CUSTOMER_LIST: 'corp_customer_list',
  INVENTORY_DASHBOARD: 'inventory_dashboard'
};

export const INVENTORY_DASHBOARD_ACTIONS = {
  STATE_ACCESS: 'inventory_dashboard_state_access',
  DISTRICT_ACCESS: 'inventory_dashboard_district_access',
  INDIVIDUAL_ACCESS: 'inventory_dashboard_individual_access'
};

export const PERMISSIONS = {
  PARTNERS: {
    ONBOARD_PARTNER: 'onboard_partner',
    UPDATE_FEASIBILITY: 'update_feasibility',
    APPROVE_PARTNER: 'approve_partner',
    PARTNER_ENQ_FORWARD_PLUS: 'partner_enq_forward_plus',
    UPDATE_PARTNER_LINK_DETAILS: 'update_partner_link_details',
    EDIT_PARTNER_DETAIL: 'edit_partner_detail'
  },
  TICKET: {
    SEARCH: 'search',
    FILTER: 'filter',
    DOWNLOAD_CSV: 'download_csv',
    CREATE_TICKET: 'create_ticket',
    TAKE_OVER: 'take_over',
    REOPEN: 'reopen'
  },
  INVENTORY: {
    ADD_STOCK: 'add_stock',
    STOCK_MANAGEMENT: 'stock_management',
    STOCK_LIST: 'stock_list',
    DEVICE_TYPE: 'device_type',
    DEVICE_MAKE: 'device_make',
    DEVICE_CATEGORY: 'device_category',
    DEVICE_MODEL: 'device_model',
    DEVICE_VENDOR: 'device_vendor'
  },
  CORPORATE: {
    CORP_CREATE_ENQUIRY: 'create_enquiry',
    CORP_SEARCH: 'search',
    CORP_FILTER: 'filter',
    CORP_DOWNLOAD_CSV: 'download_csv',
    CORP_FORWARD_PLUS: 'forward_plus',
    CORP_EDIT: 'edit',
    CORP_CUSTOMER_VERIFICATION: 'corp_customer_verification',
    CORP_MEETINGS: 'meetings',
    CORP_ADD_LOCATION: 'add_location',
    CORP_ADD_SUBSCRIBER: 'add_subscriber',
    CORP_ASSIGN_TO: 'assign_to',
    CORP_RETURN_TO: 'return_to',
    CORP_DISPOSITION: 'disposition',
    CORP_NEAREST_CONNECTION: 'nearest_connection',
    CORP_VIEW: 'corp_view',
    LOCATION_VIEW: 'corp_location_view',
    CORP_SEND_TO_CUSTOMER: 'corp_send_to_customer',
    CORP_UPDATE_PO: 'corp_update_po',
    CORP_REVISE_PROPOSAL: 'corp_revise_proposal',
    PROPOSAL_CREATE: 'proposal_create',
    PROPOSAL_EDIT: 'proposal_edit',
    PROPOSAL_APPROVE: 'proposal_approve',
    PROPOSAL_VERIFY: 'proposal_verify',
    ENQUIRY_PROPOSAL_CREATE: 'enquiry_proposal_create',
    ENQUIRY_PROPOSAL_EDIT: 'enquiry_proposal_edit',
    ENQUIRY_PROPOSAL_VERIFY: 'enquiry_proposal_verify',
    ENQUIRY_PROPOSAL_APPROVE: 'enquiry_proposal_approve',
    ENQUIRY_CORP_REVISE_PROPOSAL: 'enquiry_corp_revise_proposal',
    ENQUIRY_CORP_UPDATE_PO: 'enquiry_corp_update_po',
    ENQUIRY_CORP_SEND_TO_CUSTOMER: 'enquiry_corp_send_to_customer',
    ENQUIRY_VIEW_PURCHASE_ORDER: 'enquiry_view_purchase_order',
    CORP_CIRCUIT_PROVISIONING: 'view_circuit_provisioning',
    CORP_SAVE_CIRCUIT_PROVISIONING: 'save_circuit_provisioning',
    CORP_SERVICE_PROVISIONING: 'view_service_provisioning',
    CORP_SAVE_SERVICE_PROVISIONING: 'save_service_provisioning',
    CORP_APPROVE_SERVICE_PROVISIONING: 'approve_service_provisioning',
    LOCATION_FILTER: 'location_filter',
    LOCATION_DOWNLOAD_CSV: 'location_download_csv',
    LOCATION_ASSIGN_TO: 'location_assign_to',
    LOCATION_RETURN_TO: 'location_return_to',
    LOCATION_EDIT: 'location_edit',
    LOCATION_SEARCH: 'location_search',
    LOCATION_DISPOSITION: 'location_disposition',
    LOCATION_NEAREST_CONNECTION: 'location_nearest_connection'
  },
  STOCK_LIST: {
    APPROVE_REJECT: 'stock_approve_reject'
  },
  STOCK_MANAGEMENT: {
    DEVICE_REQUEST: 'device_request',
    DEVICE_TRANSFER: 'device_transfer',
    TRANSFER_TO_OEM: 'transfer_to_oem',
    UPDATE_CONDITION: 'update_condition',
    MAP_TO_LOCATION: 'map_to_location',
    LOCATION_MAPPING_APPROVAL: 'location_mapping_approval',
    TRANSFER_OEM_APPROVAL: 'transfer_oem_approval',
    DEVICE_REPLACEMENT: 'device_replacement',
    UPDATE_DEVICE_DETAILS: 'update_device_details'
  },
  SUBSCRIBER: {
    SUBSCRIBER_DOWNLOAD_CSV: 'subscriber_download_csv',
    SUBSCRIBER_ASSIGN_TO_LNP: 'subscriber_assignToLnp',
    SUBSCRIBER_ASSIGN_TO_FE: 'subscriber_assignToFe',
    SUBSCRIBER_CREATE_ENQUIRY: 'subscriber_create_enquiry',
    SUBSCRIBER_MEETING: 'subscriber_meeting',
    SUBSCRIBER_DISPOSITION: 'subscriber_disposition',
    SUBSCRIBER_ONBOARD_SUBSCRIBER: 'onboard_subscriber',
    SUBSCRIBER_VERIFY: 'verify_subscriber',
    SUBSCRIBER_ENQ_FORWARD_PLUS: 'subscriber_enq_forward',
    SUBSCRIBER_ONT_ACKNOWLEDGEMENT: 'ont_acknowledgement'
  },
  WORK_ORDER: {
    CREATE_WORK_ORDER: 'create_work_order'
  }
};
