import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

const API_ACTION_TYPES = {
  SUBMIT_PLAN_PACKAGE: `${STATE_REDUCER_KEY}/SUBMIT_PLAN_PACKAGE`,
  UPDATE_PLAN_STATUS: `${STATE_REDUCER_KEY}/UPDATE_PLAN_STATUS`,
  FETCH_MASTER_PACKAGE_TYPE: `${STATE_REDUCER_KEY}/FETCH_MASTER_PACKAGE_TYPE`,
  FETCH_MASTER_PLAN_TYPE: `${STATE_REDUCER_KEY}/FETCH_MASTER_PLAN_TYPE`,
  FETCH_MASTER_CATEGORY_TYPE: `${STATE_REDUCER_KEY}/FETCH_MASTER_CATEGORY_TYPE`,
  FETCH_MASTER_PACKAGE_PLAN_TYPE: `${STATE_REDUCER_KEY}/FETCH_MASTER_PACKAGE_PLAN_TYPE`,
  FETCH_MASTER_FALLBACK_SPEED: `${STATE_REDUCER_KEY}/FETCH_MASTER_FALLBACK_SPEED`,
  FETCH_MASTER_SPEED_PROFILE: `${STATE_REDUCER_KEY}/FETCH_MASTER_SPEED_PROFILE`,
  FETCH_MASTER_SUBSCRIBER_PROFILE: `${STATE_REDUCER_KEY}/FETCH_MASTER_SUBSCRIBER_PROFILE`,

  FETCH_SERVICE_TYPE_LIST: `${STATE_REDUCER_KEY}/FETCH_SERVICE_TYPE_LIST`,
  FETCH_REVENUE_SHARE_LIST: `${STATE_REDUCER_KEY}/FETCH_REVENUE_SHARE_LIST`,

  FETCH_FUP_LIST: `${STATE_REDUCER_KEY}/FETCH_FUP_LIST`,
  FETCH_SUB_PACKAGE_LIST: `${STATE_REDUCER_KEY}/FETCH_SUB_PACKAGE_LIST`,
  DOWNLOAD_PLAN_PACKAGE_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_PLAN_PACKAGE_CSV`,

  FETCH_PACKAGE_DETAILS_BY_ID: `${STATE_REDUCER_KEY}/FETCH_PACKAGE_DETAILS_BY_ID`,
  SUBMIT_PLAN_SUB_PACKAGE: `${STATE_REDUCER_KEY}/SUBMIT_PLAN_SUB_PACKAGE`,
  UPDATE_PLAN_SUB_PACKAGE: `${STATE_REDUCER_KEY}/UPDATE_PLAN_SUB_PACKAGE`,
  UPDATE_PLAN_PACKAGE: `${STATE_REDUCER_KEY}/UPDATE_PLAN_PACKAGE`,

  FETCH_CORPORATE_SERVICE_TYPE: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_SERVICE_TYPE`,
  FETCH_CORPORATE_SUB_SERVICE_TYPE: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_SUB_SERVICE_TYPE`,
  SUBMIT_CORPORATE_PACKAGE: `${STATE_REDUCER_KEY}/SUBMIT_CORPORATE_PACKAGE`,
  UPDATE_CORPORATE_PACKAGE: `${STATE_REDUCER_KEY}/UPDATE_CORPORATE_PACKAGE`,
  FETCH_CORPORATE_PACKAGE_BY_ID: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_PACKAGE_BY_ID`,
  FETCH_CORPORATE_PACKAGE_LIST: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_PACKAGE_LIST`,
  FETCH_RETAIL_PACKAGE_LIST: `${STATE_REDUCER_KEY}/FETCH_RETAIL_PACKAGE_LIST`,
  FETCH_RETAIL_SERVICE_TYPE: `${STATE_REDUCER_KEY}/FETCH_RETAIL_SERVICE_TYPE`,
  FETCH_SUB_SERVICE_TYPES: `${STATE_REDUCER_KEY}/FETCH_SUB_SERVICE_TYPES`,
  FETCH_PARTNER_TYPE: `${STATE_REDUCER_KEY}/FETCH_PARTNER_TYPE`,
  FETCH_PROVIDER: `${STATE_REDUCER_KEY}/FETCH_PROVIDER`,
  SUBMIT_MAIN_SERVICE: `${STATE_REDUCER_KEY}/SUBMIT_MAIN_SERVICE`,
  SUBMIT_SERVICE_MAPPING: `${STATE_REDUCER_KEY}/SUBMIT_SERVICE_MAPPING`,
  UPDATE_SERVICE_MAPPING: `${STATE_REDUCER_KEY}/UPDATE_SERVICE_MAPPING`,
  FETCH_SERVICE_MAPPINGS: `${STATE_REDUCER_KEY}/FETCH_SERVICE_MAPPINGS`,
  UPDATE_MAIN_SERVICE: `${STATE_REDUCER_KEY}/UPDATE_MAIN_SERVICE`,
  FETCH_MAIN_SERVICES: `${STATE_REDUCER_KEY}/FETCH_MAIN_SERVICES`,
  FETCH_DEFAULT_PACKAGE_TYPE: `${STATE_REDUCER_KEY}/FETCH_DEFAULT_PACKAGE_TYPE`,
  FETCH_SERVICE_CATEGORY_LOOKUP: `${STATE_REDUCER_KEY}/FETCH_SERVICE_CATEGORY_LOOKUP`,
  FETCH_SUB_SERVICE_CATEGORY_LOOKUP: `${STATE_REDUCER_KEY}/FETCH_SUB_SERVICE_CATEGORY_LOOKUP`,
  FETCH_SUB_PACKAGE_TYPE_LOOKUP: `${STATE_REDUCER_KEY}/FETCH_SUB_PACKAGE_TYPE_LOOKUP`,
  SUBMIT_SUB_SERVICE: `${STATE_REDUCER_KEY}/SUBMIT_SUB_SERVICE`,
  UPDATE_SUB_SERVICE: `${STATE_REDUCER_KEY}/UPDATE_SUB_SERVICE`,
  FETCH_SUB_SERVICES: `${STATE_REDUCER_KEY}/FETCH_SUB_SERVICES`,
  FETCH_SUB_SERVICE_BY_ID: `${STATE_REDUCER_KEY}/FETCH_SUB_SERVICE_BY_ID`,
  FETCH_SERVICE_CATEGORY_BY_ID: `${STATE_REDUCER_KEY}/FETCH_SERVICE_CATEGORY_BY_ID`,
  FETCH_SERVICE_TYPES_LOOKUP: `${STATE_REDUCER_KEY}/FETCH_SERVICE_TYPES_LOOKUP`
};

export const ACTION_TYPES = {
  ...API_ACTION_TYPES
};

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const submitPlanPackage = createAction(ACTION_TYPES.SUBMIT_PLAN_PACKAGE);
export const updatePlanStatus = createAction(ACTION_TYPES.UPDATE_PLAN_STATUS);
export const fetchMasterPackageType = createAction(ACTION_TYPES.FETCH_MASTER_PACKAGE_TYPE);
export const fetchMasterPlanType = createAction(ACTION_TYPES.FETCH_MASTER_PLAN_TYPE);
export const fetchMasterCategoryType = createAction(ACTION_TYPES.FETCH_MASTER_CATEGORY_TYPE);
export const fetchMasterPackagePlanType = createAction(ACTION_TYPES.FETCH_MASTER_PACKAGE_PLAN_TYPE);
export const fetchMasterFallbackSpeed = createAction(ACTION_TYPES.FETCH_MASTER_FALLBACK_SPEED);
export const fetchMasterSpeedProfile = createAction(ACTION_TYPES.FETCH_MASTER_SPEED_PROFILE);
export const getSubscriberProfile = createAction(ACTION_TYPES.FETCH_MASTER_SUBSCRIBER_PROFILE);

export const fetchFupList = createAction(ACTION_TYPES.FETCH_FUP_LIST);
export const downloadPackageCsv = createAction(ACTION_TYPES.DOWNLOAD_PLAN_PACKAGE_CSV);

export const fetchserviceTypes = createAction(ACTION_TYPES.FETCH_SERVICE_TYPE_LIST);
export const fetchRevenueShareList = createAction(ACTION_TYPES.FETCH_REVENUE_SHARE_LIST);
export const fetchSubpackageList = createAction(ACTION_TYPES.FETCH_SUB_PACKAGE_LIST);
export const fetchPackageDetailsById = createAction(ACTION_TYPES.FETCH_PACKAGE_DETAILS_BY_ID);
export const submitPlanSubPackage = createAction(ACTION_TYPES.SUBMIT_PLAN_SUB_PACKAGE);
export const updatePlanSubPackage = createAction(ACTION_TYPES.UPDATE_PLAN_SUB_PACKAGE);
export const updatePlanPackage = createAction(ACTION_TYPES.UPDATE_PLAN_PACKAGE);

export const fetchCorporateServiceType = createAction(ACTION_TYPES.FETCH_CORPORATE_SERVICE_TYPE);
export const fetchCorporateSubServiceType = createAction(ACTION_TYPES.FETCH_CORPORATE_SUB_SERVICE_TYPE);
export const submitCorporatePackage = createAction(ACTION_TYPES.SUBMIT_CORPORATE_PACKAGE);
export const updateCorporatePackage = createAction(ACTION_TYPES.UPDATE_CORPORATE_PACKAGE);
export const fetchCorporatePackageById = createAction(ACTION_TYPES.FETCH_CORPORATE_PACKAGE_BY_ID);
export const fetchCorporatePackageList = createAction(ACTION_TYPES.FETCH_CORPORATE_PACKAGE_LIST);
export const fetchRetailPackageList = createAction(ACTION_TYPES.FETCH_RETAIL_PACKAGE_LIST);
export const fetchRetailServiceType = createAction(ACTION_TYPES.FETCH_RETAIL_SERVICE_TYPE);
export const fetchSubServiceType = createAction(ACTION_TYPES.FETCH_SUB_SERVICE_TYPES);
export const fetchPartnerType = createAction(ACTION_TYPES.FETCH_PARTNER_TYPE);
export const fetchProvider = createAction(ACTION_TYPES.FETCH_PROVIDER);
export const submitMainService = createAction(ACTION_TYPES.SUBMIT_MAIN_SERVICE);
export const submitServiceMapping = createAction(ACTION_TYPES.SUBMIT_SERVICE_MAPPING);
export const updateServiceMapping = createAction(ACTION_TYPES.UPDATE_SERVICE_MAPPING);
export const fetchServiceMappings = createAction(ACTION_TYPES.FETCH_SERVICE_MAPPINGS);
export const updateMainService = createAction(ACTION_TYPES.UPDATE_MAIN_SERVICE);
export const fetchMainServices = createAction(ACTION_TYPES.FETCH_MAIN_SERVICES);
export const fetchDefaultPackageType = createAction(ACTION_TYPES.FETCH_DEFAULT_PACKAGE_TYPE);
export const fetchServiceCategoryLookup = createAction(ACTION_TYPES.FETCH_SERVICE_CATEGORY_LOOKUP);
export const fetchSubServiceCategoryLookup = createAction(ACTION_TYPES.FETCH_SUB_SERVICE_CATEGORY_LOOKUP);
export const fetchSubPackageTypeLookup = createAction(ACTION_TYPES.FETCH_SUB_PACKAGE_TYPE_LOOKUP);
export const fetchSubServiceById = createAction(ACTION_TYPES.FETCH_SUB_SERVICE_BY_ID);
export const submitSubService = createAction(ACTION_TYPES.SUBMIT_SUB_SERVICE);
export const updateSubService = createAction(ACTION_TYPES.UPDATE_SUB_SERVICE);
export const fetchSubServices = createAction(ACTION_TYPES.FETCH_SUB_SERVICES);
export const fetchServiceCategoryById = createAction(ACTION_TYPES.FETCH_SERVICE_CATEGORY_BY_ID);
export const fetchServiceTypesLookup = createAction(ACTION_TYPES.FETCH_SERVICE_TYPES_LOOKUP);