import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

const API_ACTION_TYPES = {
  FETCH_AGNP_CORPORATE_INVOICE: `${STATE_REDUCER_KEY}/FETCH_AGNP_CORPORATE_INVOICE`,
  FETCH_AGNP_RETAIL_INVOICE: `${STATE_REDUCER_KEY}/FETCH_AGNP_RETAIL_INVOICE`,
  FETCH_EO_SUBSCRIBER_INVOICE: `${STATE_REDUCER_KEY}/FETCH_EO_SUBSCRIBER_INVOICE`,
  FETCH_LNP_CORPORATE_INVOICE: `${STATE_REDUCER_KEY}/FETCH_LNP_CORPORATE_INVOICE`,
  FETCH_LNP_CORPORATE_OTC_INVOICE: `${STATE_REDUCER_KEY}/FETCH_LNP_CORPORATE_OTC_INVOICE`,
  FETCH_LNP_RETAIL_INVOICE: `${STATE_REDUCER_KEY}/FETCH_LNP_RETAIL_INVOICE`,
  FETCH_MSP_BU_OE_INVOICE: `${STATE_REDUCER_KEY}/FETCH_MSP_BU_OE_INVOICE`,
  FETCH_MSP_CORPORATE_INVOICE: `${STATE_REDUCER_KEY}/FETCH_MSP_CORPORATE_INVOICE`,
  FETCH_ONT_PURCHASE_INVOICE: `${STATE_REDUCER_KEY}/FETCH_ONT_PURCHASE_INVOICE`,
  FETCH_OTT_PROVIDER_INVOICE: `${STATE_REDUCER_KEY}/FETCH_OTT_PROVIDER_INVOICE`,
  FETCH_SUBSCRIBER_BPL_INVOICE: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_BPL_INVOICE`,
  FETCH_SUBSCRIBER_INVOICE_REPORTS: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_INVOICE_REPORTS`
};

export const ACTION_TYPES = {
  ...API_ACTION_TYPES
};

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchAGNPRetailInvoice = createAction(ACTION_TYPES.FETCH_AGNP_RETAIL_INVOICE);

export const fetchAGNPCorporateInvoice = createAction(ACTION_TYPES.FETCH_AGNP_CORPORATE_INVOICE);

export const fetchEOSubscriberInvoice = createAction(ACTION_TYPES.FETCH_EO_SUBSCRIBER_INVOICE);

export const fetchLNPRetailInvoice = createAction(ACTION_TYPES.FETCH_LNP_RETAIL_INVOICE);

export const fetchLNPCorporateInvoice = createAction(ACTION_TYPES.FETCH_LNP_CORPORATE_INVOICE);

export const fetchLNPCorporateOTCInvoice = createAction(ACTION_TYPES.FETCH_LNP_CORPORATE_OTC_INVOICE);

export const fetchMSPBuOeInvoice = createAction(ACTION_TYPES.FETCH_MSP_BU_OE_INVOICE);

export const fetchMSPCorporateInvoice = createAction(ACTION_TYPES.FETCH_MSP_CORPORATE_INVOICE);

export const fetchONTPurchaseInvoice = createAction(ACTION_TYPES.FETCH_ONT_PURCHASE_INVOICE);

export const fetchOTTProviderInvoice = createAction(ACTION_TYPES.FETCH_OTT_PROVIDER_INVOICE);

export const fetchSubscriberBPLInvoice = createAction(ACTION_TYPES.FETCH_SUBSCRIBER_BPL_INVOICE);

export const fetchSubscriberInvoiceReports = createAction(ACTION_TYPES.FETCH_SUBSCRIBER_INVOICE_REPORTS);
