import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

const API_ACTION_TYPES = {
  FETCH_FRANCHISEE_CORPORATE_INVOICES: `${STATE_REDUCER_KEY}/FETCH_FRANCHISEE_CORPORATE_INVOICES`,
  FETCH_OTC_APPROVAL: `${STATE_REDUCER_KEY}/FETCH_OTC_APPROVAL`,
  FETCH_SUBSCRIBER_DETAILS: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_DETAILS`,
  FETCH_LNP_PARTNER_FINANCE: `${STATE_REDUCER_KEY}/FETCH_LNP_PARTNER_FINANCE`,
  FETCH_DISBURSEMENT: `${STATE_REDUCER_KEY}/FETCH_DISBURSEMENT`,
  FETCH_LNP_SUMMARY_LOCATION: `${STATE_REDUCER_KEY}/FETCH_LNP_SUMMARY_LOCATION`,
  FETCH_LNP_CREDIT_NOTES: `${STATE_REDUCER_KEY}/FETCH_LNP_CREDIT_NOTES`,
  FETCH_LNP_CUMULATIVE_SUMMARY: `${STATE_REDUCER_KEY}/FETCH_LNP_CUMULATIVE_SUMMARY`
};

export const ACTION_TYPES = {
  ...API_ACTION_TYPES
};

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchFranchiseeCorporateInvoices = createAction(ACTION_TYPES.FETCH_FRANCHISEE_CORPORATE_INVOICES);
export const fetchOTCApproval = createAction(ACTION_TYPES.FETCH_OTC_APPROVAL);
export const fetchSubscriberDetails = createAction(ACTION_TYPES.FETCH_SUBSCRIBER_DETAILS);
export const fetchLNPPartnerFinance = createAction(ACTION_TYPES.FETCH_LNP_PARTNER_FINANCE);
export const fetchDisbursement = createAction(ACTION_TYPES.FETCH_DISBURSEMENT);
export const fetchLNPSummaryLocation = createAction(ACTION_TYPES.FETCH_LNP_SUMMARY_LOCATION);
export const fetchLNPCreditNotes = createAction(ACTION_TYPES.FETCH_LNP_CREDIT_NOTES);
export const fetchLNPCumulativeSummary = createAction(ACTION_TYPES.FETCH_LNP_CUMULATIVE_SUMMARY);
