import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

const API_ACTION_TYPES = {
  FETCH_REVENUE_CONTROL: `${STATE_REDUCER_KEY}/FETCH_REVENUE_CONTROL`,
  FETCH_GSTR2A_PARTNERS: `${STATE_REDUCER_KEY}/FETCH_GSTR2A_PARTNERS`,
  FETCH_GSTR1_RETAIL_CORPORATE: `${STATE_REDUCER_KEY}/FETCH_GSTR1_RETAIL_CORPORATE`,
  FETCH_SUB_INVOICE_B2B: `${STATE_REDUCER_KEY}/FETCH_SUB_INVOICE_B2B`,
  FETCH_SUB_INVOICE_B2C_RETAILS: `${STATE_REDUCER_KEY}/FETCH_SUB_INVOICE_B2C_RETAILS`,
  FETCH_SUB_INVOICE_B2B_CORPORATE: `${STATE_REDUCER_KEY}/FETCH_SUB_INVOICE_B2B_CORPORATE`,
  FETCH_SUB_INVOICE_B2C_CORPORATE: `${STATE_REDUCER_KEY}/FETCH_SUB_INVOICE_B2C_CORPORATE`,
  FETCH_NLD_REPORT: `${STATE_REDUCER_KEY}/FETCH_NLD_REPORT`,
  FETCH_AGR_REPORT: `${STATE_REDUCER_KEY}/FETCH_AGR_REPORT`
};

export const ACTION_TYPES = {
  ...API_ACTION_TYPES
};

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchRevenueControl = createAction(ACTION_TYPES.FETCH_REVENUE_CONTROL);
export const fetchGstr2aPartners = createAction(ACTION_TYPES.FETCH_GSTR2A_PARTNERS);
export const fetchGstr1RetailCorporate = createAction(ACTION_TYPES.FETCH_GSTR1_RETAIL_CORPORATE);
export const fetchSubInvoiceB2B = createAction(ACTION_TYPES.FETCH_SUB_INVOICE_B2B);
export const fetchSubInvoiceB2CRetails = createAction(ACTION_TYPES.FETCH_SUB_INVOICE_B2C_RETAILS);
export const fetchSubInvoiceB2BCorporate = createAction(ACTION_TYPES.FETCH_SUB_INVOICE_B2B_CORPORATE);
export const fetchSubInvoiceB2CCorporate = createAction(ACTION_TYPES.FETCH_SUB_INVOICE_B2C_CORPORATE);
export const fetchNldReport = createAction(ACTION_TYPES.FETCH_NLD_REPORT);
export const fetchAgrReport = createAction(ACTION_TYPES.FETCH_AGR_REPORT);
