import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

const API_ACTION_TYPES = {
  FETCH_ACCOUNT_TOPUP_RECEIPT_DETAILS: `${STATE_REDUCER_KEY}/FETCH_ACCOUNT_TOPUP_RECEIPT_DETAILS`,
  FETCH_SUBSCRIBER_ADVANCED_TOPUP_VOUCHER: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_ADVANCED_TOPUP_VOUCHER`,
  FETCH_TRANSFERRED_TO_SUBSCRIBER: `${STATE_REDUCER_KEY}/FETCH_TRANSFERRED_TO_SUBSCRIBER`,
  FETCH_REVENUE: `${STATE_REDUCER_KEY}/FETCH_REVENUE`,
  FETCH_GST_WALLET: `${STATE_REDUCER_KEY}/FETCH_GST_WALLET`,
  FETCH_FINANCE_TRANSACTIONS: `${STATE_REDUCER_KEY}/FETCH_FINANCE_TRANSACTIONS`,
  FETCH_SUBSCRIBER_FINANCE: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_FINANCE`,
  FETCH_DISBURSEMENT_DETAILS: `${STATE_REDUCER_KEY}/FETCH_DISBURSEMENT_DETAILS`,
  FETCH_SUBSCRIBER_INVOICE: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_INVOICE`,
  FETCH_MONTHLY_LNP_INVOICE: `${STATE_REDUCER_KEY}/FETCH_MONTHLY_LNP_INVOICE`,
  FETCH_ONLINE_TRANSACTION_HISTORY: `${STATE_REDUCER_KEY}/FETCH_ONLINE_TRANSACTION_HISTORY`,
  FETCH_SUBSCRIBER_ONLINE_RECHARGE: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_ONLINE_RECHARGE`,
  SUBMIT_ONLINE_TOPUP_RECHARGE: `${STATE_REDUCER_KEY}/SUBMIT_ONLINE_TOPUP_RECHARGE`,
  FETCH_ACCOUNT_BALANCE: `${STATE_REDUCER_KEY}/FETCH_ACCOUNT_BALANCE`
};

export const ACTION_TYPES = {
  ...API_ACTION_TYPES
};

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchAccountTopupReceiptDetails = createAction(ACTION_TYPES.FETCH_ACCOUNT_TOPUP_RECEIPT_DETAILS);
export const fetchSubscriberAdvancedTopupVoucher = createAction(ACTION_TYPES.FETCH_SUBSCRIBER_ADVANCED_TOPUP_VOUCHER);
export const fetchTransferredToSubscriber = createAction(ACTION_TYPES.FETCH_TRANSFERRED_TO_SUBSCRIBER);
export const fetchRevenue = createAction(ACTION_TYPES.FETCH_REVENUE);
export const fetchGSTWallet = createAction(ACTION_TYPES.FETCH_GST_WALLET);
export const fetchFinanceTransactions = createAction(ACTION_TYPES.FETCH_FINANCE_TRANSACTIONS);
export const fetchSubscriberFinance = createAction(ACTION_TYPES.FETCH_SUBSCRIBER_FINANCE);
export const fetchDisbursementDetails = createAction(ACTION_TYPES.FETCH_DISBURSEMENT_DETAILS);
export const fetchSubscriberInvoice = createAction(ACTION_TYPES.FETCH_SUBSCRIBER_INVOICE);
export const fetchMonthlyLNPInvoice = createAction(ACTION_TYPES.FETCH_MONTHLY_LNP_INVOICE);
export const fetchOnlineTransactionHistory = createAction(ACTION_TYPES.FETCH_ONLINE_TRANSACTION_HISTORY);
export const fetchSubscriberOnlineRecharge = createAction(ACTION_TYPES.FETCH_SUBSCRIBER_ONLINE_RECHARGE);
export const submitOnlineTopupRecharge = createAction(ACTION_TYPES.SUBMIT_ONLINE_TOPUP_RECHARGE);
export const fetchAccountBalance = createAction(ACTION_TYPES.FETCH_ACCOUNT_BALANCE);
