import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

const API_ACTION_TYPES = {
  FETCH_AGNP_PARTNER_FINANCE_CORPORATE: `${STATE_REDUCER_KEY}/FETCH_AGNP_PARTNER_FINANCE_CORPORATE`,
  FETCH_CORPORATE_SUBSCRIBER_ONLINE_RECHARGE: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_SUBSCRIBER_ONLINE_RECHARGE`,
  FETCH_LNP_ONLINE_RECHARGE: `${STATE_REDUCER_KEY}/FETCH_LNP_ONLINE_RECHARGE`,
  FETCH_LNP_PARTNER_FINANCE_CORPORATE: `${STATE_REDUCER_KEY}/FETCH_LNP_PARTNER_FINANCE_CORPORATE`,
  FETCH_ONE_PLUS_ONE: `${STATE_REDUCER_KEY}/FETCH_ONE_PLUS_ONE`,
  FETCH_PARTNER_ACCOUNT_BALANCE: `${STATE_REDUCER_KEY}/FETCH_PARTNER_ACCOUNT_BALANCE`,
  FETCH_PARTNER_ACCOUNT_DISBURSEMENT: `${STATE_REDUCER_KEY}/FETCH_PARTNER_ACCOUNT_DISBURSEMENT`,
  FETCH_PARTNER_ACCOUNT_TOPUP_RECEIPT: `${STATE_REDUCER_KEY}/FETCH_PARTNER_ACCOUNT_TOPUP_RECEIPT`,
  FETCH_PARTNER_FINANCE: `${STATE_REDUCER_KEY}/FETCH_PARTNER_FINANCE`,
  FETCH_SUBSCRIBER_ONLINE_RECHARGE: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_ONLINE_RECHARGE`
};

export const ACTION_TYPES = {
  ...API_ACTION_TYPES
};

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchAGNPPartnerFinanceCorporate = createAction(ACTION_TYPES.FETCH_AGNP_PARTNER_FINANCE_CORPORATE);
export const fetchCorporateSubscriberOnlineRecharge = createAction(
  ACTION_TYPES.FETCH_CORPORATE_SUBSCRIBER_ONLINE_RECHARGE
);
export const fetchLNPOnlineRecharge = createAction(ACTION_TYPES.FETCH_LNP_ONLINE_RECHARGE);
export const fetchLNPPartnerFinanceCorporate = createAction(ACTION_TYPES.FETCH_LNP_PARTNER_FINANCE_CORPORATE);
export const fetchOnePlusOne = createAction(ACTION_TYPES.FETCH_ONE_PLUS_ONE);
export const fetchPartnerAccountBalance = createAction(ACTION_TYPES.FETCH_PARTNER_ACCOUNT_BALANCE);
export const fetchPartnerAccountDisbursement = createAction(ACTION_TYPES.FETCH_PARTNER_ACCOUNT_DISBURSEMENT);
export const fetchPartnerAccountTopupReceipt = createAction(ACTION_TYPES.FETCH_PARTNER_ACCOUNT_TOPUP_RECEIPT);
export const fetchPartnerFinance = createAction(ACTION_TYPES.FETCH_PARTNER_FINANCE);
export const fetchSubscriberOnlineRecharge = createAction(ACTION_TYPES.FETCH_SUBSCRIBER_ONLINE_RECHARGE);
