import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

const API_ACTION_TYPES = {
  FETCH_PRIORITIES: `${STATE_REDUCER_KEY}/FETCH_PRIORITIES`,
  FETCH_ISSUE_TYPES: `${STATE_REDUCER_KEY}/FETCH_ISSUE_TYPES`,
  FETCH_CUSTOMER_TYPES: `${STATE_REDUCER_KEY}/FETCH_CUSTOMER_TYPES`,
  FETCH_CUSTOMER_SUBTYPES: `${STATE_REDUCER_KEY}/FETCH_CUSTOMER_SUBTYPES`,
  SUBMIT_TICKET: `${STATE_REDUCER_KEY}/SUBMIT_TICKET`,
  UPLOAD_TICKET_DOCUMENT: `${STATE_REDUCER_KEY}/UPLOAD_TICKET_DOCUMENT`,
  CUSTOMER_SUBMIT_TICKET: `${STATE_REDUCER_KEY}/CUSTOMER_SUBMIT_TICKET`,
  FETCH_ATTACHMENT: `${STATE_REDUCER_KEY}/FETCH_ATTACHMENT`,
  FETCH_INBOX_TICKETS: `${STATE_REDUCER_KEY}/FETCH_INBOX_TICKETS`,
  FETCH_OUTBOX_TICKETS: `${STATE_REDUCER_KEY}/FETCH_OUTBOX_TICKETS`,
  FETCH_TICKET_LIST: `${STATE_REDUCER_KEY}/FETCH_TICKET_LIST`,
  FETCH_VISIBILITY_PERMISSION: `${STATE_REDUCER_KEY}/FETCH_VISIBILITY_PERMISSION`,
  SUBMIT_COMMENT: `${STATE_REDUCER_KEY}/SUBMIT_COMMENT`,
  FETCH_UPDATE_STATE: `${STATE_REDUCER_KEY}/FETCH_UPDATE_STATE`,
  DELETE_ATTACHMENT: `${STATE_REDUCER_KEY}/DELETE_ATTACHMENT`,
  FETCH_ROLE_NAME: `${STATE_REDUCER_KEY}/FETCH_ROLE_NAME`,
  FORWARD_TICKET: `${STATE_REDUCER_KEY}/FORWARD_TICKET`,
  FETCH_FILE_URL: `${STATE_REDUCER_KEY}/FETCH_FILE_URL`,
  FETCH_SUBSCRIBER_LIST: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_LIST`,
  RETURN_TICKET: `${STATE_REDUCER_KEY}/RETURN_TICKET`,
  SUBMIT_CRM_MAPPING: `${STATE_REDUCER_KEY}/SUBMIT_CRM_MAPPING`,
  UPDATE_CRM_MAPPING: `${STATE_REDUCER_KEY}/UPDATE_CRM_MAPPING`,
  FETCH_CRM_TEMPLATE: `${STATE_REDUCER_KEY}/FETCH_CRM_TEMPLATE`,
  PIN_TICKET: `${STATE_REDUCER_KEY}/PIN_TICKET`,
  DOWNLOAD_INBOX_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_INBOX_CSV`,
  DOWNLOAD_OUTBOX_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_OUTBOX_CSV`,
  RETURN_TO_CUSTODIAN: `${STATE_REDUCER_KEY}/RETURN_TO_CUSTODIAN`,
  FETCH_GOVT_CUSTOMERS: `${STATE_REDUCER_KEY}/FETCH_GOVT_CUSTOMERS`,
  REOPEN_TICKET: `${STATE_REDUCER_KEY}/REOPEN_TICKET`,
  DELETE_CRM_TEMPLATE: `${STATE_REDUCER_KEY}/DELETE_CRM_TEMPLATE`,
  CLOSED_TICKET_NOTIFICATION: `${STATE_REDUCER_KEY}/CLOSED_TICKET_NOTIFICATION`,
  FETCH_ROLE_BY_TICKET_ID: `${STATE_REDUCER_KEY}/FETCH_ROLE_BY_TICKET_ID`,
  FETCH_SUBSCRIBER_BY_NUMBER: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_BY_NUMBER`,
  FETCH_PREVIOUS_EMPLOYEE: `${STATE_REDUCER_KEY}/FETCH_PREVIOUS_EMPLOYEE`,
  TAKEOVER_SEARCH: `${STATE_REDUCER_KEY}/TAKEOVER_SEARCH`,
  FETCH_DASHBOARD_TICKET_SUMMARY: `${STATE_REDUCER_KEY}/FETCH_DASHBOARD_TICKET_SUMMARY`,
  FETCH_CUSTOMER_TYPE_BREAKDOWN: `${STATE_REDUCER_KEY}/FETCH_CUSTOMER_TYPE_BREAKDOWN`,
  FETCH_TOP_10_ISSUES: `${STATE_REDUCER_KEY}/FETCH_TOP_10_ISSUES`,
  FETCH_SUBJECT_TYPE_BREAKDOWN: `${STATE_REDUCER_KEY}/FETCH_SUBJECT_TYPE_BREAKDOWN`,
  FETCH_DISTRICT_WISE_COMPLAINTS: `${STATE_REDUCER_KEY}/FETCH_DISTRICT_WISE_COMPLAINTS`,
  FETCH_PERFORMANCE_KPI: `${STATE_REDUCER_KEY}/FETCH_PERFORMANCE_KPI`,
  FETCH_RESOLUTION_PERFORMANCE: `${STATE_REDUCER_KEY}/FETCH_RESOLUTION_PERFORMANCE`,
  FETCH_MONTHLY_SUMMARY: `${STATE_REDUCER_KEY}/FETCH_MONTHLY_SUMMARY`,
  FETCH_LONG_PENDING: `${STATE_REDUCER_KEY}/FETCH_LONG_PENDING`,
  FETCH_LONG_PENDING_SUMMARY: `${STATE_REDUCER_KEY}/FETCH_LONG_PENDING_SUMMARY`,
  FETCH_LONG_PENDING_LIST: `${STATE_REDUCER_KEY}/FETCH_LONG_PENDING_LIST`,
  FETCH_ALL_TICKETS_LIST: `${STATE_REDUCER_KEY}/FETCH_ALL_TICKETS_LIST`,
  FETCH_NO_CUSTODIAN_TICKET_COUNT: `${STATE_REDUCER_KEY}/FETCH_NO_CUSTODIAN_TICKET_COUNT`
};

export const ACTION_TYPES = {
  ...API_ACTION_TYPES
};

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchPriorities = createAction(ACTION_TYPES.FETCH_PRIORITIES);
export const fetchIssueTypes = createAction(ACTION_TYPES.FETCH_ISSUE_TYPES);
export const fetchCustomerTypes = createAction(ACTION_TYPES.FETCH_CUSTOMER_TYPES);
export const fetchCustomerSubTypes = createAction(ACTION_TYPES.FETCH_CUSTOMER_SUBTYPES);
export const submitTicket = createAction(ACTION_TYPES.SUBMIT_TICKET);
export const uploadTicketDocument = createAction(ACTION_TYPES.UPLOAD_TICKET_DOCUMENT);
export const customerSubmitTicket = createAction(ACTION_TYPES.CUSTOMER_SUBMIT_TICKET);
export const fetchAttachment = createAction(ACTION_TYPES.FETCH_ATTACHMENT);
export const fetchInboxTickets = createAction(ACTION_TYPES.FETCH_INBOX_TICKETS);
export const fetchOutboxTickets = createAction(ACTION_TYPES.FETCH_OUTBOX_TICKETS);
export const fetchTicketList = createAction(ACTION_TYPES.FETCH_TICKET_LIST);
export const fetchVisibilityPermission = createAction(ACTION_TYPES.FETCH_VISIBILITY_PERMISSION);
export const submitComment = createAction(ACTION_TYPES.SUBMIT_COMMENT);
export const fetchUpdateState = createAction(ACTION_TYPES.FETCH_UPDATE_STATE);
export const deleteAttachment = createAction(ACTION_TYPES.DELETE_ATTACHMENT);
export const fetchRoleName = createAction(ACTION_TYPES.FETCH_ROLE_NAME);
export const forwardTicket = createAction(ACTION_TYPES.FORWARD_TICKET);
export const fetchFileUrl = createAction(ACTION_TYPES.FETCH_FILE_URL);
export const fetchSubscriberList = createAction(ACTION_TYPES.FETCH_SUBSCRIBER_LIST);
export const returnTicket = createAction(ACTION_TYPES.RETURN_TICKET);
export const submitCrmMapping = createAction(ACTION_TYPES.SUBMIT_CRM_MAPPING);
export const updateCrmMapping = createAction(ACTION_TYPES.UPDATE_CRM_MAPPING);
export const fetchCrmTemplate = createAction(ACTION_TYPES.FETCH_CRM_TEMPLATE);
export const pinTicket = createAction(ACTION_TYPES.PIN_TICKET);
export const downloadInboxCsv = createAction(ACTION_TYPES.DOWNLOAD_INBOX_CSV);
export const downloadOutboxCsv = createAction(ACTION_TYPES.DOWNLOAD_OUTBOX_CSV);
export const returnToCustodian = createAction(ACTION_TYPES.RETURN_TO_CUSTODIAN);
export const fetchGovtCustomers = createAction(ACTION_TYPES.FETCH_GOVT_CUSTOMERS);
export const reopenTicket = createAction(ACTION_TYPES.REOPEN_TICKET);
export const deleteCrmTemplate = createAction(ACTION_TYPES.DELETE_CRM_TEMPLATE);
export const closedTicketNotification = createAction(ACTION_TYPES.CLOSED_TICKET_NOTIFICATION);
export const fetchRoleByTicketId = createAction(ACTION_TYPES.FETCH_ROLE_BY_TICKET_ID);
export const fetchSubscriberByNumber = createAction(ACTION_TYPES.FETCH_SUBSCRIBER_BY_NUMBER);
export const fetchPreviousEmployee = createAction(ACTION_TYPES.FETCH_PREVIOUS_EMPLOYEE);
export const takeoverSearch = createAction(ACTION_TYPES.TAKEOVER_SEARCH);
export const fetchDashboardTicketSummary = createAction(ACTION_TYPES.FETCH_DASHBOARD_TICKET_SUMMARY);
export const fetchCustomerTypeBreakdown = createAction(ACTION_TYPES.FETCH_CUSTOMER_TYPE_BREAKDOWN);
export const fetchTop10Issues = createAction(ACTION_TYPES.FETCH_TOP_10_ISSUES);
export const fetchSubjectTypeBreakdown = createAction(ACTION_TYPES.FETCH_SUBJECT_TYPE_BREAKDOWN);
export const fetchDistrictWiseComplaints = createAction(ACTION_TYPES.FETCH_DISTRICT_WISE_COMPLAINTS);
export const fetchPerformanceKpi = createAction(ACTION_TYPES.FETCH_PERFORMANCE_KPI);
export const fetchResolutionPerformance = createAction(ACTION_TYPES.FETCH_RESOLUTION_PERFORMANCE);
export const fetchMonthlySummary = createAction(ACTION_TYPES.FETCH_MONTHLY_SUMMARY);
export const fetchLongPending = createAction(ACTION_TYPES.FETCH_LONG_PENDING);
export const fetchLongPendingSummary = createAction(ACTION_TYPES.FETCH_LONG_PENDING_SUMMARY);
export const fetchLongPendingList = createAction(ACTION_TYPES.FETCH_LONG_PENDING_LIST);
export const fetchAllTicketsList = createAction(ACTION_TYPES.FETCH_ALL_TICKETS_LIST);
export const fetchNoCustodianTicketCount = createAction(ACTION_TYPES.FETCH_NO_CUSTODIAN_TICKET_COUNT)
