import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

const API_ACTION_TYPES = {
  FETCH_PARTNER_STAT_CARDS: `${STATE_REDUCER_KEY}/FETCH_PARTNER_STAT_CARDS`,
  FETCH_PARTNER_SUMMARY_CARDS: `${STATE_REDUCER_KEY}/FETCH_PARTNER_SUMMARY_CARDS`,
  FETCH_PARTNER_ONBOARDING_EFFICIENCY: `${STATE_REDUCER_KEY}/FETCH_PARTNER_ONBOARDING_EFFICIENCY`,
  FETCH_PARTNER_LONG_PENDING_NOT_ONBOARDED: `${STATE_REDUCER_KEY}/FETCH_PARTNER_LONG_PENDING_NOT_ONBOARDED`,
  FETCH_PARTNER_LONG_PENDING_LINK_NOT_ESTABLISHED: `${STATE_REDUCER_KEY}/FETCH_PARTNER_LONG_PENDING_LINK_NOT_ESTABLISHED`,
  FETCH_PARTNER_ENQUIRY_POSITION: `${STATE_REDUCER_KEY}/FETCH_PARTNER_ENQUIRY_POSITION`,
  FETCH_PARTNER_DISTRICT_SUMMARY: `${STATE_REDUCER_KEY}/FETCH_PARTNER_DISTRICT_SUMMARY`,
  FETCH_PARTNER_ACTIVE_LIST: `${STATE_REDUCER_KEY}/FETCH_PARTNER_ACTIVE_LIST`,
  DOWNLOAD_PARTNER_ACTIVE_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_PARTNER_ACTIVE_CSV`
};

export const ACTION_TYPES = {
  ...API_ACTION_TYPES
};

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchPartnerStatCards = createAction(ACTION_TYPES.FETCH_PARTNER_STAT_CARDS);
export const fetchPartnerSummaryCards = createAction(ACTION_TYPES.FETCH_PARTNER_SUMMARY_CARDS);
export const fetchPartnerOnboardingEfficiency = createAction(ACTION_TYPES.FETCH_PARTNER_ONBOARDING_EFFICIENCY);
export const fetchPartnerLongPendingNotOnboarded = createAction(ACTION_TYPES.FETCH_PARTNER_LONG_PENDING_NOT_ONBOARDED);
export const fetchPartnerLongPendingLinkNotEstablished = createAction(
  ACTION_TYPES.FETCH_PARTNER_LONG_PENDING_LINK_NOT_ESTABLISHED
);
export const fetchPartnerEnquiryPosition = createAction(ACTION_TYPES.FETCH_PARTNER_ENQUIRY_POSITION);
export const fetchPartnerDistrictSummary = createAction(ACTION_TYPES.FETCH_PARTNER_DISTRICT_SUMMARY);
export const fetchPartnerActiveList = createAction(ACTION_TYPES.FETCH_PARTNER_ACTIVE_LIST);
export const downloadPartnerActiveCsv = createAction(ACTION_TYPES.DOWNLOAD_PARTNER_ACTIVE_CSV);
