import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

const API_ACTION_TYPES = {
  FETCH_INVENTORY_SUMMARY_CARDS: `${STATE_REDUCER_KEY}/FETCH_INVENTORY_SUMMARY_CARDS`,
  FETCH_INVENTORY_STOCK_TYPE_COUNT: `${STATE_REDUCER_KEY}/FETCH_INVENTORY_STOCK_TYPE_COUNT`,
  FETCH_INVENTORY_DEVICE_LIST: `${STATE_REDUCER_KEY}/FETCH_INVENTORY_DEVICE_LIST`,
  FETCH_INVENTORY_DISTRICT_BREAKDOWN: `${STATE_REDUCER_KEY}/FETCH_INVENTORY_DISTRICT_BREAKDOWN`,
  FETCH_INVENTORY_WARRANTY_ALERTS: `${STATE_REDUCER_KEY}/FETCH_INVENTORY_WARRANTY_ALERTS`,
  FETCH_INVENTORY_REQUEST_PIPELINE: `${STATE_REDUCER_KEY}/FETCH_INVENTORY_REQUEST_PIPELINE`,
  FETCH_INVENTORY_RECENT_ACTIVITY: `${STATE_REDUCER_KEY}/FETCH_INVENTORY_RECENT_ACTIVITY`
};

export const ACTION_TYPES = {
  ...API_ACTION_TYPES
};

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchInventorySummaryCards = createAction(ACTION_TYPES.FETCH_INVENTORY_SUMMARY_CARDS);
export const fetchInventoryStockTypeCount = createAction(ACTION_TYPES.FETCH_INVENTORY_STOCK_TYPE_COUNT);
export const fetchInventoryDeviceList = createAction(ACTION_TYPES.FETCH_INVENTORY_DEVICE_LIST);
export const fetchInventoryDistrictBreakdown = createAction(ACTION_TYPES.FETCH_INVENTORY_DISTRICT_BREAKDOWN);
export const fetchInventoryWarrantyAlerts = createAction(ACTION_TYPES.FETCH_INVENTORY_WARRANTY_ALERTS);
export const fetchInventoryRequestPipeline = createAction(ACTION_TYPES.FETCH_INVENTORY_REQUEST_PIPELINE);
export const fetchInventoryRecentActivity = createAction(ACTION_TYPES.FETCH_INVENTORY_RECENT_ACTIVITY);
