import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

const API_ACTION_TYPES = {
  DISTRIBUTOR_FIELD_FETCH: `${STATE_REDUCER_KEY}/FETCH_DISTRIBUTOR-FIELD`,
  ONBOARDING_BASIC_DETAILS_SUBMIT: `${STATE_REDUCER_KEY}/SUBMIT_ONBOARDING_BASIC_DETAILS`,
  ONBOARDING_AGREEMENT_DETAILS_SUBMIT: `${STATE_REDUCER_KEY}/SUBMIT_ONBOARDING_AGREEMENT_DETAILS`,
  ONBOARDING_BANK_DETAILS_SUBMIT: `${STATE_REDUCER_KEY}/SUBMIT_ONBOARDING_BANK_DETAILS`,
  ONBOARDING_KYC_GST_DETAILS_SUBMIT: `${STATE_REDUCER_KEY}/SUBMIT_ONBOARDING_KYC_GST_DETAILS`,
  ONBOARDING_SUPPORTING_DOCUMENTS_SUBMIT: `${STATE_REDUCER_KEY}/SUBMIT_ONBOARDING_SUPPORTING_DOCUMENTS`,
  ONBOARDING_SINGLE_DOCUMENT_SUBMIT: `${STATE_REDUCER_KEY}/SUBMIT_ONBOARDING_SINGLE_DOCUMENT`,
  ONBOARDING_GST_DETAILS_SEARCH: `${STATE_REDUCER_KEY}/SEARCH_ONBOARDING_GST_DETAILS`,
  LNP_PARTNERS_LIST_FETCH: `${STATE_REDUCER_KEY}/FETCH_LNP_PARTNERS_LIST`,
  LNP_PARTNER_STATUS_DROPDOWN_FETCH: `${STATE_REDUCER_KEY}/FETCH_LNP_PARTNER_STATUS_DROPDOWN`,
  LNP_PARTNER_UPDATE: `${STATE_REDUCER_KEY}/UPDATE_LNP_PARTNER`,
  AGNP_PARTNERS_LIST_FETCH: `${STATE_REDUCER_KEY}/FETCH_AGNP_PARTNERS_LIST`,
  AGNP_PARTNER_UPDATE: `${STATE_REDUCER_KEY}/UPDATE_AGNP_PARTNER`,
  ONBOARDING_POP_NAME_FETCH: `${STATE_REDUCER_KEY}/FETCH_ONBOARDING_POP_NAME`,
  ONBOARDING_PINCODE_FETCH: `${STATE_REDUCER_KEY}/FETCH_ONBOARDING_PINCODE`,
  ONBOARDING_POSTOFFICE_FETCH: `${STATE_REDUCER_KEY}/FETCH_ONBOARDING_POSTOFFICE`,
  ONBOARDING_IFSC_DETAILS_FETCH: `${STATE_REDUCER_KEY}/FETCH_ONBOARDING_IFSC_DETAILS`,
  ONBOARDING_COMPANY_NATURE_FETCH: `${STATE_REDUCER_KEY}/FETCH_ONBOARDING_COMPANY_NATURE`,
  ONBOARDING_BANK_ACCOUNT_TYPE_FETCH: `${STATE_REDUCER_KEY}/FETCH_ONBOARDING_BANK_ACCOUNT_TYPE`,
  ONBOARDING_SHARE_PLAN_FETCH: `${STATE_REDUCER_KEY}/FETCH_ONBOARDING_SHARE_PLAN`,
  ONBOARDING_VLAN_MAPPING_DATA_FETCH: `${STATE_REDUCER_KEY}/FETCH_ONBOARDING_VLAN_MAPPING_DATA`,
  ONBOARDING_VLAN_MAPPING_SUBMIT: `${STATE_REDUCER_KEY}/SUBMIT_ONBOARDING_VLAN_MAPPING`,
  ONBOARDING_VLAN_MAPPING_UPDATE: `${STATE_REDUCER_KEY}/UPDATE_ONBOARDING_VLAN_MAPPING`,
  ONBOARDING_VLAN_REQUEST_DATA_FETCH: `${STATE_REDUCER_KEY}/FETCH_ONBOARDING_VLAN_REQUEST_DATA`,
  ONBOARDING_VLAN_REQUEST_SUBMIT: `${STATE_REDUCER_KEY}/SUBMIT_ONBOARDING_VLAN_REQUEST`,
  FETCH_VLAN_TYPE_LIST: `${STATE_REDUCER_KEY}/FETCH_VLAN_TYPE_LIST`,
  FETCH_VLAN_PARTNER_LIST: `${STATE_REDUCER_KEY}/FETCH_VLAN_PARTNER_LIST`,
  FETCH_ONBOARDING_DETAILS: `${STATE_REDUCER_KEY}/FETCH_ONBOARDING_DETAILS`,
  FETCH_PARTNER_ENQUIRY: `${STATE_REDUCER_KEY}/FETCH_PARTNER_ENQUIRY`,
  ONBOARDING_FINAL_SUBMIT: `${STATE_REDUCER_KEY}/SUBMIT_ONBOARDING_FINAL`,
  FETCH_SINGLE_ONBOARDING_DATA: `${STATE_REDUCER_KEY}/FETCH_SINGLE_ONBOARDING_DATA`,
  RESET_PASSWORD: `${STATE_REDUCER_KEY}/RESET_PASSWORD`,
  DOWNLOAD_AGNP_LIST_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_AGNP_LIST_CSV`,
  ADD_SERVICE_AREA: `${STATE_REDUCER_KEY}/ADD_SERVICE_AREA`,
  FETCH_OLT_DEVICE_LIST: `${STATE_REDUCER_KEY}/FETCH_OLT_DEVICE_LIST`,
  FILE_STORAGE_UPLOAD: `${STATE_REDUCER_KEY}/FILE_STORAGE_UPLOAD`,
  FILE_STORAGE_DELETE: `${STATE_REDUCER_KEY}/FILE_STORAGE_DELETE`,
  FILE_STORAGE_VIEW_URL: `${STATE_REDUCER_KEY}/FILE_STORAGE_VIEW_URL`,
  ONBOARDING_DOCUMENT_DELETE: `${STATE_REDUCER_KEY}/ONBOARDING_DOCUMENT_DELETE`,
  PARTNERS_FETCH_ALL: `${STATE_REDUCER_KEY}/FETCH_PARTNERS_ALL`,
  FETCH_PARTNER_DETAILS_BY_ID: `${STATE_REDUCER_KEY}/FETCH_PARTNER_DETAILS_BY_ID`,
  UPDATE_PARTNER_DETAILS: `${STATE_REDUCER_KEY}/UPDATE_PARTNER_DETAILS`,
  FETCH_LINK_TYPE_OPTIONS: `${STATE_REDUCER_KEY}/FETCH_LINK_TYPE_OPTIONS`,
  FETCH_LINK_ESTABLISHMENT_STATUS_OPTIONS: `${STATE_REDUCER_KEY}/FETCH_LINK_ESTABLISHMENT_STATUS_OPTIONS`,
  FETCH_FRC_RECEIVED_OPTIONS: `${STATE_REDUCER_KEY}/FETCH_FRC_RECEIVED_OPTIONS`,
  DOWNLOAD_PARTNER_LIST_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_PARTNER_LIST_CSV`,
  DOWNLOAD_PARTNER_ENQUIRY_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_PARTNER_ENQUIRY_CSV`,
  DOWNLOAD_VLAN_MAPPINGS_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_VLAN_MAPPINGS_CSV`,
  FETCH_PARTNER_FORWARD_USERS: `${STATE_REDUCER_KEY}/FETCH_PARTNER_FORWARD_USERS`,
  FORWARD_PARTNER_ENQUIRY: `${STATE_REDUCER_KEY}/FORWARD_PARTNER_ENQUIRY`,
  FORWARD_AGNP_ENQUIRY: `${STATE_REDUCER_KEY}/FORWARD_AGNP_ENQUIRY`,
  ASSIGN_ENQUIRY: `${STATE_REDUCER_KEY}/ASSIGN_ENQUIRY`,
  ASSIGN_ENQUIRY_TO_PREVIOUS_USER: `${STATE_REDUCER_KEY}/ASSIGN_ENQUIRY_TO_PREVIOUS_USER`,
  ONBOARDING_POP_UPDATE: `${STATE_REDUCER_KEY}/UPDATE_ONBOARDING_POP`
};

export const ACTION_TYPES = {
  ...API_ACTION_TYPES
};

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchDistributorField = createAction(ACTION_TYPES.DISTRIBUTOR_FIELD_FETCH);
export const submitOnboardingBasicDetails = createAction(ACTION_TYPES.ONBOARDING_BASIC_DETAILS_SUBMIT);
export const submitOnboardingAgreementDetails = createAction(ACTION_TYPES.ONBOARDING_AGREEMENT_DETAILS_SUBMIT);
export const submitOnboardingBankDetails = createAction(ACTION_TYPES.ONBOARDING_BANK_DETAILS_SUBMIT);
export const submitOnboardingKycGstDetails = createAction(ACTION_TYPES.ONBOARDING_KYC_GST_DETAILS_SUBMIT);
export const submitOnboardingSupportingDocuments = createAction(ACTION_TYPES.ONBOARDING_SUPPORTING_DOCUMENTS_SUBMIT);
export const submitOnboardingSingleDocument = createAction(ACTION_TYPES.ONBOARDING_SINGLE_DOCUMENT_SUBMIT);
export const searchOnboardingGstDetails = createAction(ACTION_TYPES.ONBOARDING_GST_DETAILS_SEARCH);
export const fetchOnboardingPopName = createAction(ACTION_TYPES.ONBOARDING_POP_NAME_FETCH);
export const fetchOnboardingPincode = createAction(ACTION_TYPES.ONBOARDING_PINCODE_FETCH);
export const fetchOnboardingPostoffice = createAction(ACTION_TYPES.ONBOARDING_POSTOFFICE_FETCH);
export const fetchOnboardingIfscDetails = createAction(ACTION_TYPES.ONBOARDING_IFSC_DETAILS_FETCH);
export const fetchOnboardingCompanyNature = createAction(ACTION_TYPES.ONBOARDING_COMPANY_NATURE_FETCH);
export const fetchOnboardingBankAccountType = createAction(ACTION_TYPES.ONBOARDING_BANK_ACCOUNT_TYPE_FETCH);
export const fetchOnboardingSharePlan = createAction(ACTION_TYPES.ONBOARDING_SHARE_PLAN_FETCH);
export const fetchLnpPartnersList = createAction(ACTION_TYPES.LNP_PARTNERS_LIST_FETCH);
export const fetchLnpPartnerStatusDropdown = createAction(ACTION_TYPES.LNP_PARTNER_STATUS_DROPDOWN_FETCH);
export const updateLnpPartner = createAction(ACTION_TYPES.LNP_PARTNER_UPDATE);
export const fetchAgnpPartnersList = createAction(ACTION_TYPES.AGNP_PARTNERS_LIST_FETCH);
export const updateAgnpPartner = createAction(ACTION_TYPES.AGNP_PARTNER_UPDATE);
export const fetchVlanMappingData = createAction(ACTION_TYPES.ONBOARDING_VLAN_MAPPING_DATA_FETCH);
export const submitVlanMapping = createAction(ACTION_TYPES.ONBOARDING_VLAN_MAPPING_SUBMIT);
export const updateVlanMapping = createAction(ACTION_TYPES.ONBOARDING_VLAN_MAPPING_UPDATE);
export const fetchVlanRequestData = createAction(ACTION_TYPES.ONBOARDING_VLAN_REQUEST_DATA_FETCH);
export const submitVlanRequest = createAction(ACTION_TYPES.ONBOARDING_VLAN_REQUEST_SUBMIT);
export const fetchVlanTypeList = createAction(ACTION_TYPES.FETCH_VLAN_TYPE_LIST);
export const fetchVlanPartnerList = createAction(ACTION_TYPES.FETCH_VLAN_PARTNER_LIST);
export const fetchOnboardingDetails = createAction(ACTION_TYPES.FETCH_ONBOARDING_DETAILS);
export const fetchPartnerEnquiry = createAction(ACTION_TYPES.FETCH_PARTNER_ENQUIRY);
export const submitOnboarding = createAction(ACTION_TYPES.ONBOARDING_FINAL_SUBMIT);
export const fetchSingleOnboardingData = createAction(ACTION_TYPES.FETCH_SINGLE_ONBOARDING_DATA);
export const resetPassword = createAction(ACTION_TYPES.RESET_PASSWORD);
export const downloadAgnpListCsv = createAction(ACTION_TYPES.DOWNLOAD_AGNP_LIST_CSV);
export const addServiceArea = createAction(ACTION_TYPES.ADD_SERVICE_AREA);
export const fetchOltDeviceList = createAction(ACTION_TYPES.FETCH_OLT_DEVICE_LIST);
export const fileStorageUpload = createAction(ACTION_TYPES.FILE_STORAGE_UPLOAD);
export const fileStorageDelete = createAction(ACTION_TYPES.FILE_STORAGE_DELETE);
export const fileStorageViewUrl = createAction(ACTION_TYPES.FILE_STORAGE_VIEW_URL);
export const deleteOnboardingDocument = createAction(ACTION_TYPES.ONBOARDING_DOCUMENT_DELETE);
export const fetchPartnersAll = createAction(ACTION_TYPES.PARTNERS_FETCH_ALL);
export const fetchPartnerDetailsById = createAction(ACTION_TYPES.FETCH_PARTNER_DETAILS_BY_ID);
export const updatePartnerDetails = createAction(ACTION_TYPES.UPDATE_PARTNER_DETAILS);
export const fetchLinkTypeOptions = createAction(ACTION_TYPES.FETCH_LINK_TYPE_OPTIONS);
export const fetchLinkEstablishmentStatusOptions = createAction(ACTION_TYPES.FETCH_LINK_ESTABLISHMENT_STATUS_OPTIONS);
export const fetchFrcReceivedOptions = createAction(ACTION_TYPES.FETCH_FRC_RECEIVED_OPTIONS);
export const downloadPartnerListCsv = createAction(ACTION_TYPES.DOWNLOAD_PARTNER_LIST_CSV);
export const downloadPartnerEnquiryCsv = createAction(ACTION_TYPES.DOWNLOAD_PARTNER_ENQUIRY_CSV);
export const downloadVlanMappingsCsv = createAction(ACTION_TYPES.DOWNLOAD_VLAN_MAPPINGS_CSV);
export const fetchPartnerForwardUsers = createAction(ACTION_TYPES.FETCH_PARTNER_FORWARD_USERS);
export const forwardPartnerEnquiry = createAction(ACTION_TYPES.FORWARD_PARTNER_ENQUIRY);
export const forwardAgnpEnquiry = createAction(ACTION_TYPES.FORWARD_AGNP_ENQUIRY);
export const assignEnquiry = createAction(ACTION_TYPES.ASSIGN_ENQUIRY);
export const assignEnquiryToPreviousUser = createAction(ACTION_TYPES.ASSIGN_ENQUIRY_TO_PREVIOUS_USER);
export const updateOnboardingPop = createAction(ACTION_TYPES.ONBOARDING_POP_UPDATE);
