import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

const API_ACTION_TYPES = {
  ROLE_CREATION_MENU_FETCH: `${STATE_REDUCER_KEY}/ROLE_CREATION_MENU_FETCH`,
  FETCH_ALL_ROLE: `${STATE_REDUCER_KEY}/FETCH_ALL_ROLE`,
  FETCH_BUISINESS_UNIT: `${STATE_REDUCER_KEY}/FETCH_BUISINESS_UNIT`,
  CREATE_USER_SUBMIT: `${STATE_REDUCER_KEY}/CREATE_USER_SUBMIT`,
  UPDATE_USER_SUBMIT: `${STATE_REDUCER_KEY}/UPDATE_USER_SUBMIT`,
  USER_LIST_FETCH: `${STATE_REDUCER_KEY}/USER_LIST_FETCH`,
  ROLE_PERMISSION_SUBMIT: `${STATE_REDUCER_KEY}/ROLE_PERMISSION_SUBMIT`,
  FETCH_USER_ROLE_LIST: `${STATE_REDUCER_KEY}/FETCH_USER_ROLE_LIST`,
  FETCH_EDIT_USER_PERMISSION: `${STATE_REDUCER_KEY}/FETCH_EDIT_USER_PERMISSION`,
  DOWNLOAD_USER_LIST_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_USER_LIST_CSV`,
  UPDATE_ROLE_PERMISSION: `${STATE_REDUCER_KEY}/UPDATE_ROLE_PERMISSION`,
  CLEAR_EDIT_USER_PERMISSION: `${STATE_REDUCER_KEY}/CLEAR_EDIT_USER_PERMISSION`,
  RESET_USER_ROLE_FORM: `${STATE_REDUCER_KEY}/RESET_USER_ROLE_FORM`,
  USER_MAPPING_SUBMIT: `${STATE_REDUCER_KEY}/USER_MAPPING_SUBMIT`,
  CREATE_SEAT_SUBMIT: `${STATE_REDUCER_KEY}/CREATE_SEAT_SUBMIT`,
  UPDATE_SEAT_SUBMIT: `${STATE_REDUCER_KEY}/UPDATE_SEAT_SUBMIT`,
  FETCH_SEAT_LIST: `${STATE_REDUCER_KEY}/FETCH_SEAT_LIST`,
  FETCH_ORGANIZATION: `${STATE_REDUCER_KEY}/FETCH_ORGANIZATION`,
  FETCH_ROLE_BY_USER: `${STATE_REDUCER_KEY}/FETCH_ROLE_BY_USER`,
  LINK_USER: `${STATE_REDUCER_KEY}/LINK_USER`,
  FETCH_UNMAPPED_USER: `${STATE_REDUCER_KEY}/FETCH_UNMAPPED_USER`,
  FETCH_ZONE: `${STATE_REDUCER_KEY}/FETCH_ZONE`,
  FETCH_SEAT_PERMISSION: `${STATE_REDUCER_KEY}/FETCH_SEAT_PERMISSION`,
  UPDATE_USER_MAPPING: `${STATE_REDUCER_KEY}/UPDATE_USER_MAPPING`,
  FETCH_PINCODE_BY_DISTRICT_IDS: `${STATE_REDUCER_KEY}/FETCH_PINCODE_BY_DISTRICT_IDS`,
  SUBMIT_PINCODE_MAPPING: `${STATE_REDUCER_KEY}/SUBMIT_PINCODE_MAPPING`,
  DELINK_USER: `${STATE_REDUCER_KEY}/DELINK_USER`,
  SUBMIT_TEMPLATE: `${STATE_REDUCER_KEY}/SUBMIT_TEMPLATE`,
  FETCH_TEMPLATE_LIST: `${STATE_REDUCER_KEY}/FETCH_TEMPLATE_LIST`,
  EDIT_TEMPLATE: `${STATE_REDUCER_KEY}/EDIT_TEMPLATE`,
  FETCH_DESIGNATION: `${STATE_REDUCER_KEY}/FETCH_DESIGNATION`,
  FETCH_MAPPED_DIST: `${STATE_REDUCER_KEY}/FETCH_MAPPED_DIST`,
  RESET_MAPPED_DIST: `${STATE_REDUCER_KEY}/RESET_MAPPED_DIST`,
  UPDATE_PINCODE_MAPPING: `${STATE_REDUCER_KEY}/UPDATE_PINCODE_MAPPING`,
  DOWNLOAD_SEAT_LIST_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_SEAT_LIST_CSV`,
  DOWNLOAD_ROLE_LIST_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_ROLE_LIST_CSV`,
  FETCH_DESIGNATION_LIST: `${STATE_REDUCER_KEY}/FETCH_DESIGNATION_LIST`,
  CREATE_DESIGNATION_SUBMIT: `${STATE_REDUCER_KEY}/CREATE_DESIGNATION_SUBMIT`,
  UPDATE_DESIGNATION_SUBMIT: `${STATE_REDUCER_KEY}/UPDATE_DESIGNATION_SUBMIT`,
  UPDATE_ROLE_STATUS: `${STATE_REDUCER_KEY}/UPDATE_ROLE_STATUS`,
  FETCH_WORKFLOW_TYPES: `${STATE_REDUCER_KEY}/FETCH_WORKFLOW_TYPES`,
  FETCH_WORKFLOW_SUBTYPES: `${STATE_REDUCER_KEY}/FETCH_WORKFLOW_SUBTYPES`,
  CLEAR_WORKFLOW_SUBTYPES: `${STATE_REDUCER_KEY}/CLEAR_WORKFLOW_SUBTYPES`,
  FETCH_SEAT_BY_ROLES: `${STATE_REDUCER_KEY}/FETCH_SEAT_BY_ROLES`,
  CLEAR_SEAT_BY_ROLES: `${STATE_REDUCER_KEY}/CLEAR_SEAT_BY_ROLES`,
  SAVE_STAGE_CONFIG: `${STATE_REDUCER_KEY}/SAVE_STAGE_CONFIG`,
  FETCH_STAGE_CONFIG: `${STATE_REDUCER_KEY}/FETCH_STAGE_CONFIG`,
  UPDATE_STAGE_CONFIG: `${STATE_REDUCER_KEY}/UPDATE_STAGE_CONFIG`,
  DELETE_STAGE_CONFIG: `${STATE_REDUCER_KEY}/DELETE_STAGE_CONFIG`,
  CLEAR_STAGE_CONFIG: `${STATE_REDUCER_KEY}/CLEAR_STAGE_CONFIG`,
  CREATE_DIVISION_SUBMIT: `${STATE_REDUCER_KEY}/CREATE_DIVISION_SUBMIT`,
  UPDATE_DIVISION_SUBMIT: `${STATE_REDUCER_KEY}/UPDATE_DIVISION_SUBMIT`,
  FETCH_DIVISION_LIST: `${STATE_REDUCER_KEY}/FETCH_DIVISION_LIST`,
  FETCH_DIVISION_BY_ORGANIZATION: `${STATE_REDUCER_KEY}/FETCH_DIVISION_BY_ORGANIZATION`,
  FETCH_FE_LNP_FE_USERS: `${STATE_REDUCER_KEY}/FETCH_FE_LNP_FE_USERS`,
  FETCH_FE_LNP_LNP_USERS: `${STATE_REDUCER_KEY}/FETCH_FE_LNP_LNP_USERS`,
  CLEAR_FE_LNP_FE_USERS: `${STATE_REDUCER_KEY}/CLEAR_FE_LNP_FE_USERS`,
  CLEAR_FE_LNP_LNP_USERS: `${STATE_REDUCER_KEY}/CLEAR_FE_LNP_LNP_USERS`,
  ATTACH_FE_LNP: `${STATE_REDUCER_KEY}/ATTACH_FE_LNP`,
  DETACH_FE_LNP: `${STATE_REDUCER_KEY}/DETACH_FE_LNP`
};

export const ACTION_TYPES = {
  ...API_ACTION_TYPES
};

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchRoleCreationMenu = createAction(ACTION_TYPES.ROLE_CREATION_MENU_FETCH);
export const fetchAllRole = createAction(ACTION_TYPES.FETCH_ALL_ROLE);
export const fetchBusinessUnit = createAction(ACTION_TYPES.FETCH_BUISINESS_UNIT);
export const createUserSubmit = createAction(ACTION_TYPES.CREATE_USER_SUBMIT);
export const updateUserSubmit = createAction(ACTION_TYPES.UPDATE_USER_SUBMIT);
export const fetchUserList = createAction(ACTION_TYPES.USER_LIST_FETCH);
export const rolePermissionSubmit = createAction(ACTION_TYPES.ROLE_PERMISSION_SUBMIT);
export const fetchUserRoleList = createAction(ACTION_TYPES.FETCH_USER_ROLE_LIST);
export const fetchEditUserPermission = createAction(ACTION_TYPES.FETCH_EDIT_USER_PERMISSION);
export const downloadUserListCsv = createAction(ACTION_TYPES.DOWNLOAD_USER_LIST_CSV);
export const updateRolePermission = createAction(ACTION_TYPES.UPDATE_ROLE_PERMISSION);
export const clearEditUserPermission = createAction(ACTION_TYPES.CLEAR_EDIT_USER_PERMISSION);
export const resetUserRoleForm = createAction(ACTION_TYPES.RESET_USER_ROLE_FORM);
export const userMappingSubmit = createAction(ACTION_TYPES.USER_MAPPING_SUBMIT);
export const createSeatSubmit = createAction(ACTION_TYPES.CREATE_SEAT_SUBMIT);
export const updateSeatSubmit = createAction(ACTION_TYPES.UPDATE_SEAT_SUBMIT);
export const fetchOrganization = createAction(ACTION_TYPES.FETCH_ORGANIZATION);
export const fetchSeatList = createAction(ACTION_TYPES.FETCH_SEAT_LIST);
export const fetchRoleByUser = createAction(ACTION_TYPES.FETCH_ROLE_BY_USER);
export const linkUser = createAction(ACTION_TYPES.LINK_USER);
export const fetchUnmappedUser = createAction(ACTION_TYPES.FETCH_UNMAPPED_USER);
export const fetchZone = createAction(ACTION_TYPES.FETCH_ZONE);
export const fetchSeatPermission = createAction(ACTION_TYPES.FETCH_SEAT_PERMISSION);
export const updateUserMapping = createAction(ACTION_TYPES.UPDATE_USER_MAPPING);
export const fetchPincodeByDistrictIds = createAction(ACTION_TYPES.FETCH_PINCODE_BY_DISTRICT_IDS);
export const submitPincodeMapping = createAction(ACTION_TYPES.SUBMIT_PINCODE_MAPPING);
export const delinkUser = createAction(ACTION_TYPES.DELINK_USER);
export const submitTemplate = createAction(ACTION_TYPES.SUBMIT_TEMPLATE);
export const fetchTemplateList = createAction(ACTION_TYPES.FETCH_TEMPLATE_LIST);
export const editTemplate = createAction(ACTION_TYPES.EDIT_TEMPLATE);
export const fetchDesignation = createAction(ACTION_TYPES.FETCH_DESIGNATION);
export const fetchMappedDist = createAction(ACTION_TYPES.FETCH_MAPPED_DIST);
export const resetMappedDist = createAction(ACTION_TYPES.RESET_MAPPED_DIST);
export const updatePincodeMapping = createAction(ACTION_TYPES.UPDATE_PINCODE_MAPPING);
export const downloadSeatListCsv = createAction(ACTION_TYPES.DOWNLOAD_SEAT_LIST_CSV);
export const downloadRoleListCsv = createAction(ACTION_TYPES.DOWNLOAD_ROLE_LIST_CSV);
export const fetchDesignationList = createAction(ACTION_TYPES.FETCH_DESIGNATION_LIST);
export const createDesignationSubmit = createAction(ACTION_TYPES.CREATE_DESIGNATION_SUBMIT);
export const updateDesignationSubmit = createAction(ACTION_TYPES.UPDATE_DESIGNATION_SUBMIT);
export const updateRoleStatus = createAction(ACTION_TYPES.UPDATE_ROLE_STATUS);
export const fetchWorkflowTypes = createAction(ACTION_TYPES.FETCH_WORKFLOW_TYPES);
export const fetchWorkflowSubtypes = createAction(ACTION_TYPES.FETCH_WORKFLOW_SUBTYPES);
export const clearWorkflowSubtypes = createAction(ACTION_TYPES.CLEAR_WORKFLOW_SUBTYPES);
export const fetchSeatsByRoles = createAction(ACTION_TYPES.FETCH_SEAT_BY_ROLES);
export const clearSeatsByRoles = createAction(ACTION_TYPES.CLEAR_SEAT_BY_ROLES);
export const saveStageConfig = createAction(ACTION_TYPES.SAVE_STAGE_CONFIG);
export const fetchStageConfig = createAction(ACTION_TYPES.FETCH_STAGE_CONFIG);
export const updateStageConfig = createAction(ACTION_TYPES.UPDATE_STAGE_CONFIG);
export const deleteStageConfig = createAction(ACTION_TYPES.DELETE_STAGE_CONFIG);
export const clearStageConfig = createAction(ACTION_TYPES.CLEAR_STAGE_CONFIG);
export const createDivisionSubmit = createAction(ACTION_TYPES.CREATE_DIVISION_SUBMIT);
export const updateDivisionSubmit = createAction(ACTION_TYPES.UPDATE_DIVISION_SUBMIT);
export const fetchDivisionList = createAction(ACTION_TYPES.FETCH_DIVISION_LIST);
export const fetchDivisionByOrganization = createAction(ACTION_TYPES.FETCH_DIVISION_BY_ORGANIZATION);
export const fetchFeLnpFeUsers = createAction(ACTION_TYPES.FETCH_FE_LNP_FE_USERS);
export const fetchFeLnpLnpUsers = createAction(ACTION_TYPES.FETCH_FE_LNP_LNP_USERS);
export const clearFeLnpFeUsers = createAction(ACTION_TYPES.CLEAR_FE_LNP_FE_USERS);
export const clearFeLnpLnpUsers = createAction(ACTION_TYPES.CLEAR_FE_LNP_LNP_USERS);
export const attachFeLnp = createAction(ACTION_TYPES.ATTACH_FE_LNP);
export const detachFeLnp = createAction(ACTION_TYPES.DETACH_FE_LNP);
