import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

const API_ACTION_TYPES = {
  FETCH_LNP_SUMMARY_DETAILS: `${STATE_REDUCER_KEY}/FETCH_LNP_SUMMARY_DETAILS`,
  FETCH_LNP_SUMMARY_CORPORATE: `${STATE_REDUCER_KEY}/FETCH_LNP_SUMMARY_CORPORATE`,
  FETCH_GSTIN_STATUS_LNP: `${STATE_REDUCER_KEY}/FETCH_GSTIN_STATUS_LNP`,
  FETCH_SUBSCRIBER_SUMMARY_DETAILS: `${STATE_REDUCER_KEY}/FETCH_SUBSCRIBER_SUMMARY_DETAILS`,
  FETCH_LNP_SPECIAL_INCENTIVE: `${STATE_REDUCER_KEY}/FETCH_LNP_SPECIAL_INCENTIVE`,
  FETCH_AGNP_SUMMARY: `${STATE_REDUCER_KEY}/FETCH_AGNP_SUMMARY`,
  FETCH_INVOICE_WISE_AGEING_REPORT: `${STATE_REDUCER_KEY}/FETCH_INVOICE_WISE_AGEING_REPORT`,
  FETCH_INVOICE_PAYMENT_REPORT: `${STATE_REDUCER_KEY}/FETCH_INVOICE_PAYMENT_REPORT`,
  FETCH_RETENTION_INCENTIVE_REPORT: `${STATE_REDUCER_KEY}/FETCH_RETENTION_INCENTIVE_REPORT`,
  FETCH_CORPORATE_CUSTOMER_PAYMENT: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_CUSTOMER_PAYMENT`,
  FETCH_CORPORATE_INVOICE_PAYMENT: `${STATE_REDUCER_KEY}/FETCH_CORPORATE_INVOICE_PAYMENT`
};

export const ACTION_TYPES = {
  ...API_ACTION_TYPES
};

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchLNPSummaryDetails = createAction(ACTION_TYPES.FETCH_LNP_SUMMARY_DETAILS);

export const fetchLNPSummaryCorporate = createAction(ACTION_TYPES.FETCH_LNP_SUMMARY_CORPORATE);

export const fetchGSTINStatusLNP = createAction(ACTION_TYPES.FETCH_GSTIN_STATUS_LNP);

export const fetchSubscriberSummaryDetails = createAction(ACTION_TYPES.FETCH_SUBSCRIBER_SUMMARY_DETAILS);

export const fetchLNPSpecialIncentive = createAction(ACTION_TYPES.FETCH_LNP_SPECIAL_INCENTIVE);

export const fetchAGNPSummary = createAction(ACTION_TYPES.FETCH_AGNP_SUMMARY);

export const fetchInvoiceWiseAgeingReport = createAction(ACTION_TYPES.FETCH_INVOICE_WISE_AGEING_REPORT);

export const fetchInvoicePaymentReport = createAction(ACTION_TYPES.FETCH_INVOICE_PAYMENT_REPORT);

export const fetchRetentionIncentiveReport = createAction(ACTION_TYPES.FETCH_RETENTION_INCENTIVE_REPORT);

export const fetchCorporateCustomerPayment = createAction(ACTION_TYPES.FETCH_CORPORATE_CUSTOMER_PAYMENT);

export const fetchCorporateInvoicePayment = createAction(ACTION_TYPES.FETCH_CORPORATE_INVOICE_PAYMENT);
