export const STATE_REDUCER_KEY = 'invoice-details';

export const SUBSCRIBER_FILTER_OPTIONS = [
  { id: 'view_all', name: 'View All' },
  { id: 'username', name: 'Username' },
  { id: 'package', name: 'Package' },
  { id: 'fallback_status', name: 'Fall Back Status' },
  { id: 'renewal_date', name: 'Renewal Date' },
  { id: 'balance', name: 'Balance' },
  { id: 'mobile_no', name: 'Mobile No.' },
  { id: 'email', name: 'Email' },
  { id: 'updated_date', name: 'Updated Date' },
  { id: 'gstin', name: 'GSTIN' },
  { id: 'ont_mapped', name: 'ONT Mapped' }
];

export const REPORTS_TABLE_CONFIG = {
  LNP_SUMMARY_DETAILS: {
    title: 'lnpSummaryDetails',
    columns: [
      { accessor: 'lnpId', header: 'lnpId' },
      { accessor: 'lnp', header: 'lnp' },
      { accessor: 'invoiceNo', header: 'invoiceNo' },
      { accessor: 'revenueExclGst', header: 'Revenue (excl.GST)' },
      { accessor: 'revenueExclGstOnline', header: 'Revenue (excl.GST) (Online Recharge)' },
      { accessor: 'revenueExclGstEws', header: 'Revenue (excl.GST) (EWS)' },
      { accessor: 'revenueNormalRecharges', header: 'Revenue generated on normal recharges' },
      { accessor: 'dot', header: 'dot' },
      { accessor: 'agr', header: 'agr' },
      { accessor: 'isp', header: 'isp' },
      { accessor: 'msp', header: 'msp' },
      { accessor: 'lnp50', header: 'lnp50' },
      { accessor: 'incentive', header: 'incentive' },
      { accessor: 'partnerRevenue', header: 'partnerRevenue' },
      { accessor: 'sgstUgst', header: 'sgstUgst' },
      { accessor: 'cgst', header: 'cgst' },
      { accessor: 'igst', header: 'igst' },
      { accessor: 'totalGst', header: 'totalGst' },
      { accessor: 'invoiceValue', header: 'invoiceValue' }
    ]
  },
  LNP_SUMMARY_CORPORATE: {
    title: 'lnpSummaryCorporate',
    columns: [
      { accessor: 'lnpId', header: 'lnpId' },
      { accessor: 'lnp', header: 'lnp' },
      { accessor: 'agnpId', header: 'agnpId' },
      { accessor: 'agnpName', header: 'agnpName' },
      { accessor: 'invoiceNo', header: 'invoiceNo' },
      { accessor: 'workorderId', header: 'workorderId' },
      { accessor: 'locationInvoice', header: 'locationInvoice' },
      { accessor: 'customerName', header: 'customerName' },
      { accessor: 'locationName', header: 'locationName' },
      { accessor: 'package', header: 'package' },
      { accessor: 'revenueFromSubscriber', header: 'revenueFromSubscriber' },
      { accessor: 'dot', header: 'dot' },
      { accessor: 'agr', header: 'agr' },
      { accessor: 'isp', header: 'isp' },
      { accessor: 'agnpRevenueShare', header: 'agnpRevenueShare' },
      { accessor: 'lnpRevenueShare', header: 'lnpRevenueShare' },
      { accessor: 'sgstUgst', header: 'sgstUgst' },
      { accessor: 'cgst', header: 'cgst' },
      { accessor: 'igst', header: 'igst' },
      { accessor: 'totalGst', header: 'totalGst' },
      { accessor: 'totalInvoiceValue', header: 'totalInvoiceValue' },
      { accessor: 'tds', header: 'tds' },
      { accessor: 'sgstTds', header: 'sgstTds' },
      { accessor: 'cgstTds', header: 'cgstTds' },
      { accessor: 'netPayable', header: 'netPayable' },
      { accessor: 'invoiceDate', header: 'invoiceDate' }
    ]
  },
  GSTIN_STATUS_LNP: {
    title: 'gstinStatusLnp',
    columns: [
      { accessor: 'slNo', header: 'slNo' },
      { accessor: 'lnpId', header: 'lnpId' },
      { accessor: 'compName', header: 'compName' },
      { accessor: 'district', header: 'district' },
      { accessor: 'category', header: 'category' },
      { accessor: 'gstinInBss', header: 'gstinInBss' },
      { accessor: 'taxpayerTypeInBss', header: 'taxpayerTypeInBss' },
      { accessor: 'taxpayerTypeInGstPortal', header: 'taxpayerTypeInGstPortal' },
      { accessor: 'gstinStatus', header: 'gstinStatus' },
      { accessor: 'gstinCancellationDate', header: 'gstinCancellationDate' }
    ]
  },
  SUBSCRIBER_SUMMARY_DETAILS: {
    title: 'subscriberSummaryDetails',
    columns: [
      { accessor: 'lnpId', header: 'lnpId' },
      { accessor: 'lnp', header: 'lnp' },
      { accessor: 'district', header: 'district' },
      { accessor: 'agnpId', header: 'agnpId' },
      { accessor: 'agnpName', header: 'agnpName' },
      { accessor: 'invoiceNo', header: 'invoiceNo' },
      { accessor: 'invoiceDate', header: 'invoiceDate' },
      { accessor: 'subscriberId', header: 'subscriberId' },
      { accessor: 'subscriberName', header: 'subscriberName' },
      { accessor: 'package', header: 'package' },
      { accessor: 'revenueFromSubscriber', header: 'revenueFromSubscriber' },
      { accessor: 'dot', header: 'dot' },
      { accessor: 'agr', header: 'agr' },
      { accessor: 'isp', header: 'isp' },
      { accessor: 'agnpRevenueShare', header: 'agnpRevenueShare' },
      { accessor: 'lnpRevenueShare', header: 'lnpRevenueShare' },
      { accessor: 'sgstUgst', header: 'sgstUgst' },
      { accessor: 'cgst', header: 'cgst' },
      { accessor: 'igst', header: 'igst' },
      { accessor: 'totalGst', header: 'totalGst' },
      { accessor: 'totalInvoiceValue', header: 'totalInvoiceValue' }
    ]
  },
  LNP_SPECIAL_INCENTIVE: {
    title: 'lnpSpecialIncentive',
    columns: [
      { accessor: 'lnpId', header: 'lnpId' },
      { accessor: 'lnp', header: 'lnp' },
      { accessor: 'district', header: 'district' },
      { accessor: 'agnpId', header: 'agnpId' },
      { accessor: 'agnpName', header: 'agnpName' },
      { accessor: 'lnpInvoiceNo', header: 'lnpInvoiceNo' },
      { accessor: 'subscriberId', header: 'subscriberId' },
      { accessor: 'subscriberName', header: 'subscriberName' },
      { accessor: 'package', header: 'package' },
      { accessor: 'packageFee', header: 'packageFee' },
      { accessor: 'subscriberInvoiceNo', header: 'subscriberInvoiceNo' },
      { accessor: 'subscriberInvoiceDate', header: 'subscriberInvoiceDate' },
      { accessor: 'incentiveScheme', header: 'incentiveScheme' },
      { accessor: 'incentiveAmountPerSubscriber', header: 'incentiveAmountPerSubscriber' }
    ]
  },
  AGNP_SUMMARY: {
    title: 'agnpSummary',
    columns: [
      { accessor: 'agnpId', header: 'agnpId' },
      { accessor: 'agnpName', header: 'agnpName' },
      { accessor: 'lnpId', header: 'lnpId' },
      { accessor: 'lnp', header: 'lnp' },
      { accessor: 'invoiceNo', header: 'invoiceNo' },
      { accessor: 'workorderId', header: 'workorderId' },
      { accessor: 'lnpInvoice', header: 'lnpInvoice' },
      { accessor: 'customerInvoice', header: 'customerInvoice' },
      { accessor: 'customerName', header: 'customerName' },
      { accessor: 'locationName', header: 'locationName' },
      { accessor: 'package', header: 'package' },
      { accessor: 'revenueFromSubscriber', header: 'revenueFromSubscriber' },
      { accessor: 'dot', header: 'dot' },
      { accessor: 'agr', header: 'agr' },
      { accessor: 'isp', header: 'isp' },
      { accessor: 'agnpRevenueShare', header: 'agnpRevenueShare' },
      { accessor: 'lnpRevenueShare', header: 'lnpRevenueShare' },
      { accessor: 'sgstUgst', header: 'sgstUgst' },
      { accessor: 'cgst', header: 'cgst' },
      { accessor: 'igst', header: 'igst' },
      { accessor: 'totalGst', header: 'totalGst' },
      { accessor: 'totalInvoiceValue', header: 'totalInvoiceValue' },
      { accessor: 'tds', header: 'tds' },
      { accessor: 'sgstTds', header: 'sgstTds' },
      { accessor: 'cgstTds', header: 'cgstTds' },
      { accessor: 'netPayable', header: 'netPayable' },
      { accessor: 'invoiceDate', header: 'invoiceDate' }
    ]
  },
  INVOICE_WISE_AGEING_REPORT: {
    title: 'invoiceWiseAgeingReport',
    columns: [
      { accessor: 'incomeType', header: 'incomeType' },
      { accessor: 'entityType', header: 'entityType' },
      { accessor: 'invoiceDate', header: 'invoiceDate' },
      { accessor: 'invoiceNo', header: 'invoiceNo' },
      { accessor: 'customerId', header: 'customerId' },
      { accessor: 'customerName', header: 'customerName' },
      { accessor: 'gstin', header: 'gstin' },
      { accessor: 'taxpayerType', header: 'taxpayerType' },
      { accessor: 'serviceStartDate', header: 'serviceStartDate' },
      { accessor: 'serviceEndDate', header: 'serviceEndDate' },
      { accessor: 'taxableValue', header: 'taxableValue' },
      { accessor: 'cgst9', header: 'cgst9' },
      { accessor: 'sgst9', header: 'sgst9' },
      { accessor: 'invoiceValue', header: 'invoiceValue' },
      { accessor: 'totalPaymentReceivedInBank', header: 'totalPaymentReceivedInBank' },
      { accessor: 'itTdsReceivable', header: 'itTdsReceivable' },
      { accessor: 'gstTdsReceivable', header: 'gstTdsReceivable' },
      { accessor: 'totalPaymentReceived', header: 'totalPaymentReceived' },
      { accessor: 'creditNoteValue', header: 'creditNoteValue' },
      { accessor: 'outstandingAmount', header: 'outstandingAmount' },
      { accessor: 'noOfAgeingDays', header: 'noOfAgeingDays' },
      { accessor: 'osPeriod', header: 'osPeriod' },
      { accessor: 'salesActor', header: 'salesActor' },
      { accessor: 'customerAuthorisedPersonName', header: 'customerAuthorisedPersonName' },
      { accessor: 'contactNumber', header: 'contactNumber' }
    ]
  },
  INVOICE_PAYMENT_REPORT: {
    title: 'invoicePaymentReport',
    columns: [
      { accessor: 'partnerId', header: 'partnerId' },
      { accessor: 'partnerCompanyName', header: 'partnerCompanyName' },
      { accessor: 'billType', header: 'billType' },
      { accessor: 'invoiceType', header: 'invoiceType' },
      { accessor: 'invoiceNo', header: 'invoiceNo' },
      { accessor: 'taxableValue', header: 'taxableValue' },
      { accessor: 'gst', header: 'gst' },
      { accessor: 'invoiceValue', header: 'invoiceValue' },
      { accessor: 'itTds', header: 'itTds' },
      { accessor: 'gstTds', header: 'gstTds' },
      { accessor: 'netPayable', header: 'netPayable' },
      { accessor: 'paidAmount', header: 'paidAmount' },
      { accessor: 'balanceToPay', header: 'balanceToPay' },
      { accessor: 'createdDate', header: 'createdDate' }
    ]
  },
  RETENTION_INCENTIVE_REPORT: {
    title: 'retentionIncentiveReport',
    columns: [
      { accessor: 'partnerId', header: 'partnerId' },
      { accessor: 'partnerCompanyName', header: 'partnerCompanyName' },
      { accessor: 'district', header: 'district' },
      { accessor: 'invoiceNo', header: 'invoiceNo' },
      { accessor: 'invoiceDate', header: 'invoiceDate' },
      { accessor: 'bssInvoiceTaxableValue', header: 'bssInvoiceTaxableValue' },
      { accessor: 'bssInvoiceGstValue', header: 'bssInvoiceGstValue' },
      { accessor: 'bssInvoiceTotalInvoiceValue', header: 'bssInvoiceTotalInvoiceValue' },
      { accessor: 'month1SubscriberCount', header: 'month1SubscriberCount' },
      { accessor: 'month2SubscriberCount', header: 'month2SubscriberCount' },
      { accessor: 'month3SubscriberCount', header: 'month3SubscriberCount' },
      { accessor: 'incentiveSlab', header: 'incentiveSlab' },
      { accessor: 'incentiveValue', header: 'incentiveValue' },
      { accessor: 'incentiveReversalDocumentNumber', header: 'incentiveReversalDocumentNumber' },
      { accessor: 'incentiveReversalValueExclGst', header: 'incentiveReversalValueExclGst' },
      { accessor: 'incentiveReversalValueInclGst', header: 'incentiveReversalValueInclGst' },
      { accessor: 'netIncentiveValue', header: 'netIncentiveValue' },
      { accessor: 'totalGst', header: 'totalGst' },
      { accessor: 'totalIncentiveValue', header: 'totalIncentiveValue' },
      { accessor: 'totalTds', header: 'totalTds' },
      { accessor: 'netIncentivePayable', header: 'netIncentivePayable' }
    ]
  },
  CORPORATE_CUSTOMER_PAYMENT: {
    title: 'corporateCustomerPayment',
    columns: [
      { accessor: 'customerId', header: 'customerId' },
      { accessor: 'customerName', header: 'customerName' },
      { accessor: 'contactPersonName', header: 'contactPersonName' },
      { accessor: 'contactMobile', header: 'contactMobile' },
      { accessor: 'contactEmail', header: 'contactEmail' },
      { accessor: 'companyType', header: 'companyType' },
      { accessor: 'district', header: 'district' },
      { accessor: 'pincode', header: 'pincode' },
      { accessor: 'bankPaymentValue', header: 'bankPaymentValue' },
      { accessor: 'paymentDate', header: 'paymentDate' },
      { accessor: 'paymentUtr', header: 'paymentUtr' },
      { accessor: 'locationPaymentAccounted', header: 'locationPaymentAccounted' },
      { accessor: 'otcPaymentAccounted', header: 'otcPaymentAccounted' },
      { accessor: 'paymentBalanceToAccount', header: 'paymentBalanceToAccount' },
      { accessor: 'document', header: 'document' }
    ]
  },
  CORPORATE_INVOICE_PAYMENT: {
    title: 'corporateInvoicePayment',
    columns: [
      { accessor: 'state', header: 'state' },
      { accessor: 'customerName', header: 'customerName' },
      { accessor: 'customerType', header: 'customerType' },
      { accessor: 'nldServicetype', header: 'nldServicetype' },
      { accessor: 'invoiceDate', header: 'invoiceDate' },
      { accessor: 'invoiceNo', header: 'invoiceNo' },
      { accessor: 'locationCode', header: 'locationCode' },
      { accessor: 'locationName', header: 'locationName' },
      { accessor: 'serviceType', header: 'serviceType' },
      { accessor: 'serviceName', header: 'serviceName' },
      { accessor: 'category', header: 'category' },
      { accessor: 'serviceDays', header: 'serviceDays' },
      { accessor: 'locationGrandAmount', header: 'locationGrandAmount' },
      { accessor: 'locationItTdsAmount', header: 'locationItTdsAmount' },
      { accessor: 'locationGstTdsAmount', header: 'locationGstTdsAmount' },
      { accessor: 'locationBankPaidAmount', header: 'locationBankPaidAmount' },
      { accessor: 'otcGrandAmount', header: 'otcGrandAmount' },
      { accessor: 'otcItTdsAmount', header: 'otcItTdsAmount' },
      { accessor: 'otcGstTdsAmount', header: 'otcGstTdsAmount' },
      { accessor: 'otcBankPaidAmount', header: 'otcBankPaidAmount' },
      { accessor: 'creditnoteLocationGrandamount', header: 'creditnoteLocationGrandamount' },
      { accessor: 'creditnoteOtcGrandamount', header: 'creditnoteOtcGrandamount' }
    ]
  }
};
