import { createAction } from '@reduxjs/toolkit';

import { generateActionTypeVariants } from '@/utils/actionUtils';

import { STATE_REDUCER_KEY } from './constants';

export const API_ACTION_TYPES = {
  FETCH_DEVICE_LIST: `${STATE_REDUCER_KEY}/FETCH_DEVICE_LIST`,
  CREATE_DEVICE: `${STATE_REDUCER_KEY}/CREATE_DEVICE`,
  FETCH_DEVICE_LIST_DASHBOARD: `${STATE_REDUCER_KEY}/FETCH_DEVICE_LIST_DASHBOARD`,
  FETCH_TRANSFER_DEVICE_LIST: `${STATE_REDUCER_KEY}/FETCH_TRANSFER_DEVICE_LIST`,

  // Admin to Dc device transfer
  SUBMIT_DEVICE_TRANSFER: `${STATE_REDUCER_KEY}/SUBMIT_DEVICE_TRANSFER`,
  SUBMIT_MY_STOCK_TRANSFER: `${STATE_REDUCER_KEY}/SUBMIT_MY_STOCK_TRANSFER`,
  SUBMIT_DEVICE_CONDITION_UPDATE: `${STATE_REDUCER_KEY}/SUBMIT_DEVICE_CONDITION_UPDATE`,
  SUBMIT_RETURN_TO_OEM: `${STATE_REDUCER_KEY}/SUBMIT_RETURN_TO_OEM`,
  SUBMIT_BULK_DEVICE_TRANSFER: `${STATE_REDUCER_KEY}/SUBMIT_BULK_DEVICE_TRANSFER`,

  FETCH_DEVICE_TYPE_LIST: `${STATE_REDUCER_KEY}/FETCH_DEVICE_TYPE_LIST`,
  FETCH_DEVICE_TYPE_DROPDOWN: `${STATE_REDUCER_KEY}/FETCH_DEVICE_TYPE_DROPDOWN`,
  CREATE_DEVICE_TYPE: `${STATE_REDUCER_KEY}/CREATE_DEVICE_TYPE`,

  FETCH_DEVICE_MAKE_LIST: `${STATE_REDUCER_KEY}/FETCH_DEVICE_MAKE_LIST`,
  FETCH_DEVICE_MAKE_DROPDOWN: `${STATE_REDUCER_KEY}/FETCH_DEVICE_MAKE_DROPDOWN`,
  CREATE_DEVICE_MAKE: `${STATE_REDUCER_KEY}/CREATE_DEVICE_MAKE`,

  FETCH_DEVICE_CATEGORY_LIST: `${STATE_REDUCER_KEY}/FETCH_DEVICE_CATEGORY_LIST`,
  FETCH_DEVICE_CATEGORY_DROPDOWN: `${STATE_REDUCER_KEY}/FETCH_DEVICE_CATEGORY_DROPDOWN`,
  CREATE_DEVICE_CATEGORY: `${STATE_REDUCER_KEY}/CREATE_DEVICE_CATEGORY`,

  FETCH_DEVICE_MODEL_LIST: `${STATE_REDUCER_KEY}/FETCH_DEVICE_MODEL_LIST`,
  FETCH_DEVICE_MODEL_DROPDOWN: `${STATE_REDUCER_KEY}/FETCH_DEVICE_MODEL_DROPDOWN`,
  CREATE_DEVICE_MODEL: `${STATE_REDUCER_KEY}/CREATE_DEVICE_MODEL`,
  FETCH_DEVICE_MODEL_DETAILS: `${STATE_REDUCER_KEY}/FETCH_DEVICE_MODEL_DETAILS`,

  FETCH_DEVICE_VENDOR_LIST: `${STATE_REDUCER_KEY}/FETCH_DEVICE_VENDOR_LIST`,
  FETCH_DEVICE_VENDOR_DROPDOWN: `${STATE_REDUCER_KEY}/FETCH_DEVICE_VENDOR_DROPDOWN`,
  CREATE_DEVICE_VENDOR: `${STATE_REDUCER_KEY}/CREATE_DEVICE_VENDOR`,
  UPDATE_DEVICE_VENDOR: `${STATE_REDUCER_KEY}/UPDATE_DEVICE_VENDOR`,
  FETCH_DEVICE_VENDOR_DETAILS: `${STATE_REDUCER_KEY}/FETCH_DEVICE_VENDOR_DETAILS`,

  FETCH_ASSET_TYPE_DROPDOWN: `${STATE_REDUCER_KEY}/FETCH_ASSET_TYPE_DROPDOWN`,

  FETCH_USER_BY_ROLE: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ROLE`,

  DOWNLOAD_SAMPLE_DEVICE_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_SAMPLE_DEVICE_CSV`,
  DOWNLOAD_DEVICE_MODEL_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_DEVICE_MODEL_CSV`,
  DOWNLOAD_DEVICE_LIST_CSV: `${STATE_REDUCER_KEY}/DOWNLOAD_DEVICE_LIST_CSV`,
  FETCH_TRANSFER_DETAILS: `${STATE_REDUCER_KEY}/FETCH_TRANSFER_DETAILS`,
  FETCH_TRANSFER_DETAILS_LIST: `${STATE_REDUCER_KEY}/FETCH_TRANSFER_DETAILS_LIST`,
  ACKNOWLEDGE_DEVICE_TRANSFER: `${STATE_REDUCER_KEY}/ACKNOWLEDGE_DEVICE_TRANSFER`,
  UPDATE_TRANSFER_STATUS: `${STATE_REDUCER_KEY}/UPDATE_TRANSFER_STATUS`,
  FETCH_DEVICE_REQUESTS_LIST: `${STATE_REDUCER_KEY}/FETCH_DEVICE_REQUESTS_LIST`,
  CREATE_DEVICE_REQUESTS: `${STATE_REDUCER_KEY}/CREATE_DEVICE_REQUESTS`,
  FETCH_MSP_REQUEST_DETAILS: `${STATE_REDUCER_KEY}/FETCH_MSP_REQUEST_DETAILS`,
  APPROVE_DEVICE_REQUEST: `${STATE_REDUCER_KEY}/APPROVE_DEVICE_REQUEST`,
  ACKNOWLEDGE_DEVICE_REQUEST: `${STATE_REDUCER_KEY}/ACKNOWLEDGE_DEVICE_REQUEST`,
  FETCH_STOCK_TYPE_COUNT: `${STATE_REDUCER_KEY}/FETCH_STOCK_TYPE_COUNT`,
  FETCH_MY_STOCK_LIST: `${STATE_REDUCER_KEY}/FETCH_MY_STOCK_LIST`,
  FETCH_TRANSFERRED_STOCK_LIST: `${STATE_REDUCER_KEY}/FETCH_TRANSFERRED_STOCK_LIST`,
  FETCH_STOCK_DETAILS_LIST: `${STATE_REDUCER_KEY}/FETCH_STOCK_DETAILS_LIST`,
  APPROVE_OR_REJECT_STOCK: `${STATE_REDUCER_KEY}/APPROVE_OR_REJECT_STOCK`,
  FETCH_STOCK_BY_PONO: `${STATE_REDUCER_KEY}/FETCH_STOCK_BY_PONO`,
  FETCH_CATEGORY_COUNT: `${STATE_REDUCER_KEY}/FETCH_CATEGORY_COUNT`,
  FETCH_INVENTORY_DETAILS_LIST: `${STATE_REDUCER_KEY}/FETCH_INVENTORY_DETAILS_LIST`,
  SUBMIT_STOCK_REQUEST: `${STATE_REDUCER_KEY}/SUBMIT_STOCK_REQUEST`,
  SUBMIT_STOCK_RECEIVE: `${STATE_REDUCER_KEY}/SUBMIT_STOCK_RECEIVE`,
  FETCH_SEARCH_DEVICE: `${STATE_REDUCER_KEY}/FETCH_SEARCH_DEVICE`,
  SUBMIT_MAP_DEVICE: `${STATE_REDUCER_KEY}/SUBMIT_MAP_DEVICE`,
  SUBMIT_UNMAP_DEVICE: `${STATE_REDUCER_KEY}/SUBMIT_UNMAP_DEVICE`,
  FETCH_STOCK_TRACK: `${STATE_REDUCER_KEY}/FETCH_STOCK_TRACK`,
  SUBMIT_RECALL_DEVICE: `${STATE_REDUCER_KEY}/SUBMIT_RECALL_DEVICE`,
  FETCH_ALL_ROLES: `${STATE_REDUCER_KEY}/FETCH_ALL_ROLES`,
  FETCH_USERS_BY_ROLE_ID: `${STATE_REDUCER_KEY}/FETCH_USERS_BY_ROLE_ID`,
  FETCH_DEVICE_MAPPED_VALUES: `${STATE_REDUCER_KEY}/FETCH_DEVICE_MAPPED_VALUES`,
  FETCH_POP_NAME_DROPDOWN: `${STATE_REDUCER_KEY}/FETCH_POP_NAME_DROPDOWN`,
  FETCH_REPLACE_DEVICE_CONDITION: `${STATE_REDUCER_KEY}/FETCH_REPLACE_DEVICE_CONDITION`,
  SUBMIT_REPLACE_DEVICE: `${STATE_REDUCER_KEY}/SUBMIT_REPLACE_DEVICE`,
  SUBMIT_UPDATE_DEVICE_DETAILS: `${STATE_REDUCER_KEY}/SUBMIT_UPDATE_DEVICE_DETAILS`,
  FETCH_OEM_REQUEST_LIST: `${STATE_REDUCER_KEY}/FETCH_OEM_REQUEST_LIST`,
  SUBMIT_OEM_REMARK: `${STATE_REDUCER_KEY}/SUBMIT_OEM_REMARK`,
  SUBMIT_OEM_FORWARD: `${STATE_REDUCER_KEY}/SUBMIT_OEM_FORWARD`,
  SUBMIT_STOCK_TRANSFER: `${STATE_REDUCER_KEY}/SUBMIT_STOCK_TRANSFER`,
  FETCH_STOCK_STATUS_DROPDOWN: `${STATE_REDUCER_KEY}/FETCH_STOCK_STATUS_DROPDOWN`,
  FETCH_DEVICE_CONDITION_DROPDOWN: `${STATE_REDUCER_KEY}/FETCH_DEVICE_CONDITION_DROPDOWN`,
  FETCH_INVENTORY_DETAILS_BY_ID: `${STATE_REDUCER_KEY}/FETCH_INVENTORY_DETAILS_BY_ID`,
  DOWNLOAD_OEM_HANDOVER_PDF: `${STATE_REDUCER_KEY}/DOWNLOAD_OEM_HANDOVER_PDF`,
  FETCH_DEVICE_TYPE_FIELDS: `${STATE_REDUCER_KEY}/FETCH_DEVICE_TYPE_FIELDS`,
  SAVE_DEVICE_TYPE_FIELDS: `${STATE_REDUCER_KEY}/SAVE_DEVICE_TYPE_FIELDS`,
  SUBMIT_EXTERNAL_REQUEST: `${STATE_REDUCER_KEY}/SUBMIT_EXTERNAL_REQUEST`,
  FETCH_DEVICE_TYPE_CATEGORY: `${STATE_REDUCER_KEY}/FETCH_DEVICE_TYPE_CATEGORY`,
  FETCH_LNP_REQUESTS: `${STATE_REDUCER_KEY}/FETCH_LNP_REQUESTS`
};

export const API_ACTION_TYPE_VARIANTS = generateActionTypeVariants(API_ACTION_TYPES);

export const fetchDeviceList = createAction(API_ACTION_TYPES.FETCH_DEVICE_LIST);
export const fetchTransferDeviceList = createAction(API_ACTION_TYPES.FETCH_TRANSFER_DEVICE_LIST);
export const createDevice = createAction(API_ACTION_TYPES.CREATE_DEVICE);
export const fetchDeviceListDashboard = createAction(API_ACTION_TYPES.FETCH_DEVICE_LIST_DASHBOARD);
export const submitDeviceTransfer = createAction(API_ACTION_TYPES.SUBMIT_DEVICE_TRANSFER);
export const submitMyStockTransfer = createAction(API_ACTION_TYPES.SUBMIT_MY_STOCK_TRANSFER);
export const submitDeviceConditionUpdate = createAction(API_ACTION_TYPES.SUBMIT_DEVICE_CONDITION_UPDATE);
export const submitReturnToOem = createAction(API_ACTION_TYPES.SUBMIT_RETURN_TO_OEM);
export const submitBulkDeviceTransfer = createAction(API_ACTION_TYPES.SUBMIT_BULK_DEVICE_TRANSFER);
export const fetchDeviceRequestsList = createAction(API_ACTION_TYPES.FETCH_DEVICE_REQUESTS_LIST);
export const createDeviceRequests = createAction(API_ACTION_TYPES.CREATE_DEVICE_REQUESTS);
export const fetchMspRequestDetails = createAction(API_ACTION_TYPES.FETCH_MSP_REQUEST_DETAILS);
export const approveDeviceRequest = createAction(API_ACTION_TYPES.APPROVE_DEVICE_REQUEST);
export const acknowledgeDeviceRequest = createAction(API_ACTION_TYPES.ACKNOWLEDGE_DEVICE_REQUEST);
export const fetchStockTypeCount = createAction(API_ACTION_TYPES.FETCH_STOCK_TYPE_COUNT);
export const fetchMyStockList = createAction(API_ACTION_TYPES.FETCH_MY_STOCK_LIST);
export const fetchTransferredStockList = createAction(API_ACTION_TYPES.FETCH_TRANSFERRED_STOCK_LIST);
export const fetchStockDetailsList = createAction(API_ACTION_TYPES.FETCH_STOCK_DETAILS_LIST);
export const approveOrRejectStock = createAction(API_ACTION_TYPES.APPROVE_OR_REJECT_STOCK);
export const fetchStockByPoNo = createAction(API_ACTION_TYPES.FETCH_STOCK_BY_PONO);
export const fetchInventoryDetailsList = createAction(API_ACTION_TYPES.FETCH_INVENTORY_DETAILS_LIST);
export const submitStockRequest = createAction(API_ACTION_TYPES.SUBMIT_STOCK_REQUEST);
export const submitStockReceive = createAction(API_ACTION_TYPES.SUBMIT_STOCK_RECEIVE);
export const fetchSearchDevice = createAction(API_ACTION_TYPES.FETCH_SEARCH_DEVICE);
export const submitMapDevice = createAction(API_ACTION_TYPES.SUBMIT_MAP_DEVICE);
export const submitUnmapDevice = createAction(API_ACTION_TYPES.SUBMIT_UNMAP_DEVICE);
export const fetchStockTrack = createAction(API_ACTION_TYPES.FETCH_STOCK_TRACK);
export const submitRecallDevice = createAction(API_ACTION_TYPES.SUBMIT_RECALL_DEVICE);
export const submitStockTransfer = createAction(API_ACTION_TYPES.SUBMIT_STOCK_TRANSFER);

export const fetchDeviceTypeList = createAction(API_ACTION_TYPES.FETCH_DEVICE_TYPE_LIST);
export const fetchDeviceTypeDropdown = createAction(API_ACTION_TYPES.FETCH_DEVICE_TYPE_DROPDOWN);
export const createDeviceType = createAction(API_ACTION_TYPES.CREATE_DEVICE_TYPE);

export const fetchDeviceMakeList = createAction(API_ACTION_TYPES.FETCH_DEVICE_MAKE_LIST);
export const fetchDeviceMakeDropdown = createAction(API_ACTION_TYPES.FETCH_DEVICE_MAKE_DROPDOWN);
export const createDeviceMake = createAction(API_ACTION_TYPES.CREATE_DEVICE_MAKE);

export const fetchDeviceCategoryList = createAction(API_ACTION_TYPES.FETCH_DEVICE_CATEGORY_LIST);
export const fetchDeviceCategoryDropdown = createAction(API_ACTION_TYPES.FETCH_DEVICE_CATEGORY_DROPDOWN);
export const createDeviceCategory = createAction(API_ACTION_TYPES.CREATE_DEVICE_CATEGORY);

export const fetchDeviceModelList = createAction(API_ACTION_TYPES.FETCH_DEVICE_MODEL_LIST);
export const fetchDeviceModelDropdown = createAction(API_ACTION_TYPES.FETCH_DEVICE_MODEL_DROPDOWN);
export const createDeviceModel = createAction(API_ACTION_TYPES.CREATE_DEVICE_MODEL);
export const fetchDeviceModelDetails = createAction(API_ACTION_TYPES.FETCH_DEVICE_MODEL_DETAILS);
export const fetchCategoryCount = createAction(API_ACTION_TYPES.FETCH_CATEGORY_COUNT);

export const fetchDeviceVendorList = createAction(API_ACTION_TYPES.FETCH_DEVICE_VENDOR_LIST);
export const fetchDeviceVendorDropdown = createAction(API_ACTION_TYPES.FETCH_DEVICE_VENDOR_DROPDOWN);
export const createDeviceVendor = createAction(API_ACTION_TYPES.CREATE_DEVICE_VENDOR);
export const updateDeviceVendor = createAction(API_ACTION_TYPES.UPDATE_DEVICE_VENDOR);
export const fetchDeviceVendorDetails = createAction(API_ACTION_TYPES.FETCH_DEVICE_VENDOR_DETAILS);

export const fetchAssetTypes = createAction(API_ACTION_TYPES.FETCH_ASSET_TYPE_DROPDOWN);

export const fetchUserByRole = createAction(API_ACTION_TYPES.FETCH_USER_BY_ROLE);
export const fetchAllRoles = createAction(API_ACTION_TYPES.FETCH_ALL_ROLES);
export const fetchUsersByRoleId = createAction(API_ACTION_TYPES.FETCH_USERS_BY_ROLE_ID);
export const fetchDeviceMappedValues = createAction(API_ACTION_TYPES.FETCH_DEVICE_MAPPED_VALUES);
export const fetchPopNameDropdown = createAction(API_ACTION_TYPES.FETCH_POP_NAME_DROPDOWN);
export const fetchReplaceDeviceCondition = createAction(API_ACTION_TYPES.FETCH_REPLACE_DEVICE_CONDITION);
export const submitReplaceDevice = createAction(API_ACTION_TYPES.SUBMIT_REPLACE_DEVICE);
export const submitUpdateDeviceDetails = createAction(API_ACTION_TYPES.SUBMIT_UPDATE_DEVICE_DETAILS);
export const fetchOemRequestList = createAction(API_ACTION_TYPES.FETCH_OEM_REQUEST_LIST);
export const submitOemRemark = createAction(API_ACTION_TYPES.SUBMIT_OEM_REMARK);
export const submitOemForward = createAction(API_ACTION_TYPES.SUBMIT_OEM_FORWARD);
export const fetchStockStatusDropdown = createAction(API_ACTION_TYPES.FETCH_STOCK_STATUS_DROPDOWN);
export const fetchDeviceConditionDropdown = createAction(API_ACTION_TYPES.FETCH_DEVICE_CONDITION_DROPDOWN);
export const fetchInventoryDetailsById = createAction(API_ACTION_TYPES.FETCH_INVENTORY_DETAILS_BY_ID);
export const downloadOemHandoverPdf = createAction(API_ACTION_TYPES.DOWNLOAD_OEM_HANDOVER_PDF);

export const downloadSampleDeviceCSV = createAction(API_ACTION_TYPES.DOWNLOAD_SAMPLE_DEVICE_CSV);
export const downloadDeviceModelCsv = createAction(API_ACTION_TYPES.DOWNLOAD_DEVICE_MODEL_CSV);
export const downloadDeviceListCsv = createAction(API_ACTION_TYPES.DOWNLOAD_DEVICE_LIST_CSV);
export const fetchTransferDetails = createAction(API_ACTION_TYPES.FETCH_TRANSFER_DETAILS);
export const fetchTransferDetailsList = createAction(API_ACTION_TYPES.FETCH_TRANSFER_DETAILS_LIST);
export const acknowledgeDeviceTransfer = createAction(API_ACTION_TYPES.ACKNOWLEDGE_DEVICE_TRANSFER);
export const updateTransferStatus = createAction(API_ACTION_TYPES.UPDATE_TRANSFER_STATUS);
export const fetchDeviceTypeFields = createAction(API_ACTION_TYPES.FETCH_DEVICE_TYPE_FIELDS);
export const saveDeviceTypeFields = createAction(API_ACTION_TYPES.SAVE_DEVICE_TYPE_FIELDS);
export const submitExternalRequest = createAction(API_ACTION_TYPES.SUBMIT_EXTERNAL_REQUEST);
export const fetchDeviceTypeCategory = createAction(API_ACTION_TYPES.FETCH_DEVICE_TYPE_CATEGORY);
export const fetchLnpRequests = createAction(API_ACTION_TYPES.FETCH_LNP_REQUESTS);
